namespace Atc.Wpf.SourceGenerators.Tests.Generators;

[SuppressMessage("Design", "MA0048:File name must match type name", Justification = "OK.")]
public sealed partial class ViewModelGeneratorTests
{
    [Fact]
    public void ObservableProperty_Name()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial class TestViewModel
            {
                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }
            
                        name = value;
                        RaisePropertyChanged(nameof(Name));
                    }
                }
            }
            
            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_CustomName()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty("MyName)]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string MyName
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }
            
                        name = value;
                        RaisePropertyChanged(nameof(MyName));
                    }
                }
            }
            
            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_Name_SealedAccessor()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public sealed partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }
            
                        name = value;
                        RaisePropertyChanged(nameof(Name));
                    }
                }
            }
            
            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_Name_MainWindowViewModel()
    {
        const string inputCode =
            """
            namespace TestNamespace;
            
            public sealed partial class MainWindowViewModel : MainWindowViewModelBase
            {
                private readonly ILogger<MainWindowViewModel> logger;
                private BitmapImage? icon;
            
                public MainWindowViewModel(
                    ILogger<MainWindowViewModel> logger,
                    StatusBarViewModel statusBarViewModel,
                    IOptions<BasicApplicationOptions> applicationOptions)
                {
                    this.logger = logger;
            
                    Test = "Hello World";
                }
            
                [ObservableProperty]
                private string? name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class MainWindowViewModel
            {
                public string? Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }
            
                        name = value;
                        RaisePropertyChanged(nameof(Name));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperties_With_NotifyPropertiesChangedFor()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class PersonViewModel : ViewModelBase
            {
                [ObservableProperty]
                [NotifyPropertyChangedFor(nameof(FullName))]
                private string firstName = string.Empty;
            
                [ObservableProperty]
                [NotifyPropertyChangedFor(nameof(FullName), nameof(Age))]
                [NotifyPropertyChangedFor(nameof(Email))]
                [NotifyPropertyChangedFor(nameof(TheProperty))]
                private string? lastName;
            
                [ObservableProperty]
                private int? age;
            
                [ObservableProperty]
                private string? email;
            
                [ObservableProperty("TheProperty", nameof(FullName), nameof(Age))]
                private string? myTestProperty;
            
                public string FullName => $"{FirstName} {LastName}";
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable
            
            namespace TestNamespace;
            
            public partial class PersonViewModel
            {
                public string FirstName
                {
                    get => firstName;
                    set
                    {
                        if (firstName == value)
                        {
                            return;
                        }

                        firstName = value;
                        RaisePropertyChanged(nameof(FirstName));
                        RaisePropertyChanged(nameof(FullName));
                    }
                }

                public string? LastName
                {
                    get => lastName;
                    set
                    {
                        if (lastName == value)
                        {
                            return;
                        }

                        lastName = value;
                        RaisePropertyChanged(nameof(LastName));
                        RaisePropertyChanged(nameof(FullName));
                        RaisePropertyChanged(nameof(Age));
                        RaisePropertyChanged(nameof(Email));
                        RaisePropertyChanged(nameof(TheProperty));
                    }
                }

                public int? Age
                {
                    get => age;
                    set
                    {
                        if (age == value)
                        {
                            return;
                        }

                        age = value;
                        RaisePropertyChanged(nameof(Age));
                    }
                }

                public string? Email
                {
                    get => email;
                    set
                    {
                        if (email == value)
                        {
                            return;
                        }

                        email = value;
                        RaisePropertyChanged(nameof(Email));
                    }
                }

                public string? TheProperty
                {
                    get => myTestProperty;
                    set
                    {
                        if (myTestProperty == value)
                        {
                            return;
                        }

                        myTestProperty = value;
                        RaisePropertyChanged(nameof(TheProperty));
                        RaisePropertyChanged(nameof(FullName));
                        RaisePropertyChanged(nameof(Age));
                    }
                }
            }
            
            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_DependentProperties_NotifyPropertyChangedFor()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(DependentProperties = [nameof(IsReady1), nameof(IsReady2)])]
                [NotifyPropertyChangedFor(nameof(IsReady3), nameof(IsReady4))]
                private IDictionary<string, string> names;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public IDictionary<string, string> Names
                {
                    get => names;
                    set
                    {
                        if (names == value)
                        {
                            return;
                        }
            
                        names = value;
                        RaisePropertyChanged(nameof(Names));
                        RaisePropertyChanged(nameof(IsReady1));
                        RaisePropertyChanged(nameof(IsReady2));
                        RaisePropertyChanged(nameof(IsReady3));
                        RaisePropertyChanged(nameof(IsReady4));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_Name_BeforeChangedCallback()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(BeforeChangedCallback = "DoStuff();")]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }

                        DoStuff();

                        name = value;
                        RaisePropertyChanged(nameof(Name));
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_Name_AfterChangedCallback()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(AfterChangedCallback = "EntrySelected?.Invoke(this, selectedEntry);")]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }
            
                        name = value;
                        RaisePropertyChanged(nameof(Name));

                        EntrySelected?.Invoke(this, selectedEntry);
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_Name_BeforeChangedCallback_AfterChangedCallback()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(BeforeChangedCallback = "DoStuffA();", AfterChangedCallback = "EntrySelected?.Invoke(this, selectedEntry); DoStuffB();")]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }

                        DoStuffA();

                        name = value;
                        RaisePropertyChanged(nameof(Name));

                        EntrySelected?.Invoke(this, selectedEntry);
                        DoStuffB();
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }

    [Fact]
    public void ObservableProperty_Name_BeforeChangedCallback_AfterChangedCallback_nameofMethod()
    {
        const string inputCode =
            """
            namespace TestNamespace;

            public partial class TestViewModel : ViewModelBase
            {
                [ObservableProperty(BeforeChangedCallback = nameof(DoStuffA), AfterChangedCallback = nameof(DoStuffB))]
                private string name;
            }
            """;

        const string expectedCode =
            """
            // <auto-generated>
            #nullable enable

            namespace TestNamespace;

            public partial class TestViewModel
            {
                public string Name
                {
                    get => name;
                    set
                    {
                        if (name == value)
                        {
                            return;
                        }
            
                        DoStuffA();

                        name = value;
                        RaisePropertyChanged(nameof(Name));

                        DoStuffB();
                    }
                }
            }

            #nullable disable
            """;

        var generatorResult = RunGenerator<ViewModelGenerator>(inputCode);

        AssertGeneratorRunResultAsEqual(expectedCode, generatorResult);
    }
}