namespace Atc.Wpf.Tests.UndoRedo;

public sealed class RichUndoCommandTests
{
    [Fact]
    public void Id_AutoGenerated_WhenNull()
    {
        var command = new RichUndoCommand("test", () => { }, () => { });

        command.Id.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void Id_UsesProvided_WhenSpecified()
    {
        var id = Guid.NewGuid();
        var command = new RichUndoCommand("test", () => { }, () => { }, id: id);

        command.Id.Should().Be(id);
    }

    [Fact]
    public void Properties_RoundTrip()
    {
        var id = Guid.NewGuid();
        var image = "icon.png";
        var parameter = 42;
        var data = new { Foo = "bar" };

        var command = new RichUndoCommand(
            "desc",
            () => { },
            () => { },
            id: id,
            image: image,
            parameter: parameter,
            data: data,
            allowUserAction: false);

        command.Description.Should().Be("desc");
        command.Id.Should().Be(id);
        command.Image.Should().Be(image);
        command.Parameter.Should().Be(parameter);
        command.Data.Should().Be(data);
        command.AllowUserAction.Should().BeFalse();
    }

    [Fact]
    public void AllowUserAction_DefaultsToTrue()
    {
        var command = new RichUndoCommand("test", () => { }, () => { });

        command.AllowUserAction.Should().BeTrue();
    }

    [Fact]
    public void Execute_InvokesDelegate()
    {
        var executed = false;
        var command = new RichUndoCommand("test", () => executed = true, () => { });

        command.Execute();

        executed.Should().BeTrue();
    }

    [Fact]
    public void UnExecute_InvokesDelegate()
    {
        var undone = false;
        var command = new RichUndoCommand("test", () => { }, () => undone = true);

        command.UnExecute();

        undone.Should().BeTrue();
    }

    [Fact]
    public void NullDescription_Throws()
    {
        var act = () => new RichUndoCommand(null!, () => { }, () => { });

        act.Should().Throw<ArgumentNullException>();
    }

    [Fact]
    public void NullExecute_Throws()
    {
        var act = () => new RichUndoCommand("test", null!, () => { });

        act.Should().Throw<ArgumentNullException>();
    }

    [Fact]
    public void NullUnExecute_Throws()
    {
        var act = () => new RichUndoCommand("test", () => { }, null!);

        act.Should().Throw<ArgumentNullException>();
    }
}