//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool: Atc.Wpf.Generator.FontIconResources
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Atc.Wpf.FontIcons;

/// <summary>
/// Enumeration: FontAwesomeBrand7Type
/// </summary>
public enum FontAwesomeBrand7Type
{
    /// <summary>
    /// Default None
    /// </summary>
    None = 0x0,

    /// <summary>
    /// AccessibleIcon - 0xf368 - ".fa-accessible-icon"
    /// </summary>
    [Description(".fa-accessible-icon")]
    AccessibleIcon = 0xf368,

    /// <summary>
    /// Accusoft - 0xf369 - ".fa-accusoft"
    /// </summary>
    [Description(".fa-accusoft")]
    Accusoft = 0xf369,

    /// <summary>
    /// Adn - 0xf170 - ".fa-adn"
    /// </summary>
    [Description(".fa-adn")]
    Adn = 0xf170,

    /// <summary>
    /// Adversal - 0xf36a - ".fa-adversal"
    /// </summary>
    [Description(".fa-adversal")]
    Adversal = 0xf36a,

    /// <summary>
    /// Affiliatetheme - 0xf36b - ".fa-affiliatetheme"
    /// </summary>
    [Description(".fa-affiliatetheme")]
    Affiliatetheme = 0xf36b,

    /// <summary>
    /// Airbnb - 0xf834 - ".fa-airbnb"
    /// </summary>
    [Description(".fa-airbnb")]
    Airbnb = 0xf834,

    /// <summary>
    /// Algolia - 0xf36c - ".fa-algolia"
    /// </summary>
    [Description(".fa-algolia")]
    Algolia = 0xf36c,

    /// <summary>
    /// Alipay - 0xf642 - ".fa-alipay"
    /// </summary>
    [Description(".fa-alipay")]
    Alipay = 0xf642,

    /// <summary>
    /// Amazon - 0xf270 - ".fa-amazon"
    /// </summary>
    [Description(".fa-amazon")]
    Amazon = 0xf270,

    /// <summary>
    /// AmazonPay - 0xf42c - ".fa-amazon-pay"
    /// </summary>
    [Description(".fa-amazon-pay")]
    AmazonPay = 0xf42c,

    /// <summary>
    /// Amilia - 0xf36d - ".fa-amilia"
    /// </summary>
    [Description(".fa-amilia")]
    Amilia = 0xf36d,

    /// <summary>
    /// Android - 0xf17b - ".fa-android"
    /// </summary>
    [Description(".fa-android")]
    Android = 0xf17b,

    /// <summary>
    /// Angellist - 0xf209 - ".fa-angellist"
    /// </summary>
    [Description(".fa-angellist")]
    Angellist = 0xf209,

    /// <summary>
    /// Angrycreative - 0xf36e - ".fa-angrycreative"
    /// </summary>
    [Description(".fa-angrycreative")]
    Angrycreative = 0xf36e,

    /// <summary>
    /// Angular - 0xf420 - ".fa-angular"
    /// </summary>
    [Description(".fa-angular")]
    Angular = 0xf420,

    /// <summary>
    /// AppStore - 0xf36f - ".fa-app-store"
    /// </summary>
    [Description(".fa-app-store")]
    AppStore = 0xf36f,

    /// <summary>
    /// AppStoreIos - 0xf370 - ".fa-app-store-ios"
    /// </summary>
    [Description(".fa-app-store-ios")]
    AppStoreIos = 0xf370,

    /// <summary>
    /// Apper - 0xf371 - ".fa-apper"
    /// </summary>
    [Description(".fa-apper")]
    Apper = 0xf371,

    /// <summary>
    /// Apple - 0xf179 - ".fa-apple"
    /// </summary>
    [Description(".fa-apple")]
    Apple = 0xf179,

    /// <summary>
    /// ApplePay - 0xf415 - ".fa-apple-pay"
    /// </summary>
    [Description(".fa-apple-pay")]
    ApplePay = 0xf415,

    /// <summary>
    /// Artstation - 0xf77a - ".fa-artstation"
    /// </summary>
    [Description(".fa-artstation")]
    Artstation = 0xf77a,

    /// <summary>
    /// Asymmetrik - 0xf372 - ".fa-asymmetrik"
    /// </summary>
    [Description(".fa-asymmetrik")]
    Asymmetrik = 0xf372,

    /// <summary>
    /// Atlassian - 0xf77b - ".fa-atlassian"
    /// </summary>
    [Description(".fa-atlassian")]
    Atlassian = 0xf77b,

    /// <summary>
    /// Audible - 0xf373 - ".fa-audible"
    /// </summary>
    [Description(".fa-audible")]
    Audible = 0xf373,

    /// <summary>
    /// Autoprefixer - 0xf41c - ".fa-autoprefixer"
    /// </summary>
    [Description(".fa-autoprefixer")]
    Autoprefixer = 0xf41c,

    /// <summary>
    /// Avianex - 0xf374 - ".fa-avianex"
    /// </summary>
    [Description(".fa-avianex")]
    Avianex = 0xf374,

    /// <summary>
    /// Aviato - 0xf421 - ".fa-aviato"
    /// </summary>
    [Description(".fa-aviato")]
    Aviato = 0xf421,

    /// <summary>
    /// Aws - 0xf375 - ".fa-aws"
    /// </summary>
    [Description(".fa-aws")]
    Aws = 0xf375,

    /// <summary>
    /// Bandcamp - 0xf2d5 - ".fa-bandcamp"
    /// </summary>
    [Description(".fa-bandcamp")]
    Bandcamp = 0xf2d5,

    /// <summary>
    /// BattleNet - 0xf835 - ".fa-battle-net"
    /// </summary>
    [Description(".fa-battle-net")]
    BattleNet = 0xf835,

    /// <summary>
    /// Behance - 0xf1b4 - ".fa-behance"
    /// </summary>
    [Description(".fa-behance")]
    Behance = 0xf1b4,

    /// <summary>
    /// BehanceSquare - 0xf1b5 - ".fa-behance-square"
    /// </summary>
    [Description(".fa-behance-square")]
    BehanceSquare = 0xf1b5,

    /// <summary>
    /// Bilibili - 0xe3d9 - ".fa-bilibili"
    /// </summary>
    [Description(".fa-bilibili")]
    Bilibili = 0xe3d9,

    /// <summary>
    /// Bimobject - 0xf378 - ".fa-bimobject"
    /// </summary>
    [Description(".fa-bimobject")]
    Bimobject = 0xf378,

    /// <summary>
    /// Bitbucket - 0xf171 - ".fa-bitbucket"
    /// </summary>
    [Description(".fa-bitbucket")]
    Bitbucket = 0xf171,

    /// <summary>
    /// Bitcoin - 0xf379 - ".fa-bitcoin"
    /// </summary>
    [Description(".fa-bitcoin")]
    Bitcoin = 0xf379,

    /// <summary>
    /// Bity - 0xf37a - ".fa-bity"
    /// </summary>
    [Description(".fa-bity")]
    Bity = 0xf37a,

    /// <summary>
    /// BlackTie - 0xf27e - ".fa-black-tie"
    /// </summary>
    [Description(".fa-black-tie")]
    BlackTie = 0xf27e,

    /// <summary>
    /// Blackberry - 0xf37b - ".fa-blackberry"
    /// </summary>
    [Description(".fa-blackberry")]
    Blackberry = 0xf37b,

    /// <summary>
    /// Blogger - 0xf37c - ".fa-blogger"
    /// </summary>
    [Description(".fa-blogger")]
    Blogger = 0xf37c,

    /// <summary>
    /// BloggerB - 0xf37d - ".fa-blogger-b"
    /// </summary>
    [Description(".fa-blogger-b")]
    BloggerB = 0xf37d,

    /// <summary>
    /// Bluesky - 0xe671 - ".fa-bluesky"
    /// </summary>
    [Description(".fa-bluesky")]
    Bluesky = 0xe671,

    /// <summary>
    /// Bluetooth - 0xf293 - ".fa-bluetooth"
    /// </summary>
    [Description(".fa-bluetooth")]
    Bluetooth = 0xf293,

    /// <summary>
    /// BluetoothB - 0xf294 - ".fa-bluetooth-b"
    /// </summary>
    [Description(".fa-bluetooth-b")]
    BluetoothB = 0xf294,

    /// <summary>
    /// Bootstrap - 0xf836 - ".fa-bootstrap"
    /// </summary>
    [Description(".fa-bootstrap")]
    Bootstrap = 0xf836,

    /// <summary>
    /// Bots - 0xe340 - ".fa-bots"
    /// </summary>
    [Description(".fa-bots")]
    Bots = 0xe340,

    /// <summary>
    /// Brave - 0xe63c - ".fa-brave"
    /// </summary>
    [Description(".fa-brave")]
    Brave = 0xe63c,

    /// <summary>
    /// BraveReverse - 0xe63d - ".fa-brave-reverse"
    /// </summary>
    [Description(".fa-brave-reverse")]
    BraveReverse = 0xe63d,

    /// <summary>
    /// Btc - 0xf15a - ".fa-btc"
    /// </summary>
    [Description(".fa-btc")]
    Btc = 0xf15a,

    /// <summary>
    /// Buffer - 0xf837 - ".fa-buffer"
    /// </summary>
    [Description(".fa-buffer")]
    Buffer = 0xf837,

    /// <summary>
    /// Buromobelexperte - 0xf37f - ".fa-buromobelexperte"
    /// </summary>
    [Description(".fa-buromobelexperte")]
    Buromobelexperte = 0xf37f,

    /// <summary>
    /// BuyNLarge - 0xf8a6 - ".fa-buy-n-large"
    /// </summary>
    [Description(".fa-buy-n-large")]
    BuyNLarge = 0xf8a6,

    /// <summary>
    /// Buysellads - 0xf20d - ".fa-buysellads"
    /// </summary>
    [Description(".fa-buysellads")]
    Buysellads = 0xf20d,

    /// <summary>
    /// CanadianMapleLeaf - 0xf785 - ".fa-canadian-maple-leaf"
    /// </summary>
    [Description(".fa-canadian-maple-leaf")]
    CanadianMapleLeaf = 0xf785,

    /// <summary>
    /// CashApp - 0xe7d4 - ".fa-cash-app"
    /// </summary>
    [Description(".fa-cash-app")]
    CashApp = 0xe7d4,

    /// <summary>
    /// CcAmazonPay - 0xf42d - ".fa-cc-amazon-pay"
    /// </summary>
    [Description(".fa-cc-amazon-pay")]
    CcAmazonPay = 0xf42d,

    /// <summary>
    /// CcAmex - 0xf1f3 - ".fa-cc-amex"
    /// </summary>
    [Description(".fa-cc-amex")]
    CcAmex = 0xf1f3,

    /// <summary>
    /// CcApplePay - 0xf416 - ".fa-cc-apple-pay"
    /// </summary>
    [Description(".fa-cc-apple-pay")]
    CcApplePay = 0xf416,

    /// <summary>
    /// CcDinersClub - 0xf24c - ".fa-cc-diners-club"
    /// </summary>
    [Description(".fa-cc-diners-club")]
    CcDinersClub = 0xf24c,

    /// <summary>
    /// CcDiscover - 0xf1f2 - ".fa-cc-discover"
    /// </summary>
    [Description(".fa-cc-discover")]
    CcDiscover = 0xf1f2,

    /// <summary>
    /// CcJcb - 0xf24b - ".fa-cc-jcb"
    /// </summary>
    [Description(".fa-cc-jcb")]
    CcJcb = 0xf24b,

    /// <summary>
    /// CcMastercard - 0xf1f1 - ".fa-cc-mastercard"
    /// </summary>
    [Description(".fa-cc-mastercard")]
    CcMastercard = 0xf1f1,

    /// <summary>
    /// CcPaypal - 0xf1f4 - ".fa-cc-paypal"
    /// </summary>
    [Description(".fa-cc-paypal")]
    CcPaypal = 0xf1f4,

    /// <summary>
    /// CcStripe - 0xf1f5 - ".fa-cc-stripe"
    /// </summary>
    [Description(".fa-cc-stripe")]
    CcStripe = 0xf1f5,

    /// <summary>
    /// CcVisa - 0xf1f0 - ".fa-cc-visa"
    /// </summary>
    [Description(".fa-cc-visa")]
    CcVisa = 0xf1f0,

    /// <summary>
    /// Centercode - 0xf380 - ".fa-centercode"
    /// </summary>
    [Description(".fa-centercode")]
    Centercode = 0xf380,

    /// <summary>
    /// Centos - 0xf789 - ".fa-centos"
    /// </summary>
    [Description(".fa-centos")]
    Centos = 0xf789,

    /// <summary>
    /// Chrome - 0xf268 - ".fa-chrome"
    /// </summary>
    [Description(".fa-chrome")]
    Chrome = 0xf268,

    /// <summary>
    /// Chromecast - 0xf838 - ".fa-chromecast"
    /// </summary>
    [Description(".fa-chromecast")]
    Chromecast = 0xf838,

    /// <summary>
    /// Cloudflare - 0xe07d - ".fa-cloudflare"
    /// </summary>
    [Description(".fa-cloudflare")]
    Cloudflare = 0xe07d,

    /// <summary>
    /// Cloudscale - 0xf383 - ".fa-cloudscale"
    /// </summary>
    [Description(".fa-cloudscale")]
    Cloudscale = 0xf383,

    /// <summary>
    /// Cloudsmith - 0xf384 - ".fa-cloudsmith"
    /// </summary>
    [Description(".fa-cloudsmith")]
    Cloudsmith = 0xf384,

    /// <summary>
    /// Cloudversify - 0xf385 - ".fa-cloudversify"
    /// </summary>
    [Description(".fa-cloudversify")]
    Cloudversify = 0xf385,

    /// <summary>
    /// Cmplid - 0xe360 - ".fa-cmplid"
    /// </summary>
    [Description(".fa-cmplid")]
    Cmplid = 0xe360,

    /// <summary>
    /// Codepen - 0xf1cb - ".fa-codepen"
    /// </summary>
    [Description(".fa-codepen")]
    Codepen = 0xf1cb,

    /// <summary>
    /// Codiepie - 0xf284 - ".fa-codiepie"
    /// </summary>
    [Description(".fa-codiepie")]
    Codiepie = 0xf284,

    /// <summary>
    /// Confluence - 0xf78d - ".fa-confluence"
    /// </summary>
    [Description(".fa-confluence")]
    Confluence = 0xf78d,

    /// <summary>
    /// Connectdevelop - 0xf20e - ".fa-connectdevelop"
    /// </summary>
    [Description(".fa-connectdevelop")]
    Connectdevelop = 0xf20e,

    /// <summary>
    /// Contao - 0xf26d - ".fa-contao"
    /// </summary>
    [Description(".fa-contao")]
    Contao = 0xf26d,

    /// <summary>
    /// CottonBureau - 0xf89e - ".fa-cotton-bureau"
    /// </summary>
    [Description(".fa-cotton-bureau")]
    CottonBureau = 0xf89e,

    /// <summary>
    /// Cpanel - 0xf388 - ".fa-cpanel"
    /// </summary>
    [Description(".fa-cpanel")]
    Cpanel = 0xf388,

    /// <summary>
    /// CreativeCommons - 0xf25e - ".fa-creative-commons"
    /// </summary>
    [Description(".fa-creative-commons")]
    CreativeCommons = 0xf25e,

    /// <summary>
    /// CreativeCommonsBy - 0xf4e7 - ".fa-creative-commons-by"
    /// </summary>
    [Description(".fa-creative-commons-by")]
    CreativeCommonsBy = 0xf4e7,

    /// <summary>
    /// CreativeCommonsNc - 0xf4e8 - ".fa-creative-commons-nc"
    /// </summary>
    [Description(".fa-creative-commons-nc")]
    CreativeCommonsNc = 0xf4e8,

    /// <summary>
    /// CreativeCommonsNcEu - 0xf4e9 - ".fa-creative-commons-nc-eu"
    /// </summary>
    [Description(".fa-creative-commons-nc-eu")]
    CreativeCommonsNcEu = 0xf4e9,

    /// <summary>
    /// CreativeCommonsNcJp - 0xf4ea - ".fa-creative-commons-nc-jp"
    /// </summary>
    [Description(".fa-creative-commons-nc-jp")]
    CreativeCommonsNcJp = 0xf4ea,

    /// <summary>
    /// CreativeCommonsNd - 0xf4eb - ".fa-creative-commons-nd"
    /// </summary>
    [Description(".fa-creative-commons-nd")]
    CreativeCommonsNd = 0xf4eb,

    /// <summary>
    /// CreativeCommonsPd - 0xf4ec - ".fa-creative-commons-pd"
    /// </summary>
    [Description(".fa-creative-commons-pd")]
    CreativeCommonsPd = 0xf4ec,

    /// <summary>
    /// CreativeCommonsPdAlt - 0xf4ed - ".fa-creative-commons-pd-alt"
    /// </summary>
    [Description(".fa-creative-commons-pd-alt")]
    CreativeCommonsPdAlt = 0xf4ed,

    /// <summary>
    /// CreativeCommonsRemix - 0xf4ee - ".fa-creative-commons-remix"
    /// </summary>
    [Description(".fa-creative-commons-remix")]
    CreativeCommonsRemix = 0xf4ee,

    /// <summary>
    /// CreativeCommonsSa - 0xf4ef - ".fa-creative-commons-sa"
    /// </summary>
    [Description(".fa-creative-commons-sa")]
    CreativeCommonsSa = 0xf4ef,

    /// <summary>
    /// CreativeCommonsSampling - 0xf4f0 - ".fa-creative-commons-sampling"
    /// </summary>
    [Description(".fa-creative-commons-sampling")]
    CreativeCommonsSampling = 0xf4f0,

    /// <summary>
    /// CreativeCommonsSamplingPlus - 0xf4f1 - ".fa-creative-commons-sampling-plus"
    /// </summary>
    [Description(".fa-creative-commons-sampling-plus")]
    CreativeCommonsSamplingPlus = 0xf4f1,

    /// <summary>
    /// CreativeCommonsShare - 0xf4f2 - ".fa-creative-commons-share"
    /// </summary>
    [Description(".fa-creative-commons-share")]
    CreativeCommonsShare = 0xf4f2,

    /// <summary>
    /// CreativeCommonsZero - 0xf4f3 - ".fa-creative-commons-zero"
    /// </summary>
    [Description(".fa-creative-commons-zero")]
    CreativeCommonsZero = 0xf4f3,

    /// <summary>
    /// CriticalRole - 0xf6c9 - ".fa-critical-role"
    /// </summary>
    [Description(".fa-critical-role")]
    CriticalRole = 0xf6c9,

    /// <summary>
    /// Css - 0xe6a2 - ".fa-css"
    /// </summary>
    [Description(".fa-css")]
    Css = 0xe6a2,

    /// <summary>
    /// Css3 - 0xf13c - ".fa-css3"
    /// </summary>
    [Description(".fa-css3")]
    Css3 = 0xf13c,

    /// <summary>
    /// Css3Alt - 0xf38b - ".fa-css3-alt"
    /// </summary>
    [Description(".fa-css3-alt")]
    Css3Alt = 0xf38b,

    /// <summary>
    /// Cuttlefish - 0xf38c - ".fa-cuttlefish"
    /// </summary>
    [Description(".fa-cuttlefish")]
    Cuttlefish = 0xf38c,

    /// <summary>
    /// DAndD - 0xf38d - ".fa-d-and-d"
    /// </summary>
    [Description(".fa-d-and-d")]
    // ReSharper disable InconsistentNaming
    DAndD = 0xf38d,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// DAndDBeyond - 0xf6ca - ".fa-d-and-d-beyond"
    /// </summary>
    [Description(".fa-d-and-d-beyond")]
    // ReSharper disable InconsistentNaming
    DAndDBeyond = 0xf6ca,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// Dailymotion - 0xe052 - ".fa-dailymotion"
    /// </summary>
    [Description(".fa-dailymotion")]
    Dailymotion = 0xe052,

    /// <summary>
    /// DartLang - 0xe693 - ".fa-dart-lang"
    /// </summary>
    [Description(".fa-dart-lang")]
    DartLang = 0xe693,

    /// <summary>
    /// Dashcube - 0xf210 - ".fa-dashcube"
    /// </summary>
    [Description(".fa-dashcube")]
    Dashcube = 0xf210,

    /// <summary>
    /// Debian - 0xe60b - ".fa-debian"
    /// </summary>
    [Description(".fa-debian")]
    Debian = 0xe60b,

    /// <summary>
    /// Deezer - 0xe077 - ".fa-deezer"
    /// </summary>
    [Description(".fa-deezer")]
    Deezer = 0xe077,

    /// <summary>
    /// Delicious - 0xf1a5 - ".fa-delicious"
    /// </summary>
    [Description(".fa-delicious")]
    Delicious = 0xf1a5,

    /// <summary>
    /// Deploydog - 0xf38e - ".fa-deploydog"
    /// </summary>
    [Description(".fa-deploydog")]
    Deploydog = 0xf38e,

    /// <summary>
    /// Deskpro - 0xf38f - ".fa-deskpro"
    /// </summary>
    [Description(".fa-deskpro")]
    Deskpro = 0xf38f,

    /// <summary>
    /// Dev - 0xf6cc - ".fa-dev"
    /// </summary>
    [Description(".fa-dev")]
    Dev = 0xf6cc,

    /// <summary>
    /// Deviantart - 0xf1bd - ".fa-deviantart"
    /// </summary>
    [Description(".fa-deviantart")]
    Deviantart = 0xf1bd,

    /// <summary>
    /// Dhl - 0xf790 - ".fa-dhl"
    /// </summary>
    [Description(".fa-dhl")]
    Dhl = 0xf790,

    /// <summary>
    /// Diaspora - 0xf791 - ".fa-diaspora"
    /// </summary>
    [Description(".fa-diaspora")]
    Diaspora = 0xf791,

    /// <summary>
    /// Digg - 0xf1a6 - ".fa-digg"
    /// </summary>
    [Description(".fa-digg")]
    Digg = 0xf1a6,

    /// <summary>
    /// DigitalOcean - 0xf391 - ".fa-digital-ocean"
    /// </summary>
    [Description(".fa-digital-ocean")]
    DigitalOcean = 0xf391,

    /// <summary>
    /// Discord - 0xf392 - ".fa-discord"
    /// </summary>
    [Description(".fa-discord")]
    Discord = 0xf392,

    /// <summary>
    /// Discourse - 0xf393 - ".fa-discourse"
    /// </summary>
    [Description(".fa-discourse")]
    Discourse = 0xf393,

    /// <summary>
    /// Disqus - 0xe7d5 - ".fa-disqus"
    /// </summary>
    [Description(".fa-disqus")]
    Disqus = 0xe7d5,

    /// <summary>
    /// Dochub - 0xf394 - ".fa-dochub"
    /// </summary>
    [Description(".fa-dochub")]
    Dochub = 0xf394,

    /// <summary>
    /// Docker - 0xf395 - ".fa-docker"
    /// </summary>
    [Description(".fa-docker")]
    Docker = 0xf395,

    /// <summary>
    /// Draft2digital - 0xf396 - ".fa-draft2digital"
    /// </summary>
    [Description(".fa-draft2digital")]
    Draft2digital = 0xf396,

    /// <summary>
    /// Dribbble - 0xf17d - ".fa-dribbble"
    /// </summary>
    [Description(".fa-dribbble")]
    Dribbble = 0xf17d,

    /// <summary>
    /// DribbbleSquare - 0xf397 - ".fa-dribbble-square"
    /// </summary>
    [Description(".fa-dribbble-square")]
    DribbbleSquare = 0xf397,

    /// <summary>
    /// Dropbox - 0xf16b - ".fa-dropbox"
    /// </summary>
    [Description(".fa-dropbox")]
    Dropbox = 0xf16b,

    /// <summary>
    /// Drupal - 0xf1a9 - ".fa-drupal"
    /// </summary>
    [Description(".fa-drupal")]
    Drupal = 0xf1a9,

    /// <summary>
    /// Duolingo - 0xe812 - ".fa-duolingo"
    /// </summary>
    [Description(".fa-duolingo")]
    Duolingo = 0xe812,

    /// <summary>
    /// Dyalog - 0xf399 - ".fa-dyalog"
    /// </summary>
    [Description(".fa-dyalog")]
    Dyalog = 0xf399,

    /// <summary>
    /// Earlybirds - 0xf39a - ".fa-earlybirds"
    /// </summary>
    [Description(".fa-earlybirds")]
    Earlybirds = 0xf39a,

    /// <summary>
    /// Ebay - 0xf4f4 - ".fa-ebay"
    /// </summary>
    [Description(".fa-ebay")]
    Ebay = 0xf4f4,

    /// <summary>
    /// Edge - 0xf282 - ".fa-edge"
    /// </summary>
    [Description(".fa-edge")]
    Edge = 0xf282,

    /// <summary>
    /// EdgeLegacy - 0xe078 - ".fa-edge-legacy"
    /// </summary>
    [Description(".fa-edge-legacy")]
    EdgeLegacy = 0xe078,

    /// <summary>
    /// Elementor - 0xf430 - ".fa-elementor"
    /// </summary>
    [Description(".fa-elementor")]
    Elementor = 0xf430,

    /// <summary>
    /// Eleventy - 0xe7d6 - ".fa-eleventy"
    /// </summary>
    [Description(".fa-eleventy")]
    Eleventy = 0xe7d6,

    /// <summary>
    /// Ello - 0xf5f1 - ".fa-ello"
    /// </summary>
    [Description(".fa-ello")]
    Ello = 0xf5f1,

    /// <summary>
    /// Ember - 0xf423 - ".fa-ember"
    /// </summary>
    [Description(".fa-ember")]
    Ember = 0xf423,

    /// <summary>
    /// Empire - 0xf1d1 - ".fa-empire"
    /// </summary>
    [Description(".fa-empire")]
    Empire = 0xf1d1,

    /// <summary>
    /// Envira - 0xf299 - ".fa-envira"
    /// </summary>
    [Description(".fa-envira")]
    Envira = 0xf299,

    /// <summary>
    /// Erlang - 0xf39d - ".fa-erlang"
    /// </summary>
    [Description(".fa-erlang")]
    Erlang = 0xf39d,

    /// <summary>
    /// Ethereum - 0xf42e - ".fa-ethereum"
    /// </summary>
    [Description(".fa-ethereum")]
    Ethereum = 0xf42e,

    /// <summary>
    /// Etsy - 0xf2d7 - ".fa-etsy"
    /// </summary>
    [Description(".fa-etsy")]
    Etsy = 0xf2d7,

    /// <summary>
    /// Evernote - 0xf839 - ".fa-evernote"
    /// </summary>
    [Description(".fa-evernote")]
    Evernote = 0xf839,

    /// <summary>
    /// Expeditedssl - 0xf23e - ".fa-expeditedssl"
    /// </summary>
    [Description(".fa-expeditedssl")]
    Expeditedssl = 0xf23e,

    /// <summary>
    /// Facebook - 0xf09a - ".fa-facebook"
    /// </summary>
    [Description(".fa-facebook")]
    Facebook = 0xf09a,

    /// <summary>
    /// FacebookF - 0xf39e - ".fa-facebook-f"
    /// </summary>
    [Description(".fa-facebook-f")]
    FacebookF = 0xf39e,

    /// <summary>
    /// FacebookMessenger - 0xf39f - ".fa-facebook-messenger"
    /// </summary>
    [Description(".fa-facebook-messenger")]
    FacebookMessenger = 0xf39f,

    /// <summary>
    /// FacebookSquare - 0xf082 - ".fa-facebook-square"
    /// </summary>
    [Description(".fa-facebook-square")]
    FacebookSquare = 0xf082,

    /// <summary>
    /// FantasyFlightGames - 0xf6dc - ".fa-fantasy-flight-games"
    /// </summary>
    [Description(".fa-fantasy-flight-games")]
    FantasyFlightGames = 0xf6dc,

    /// <summary>
    /// Fedex - 0xf797 - ".fa-fedex"
    /// </summary>
    [Description(".fa-fedex")]
    Fedex = 0xf797,

    /// <summary>
    /// Fedora - 0xf798 - ".fa-fedora"
    /// </summary>
    [Description(".fa-fedora")]
    Fedora = 0xf798,

    /// <summary>
    /// Figma - 0xf799 - ".fa-figma"
    /// </summary>
    [Description(".fa-figma")]
    Figma = 0xf799,

    /// <summary>
    /// FilesPinwheel - 0xe69f - ".fa-files-pinwheel"
    /// </summary>
    [Description(".fa-files-pinwheel")]
    FilesPinwheel = 0xe69f,

    /// <summary>
    /// Firefox - 0xf269 - ".fa-firefox"
    /// </summary>
    [Description(".fa-firefox")]
    Firefox = 0xf269,

    /// <summary>
    /// FirefoxBrowser - 0xe007 - ".fa-firefox-browser"
    /// </summary>
    [Description(".fa-firefox-browser")]
    FirefoxBrowser = 0xe007,

    /// <summary>
    /// FirstOrder - 0xf2b0 - ".fa-first-order"
    /// </summary>
    [Description(".fa-first-order")]
    FirstOrder = 0xf2b0,

    /// <summary>
    /// FirstOrderAlt - 0xf50a - ".fa-first-order-alt"
    /// </summary>
    [Description(".fa-first-order-alt")]
    FirstOrderAlt = 0xf50a,

    /// <summary>
    /// Firstdraft - 0xf3a1 - ".fa-firstdraft"
    /// </summary>
    [Description(".fa-firstdraft")]
    Firstdraft = 0xf3a1,

    /// <summary>
    /// Flickr - 0xf16e - ".fa-flickr"
    /// </summary>
    [Description(".fa-flickr")]
    Flickr = 0xf16e,

    /// <summary>
    /// Flipboard - 0xf44d - ".fa-flipboard"
    /// </summary>
    [Description(".fa-flipboard")]
    Flipboard = 0xf44d,

    /// <summary>
    /// Flutter - 0xe694 - ".fa-flutter"
    /// </summary>
    [Description(".fa-flutter")]
    Flutter = 0xe694,

    /// <summary>
    /// Fly - 0xf417 - ".fa-fly"
    /// </summary>
    [Description(".fa-fly")]
    Fly = 0xf417,

    /// <summary>
    /// FontAwesome - 0xf2b4 - ".fa-font-awesome"
    /// </summary>
    [Description(".fa-font-awesome")]
    FontAwesome = 0xf2b4,

    /// <summary>
    /// FontAwesomeAlt - 0xf35c - ".fa-font-awesome-alt"
    /// </summary>
    [Description(".fa-font-awesome-alt")]
    FontAwesomeAlt = 0xf35c,

    /// <summary>
    /// FontAwesomeFlag - 0xf2b4 - ".fa-font-awesome-flag"
    /// </summary>
    [Description(".fa-font-awesome-flag")]
    FontAwesomeFlag = 0xf2b4,

    /// <summary>
    /// FontAwesomeLogoFull - 0xf2b4 - ".fa-font-awesome-logo-full"
    /// </summary>
    [Description(".fa-font-awesome-logo-full")]
    FontAwesomeLogoFull = 0xf2b4,

    /// <summary>
    /// Fonticons - 0xf280 - ".fa-fonticons"
    /// </summary>
    [Description(".fa-fonticons")]
    Fonticons = 0xf280,

    /// <summary>
    /// FonticonsFi - 0xf3a2 - ".fa-fonticons-fi"
    /// </summary>
    [Description(".fa-fonticons-fi")]
    FonticonsFi = 0xf3a2,

    /// <summary>
    /// FortAwesome - 0xf286 - ".fa-fort-awesome"
    /// </summary>
    [Description(".fa-fort-awesome")]
    FortAwesome = 0xf286,

    /// <summary>
    /// FortAwesomeAlt - 0xf3a3 - ".fa-fort-awesome-alt"
    /// </summary>
    [Description(".fa-fort-awesome-alt")]
    FortAwesomeAlt = 0xf3a3,

    /// <summary>
    /// Forumbee - 0xf211 - ".fa-forumbee"
    /// </summary>
    [Description(".fa-forumbee")]
    Forumbee = 0xf211,

    /// <summary>
    /// Foursquare - 0xf180 - ".fa-foursquare"
    /// </summary>
    [Description(".fa-foursquare")]
    Foursquare = 0xf180,

    /// <summary>
    /// FreeCodeCamp - 0xf2c5 - ".fa-free-code-camp"
    /// </summary>
    [Description(".fa-free-code-camp")]
    FreeCodeCamp = 0xf2c5,

    /// <summary>
    /// Freebsd - 0xf3a4 - ".fa-freebsd"
    /// </summary>
    [Description(".fa-freebsd")]
    Freebsd = 0xf3a4,

    /// <summary>
    /// Fulcrum - 0xf50b - ".fa-fulcrum"
    /// </summary>
    [Description(".fa-fulcrum")]
    Fulcrum = 0xf50b,

    /// <summary>
    /// GalacticRepublic - 0xf50c - ".fa-galactic-republic"
    /// </summary>
    [Description(".fa-galactic-republic")]
    GalacticRepublic = 0xf50c,

    /// <summary>
    /// GalacticSenate - 0xf50d - ".fa-galactic-senate"
    /// </summary>
    [Description(".fa-galactic-senate")]
    GalacticSenate = 0xf50d,

    /// <summary>
    /// GetPocket - 0xf265 - ".fa-get-pocket"
    /// </summary>
    [Description(".fa-get-pocket")]
    GetPocket = 0xf265,

    /// <summary>
    /// Gg - 0xf260 - ".fa-gg"
    /// </summary>
    [Description(".fa-gg")]
    Gg = 0xf260,

    /// <summary>
    /// GgCircle - 0xf261 - ".fa-gg-circle"
    /// </summary>
    [Description(".fa-gg-circle")]
    GgCircle = 0xf261,

    /// <summary>
    /// Git - 0xf1d3 - ".fa-git"
    /// </summary>
    [Description(".fa-git")]
    Git = 0xf1d3,

    /// <summary>
    /// GitAlt - 0xf841 - ".fa-git-alt"
    /// </summary>
    [Description(".fa-git-alt")]
    GitAlt = 0xf841,

    /// <summary>
    /// GitSquare - 0xf1d2 - ".fa-git-square"
    /// </summary>
    [Description(".fa-git-square")]
    GitSquare = 0xf1d2,

    /// <summary>
    /// Github - 0xf09b - ".fa-github"
    /// </summary>
    [Description(".fa-github")]
    Github = 0xf09b,

    /// <summary>
    /// GithubAlt - 0xf113 - ".fa-github-alt"
    /// </summary>
    [Description(".fa-github-alt")]
    GithubAlt = 0xf113,

    /// <summary>
    /// GithubSquare - 0xf092 - ".fa-github-square"
    /// </summary>
    [Description(".fa-github-square")]
    GithubSquare = 0xf092,

    /// <summary>
    /// Gitkraken - 0xf3a6 - ".fa-gitkraken"
    /// </summary>
    [Description(".fa-gitkraken")]
    Gitkraken = 0xf3a6,

    /// <summary>
    /// Gitlab - 0xf296 - ".fa-gitlab"
    /// </summary>
    [Description(".fa-gitlab")]
    Gitlab = 0xf296,

    /// <summary>
    /// GitlabSquare - 0xe5ae - ".fa-gitlab-square"
    /// </summary>
    [Description(".fa-gitlab-square")]
    GitlabSquare = 0xe5ae,

    /// <summary>
    /// Gitter - 0xf426 - ".fa-gitter"
    /// </summary>
    [Description(".fa-gitter")]
    Gitter = 0xf426,

    /// <summary>
    /// Glide - 0xf2a5 - ".fa-glide"
    /// </summary>
    [Description(".fa-glide")]
    Glide = 0xf2a5,

    /// <summary>
    /// GlideG - 0xf2a6 - ".fa-glide-g"
    /// </summary>
    [Description(".fa-glide-g")]
    GlideG = 0xf2a6,

    /// <summary>
    /// Gofore - 0xf3a7 - ".fa-gofore"
    /// </summary>
    [Description(".fa-gofore")]
    Gofore = 0xf3a7,

    /// <summary>
    /// Golang - 0xe40f - ".fa-golang"
    /// </summary>
    [Description(".fa-golang")]
    Golang = 0xe40f,

    /// <summary>
    /// Goodreads - 0xf3a8 - ".fa-goodreads"
    /// </summary>
    [Description(".fa-goodreads")]
    Goodreads = 0xf3a8,

    /// <summary>
    /// GoodreadsG - 0xf3a9 - ".fa-goodreads-g"
    /// </summary>
    [Description(".fa-goodreads-g")]
    GoodreadsG = 0xf3a9,

    /// <summary>
    /// Google - 0xf1a0 - ".fa-google"
    /// </summary>
    [Description(".fa-google")]
    Google = 0xf1a0,

    /// <summary>
    /// GoogleDrive - 0xf3aa - ".fa-google-drive"
    /// </summary>
    [Description(".fa-google-drive")]
    GoogleDrive = 0xf3aa,

    /// <summary>
    /// GooglePay - 0xe079 - ".fa-google-pay"
    /// </summary>
    [Description(".fa-google-pay")]
    GooglePay = 0xe079,

    /// <summary>
    /// GooglePlay - 0xf3ab - ".fa-google-play"
    /// </summary>
    [Description(".fa-google-play")]
    GooglePlay = 0xf3ab,

    /// <summary>
    /// GooglePlus - 0xf2b3 - ".fa-google-plus"
    /// </summary>
    [Description(".fa-google-plus")]
    GooglePlus = 0xf2b3,

    /// <summary>
    /// GooglePlusG - 0xf0d5 - ".fa-google-plus-g"
    /// </summary>
    [Description(".fa-google-plus-g")]
    GooglePlusG = 0xf0d5,

    /// <summary>
    /// GooglePlusSquare - 0xf0d4 - ".fa-google-plus-square"
    /// </summary>
    [Description(".fa-google-plus-square")]
    GooglePlusSquare = 0xf0d4,

    /// <summary>
    /// GoogleScholar - 0xe63b - ".fa-google-scholar"
    /// </summary>
    [Description(".fa-google-scholar")]
    GoogleScholar = 0xe63b,

    /// <summary>
    /// GoogleWallet - 0xf1ee - ".fa-google-wallet"
    /// </summary>
    [Description(".fa-google-wallet")]
    GoogleWallet = 0xf1ee,

    /// <summary>
    /// Gratipay - 0xf184 - ".fa-gratipay"
    /// </summary>
    [Description(".fa-gratipay")]
    Gratipay = 0xf184,

    /// <summary>
    /// Grav - 0xf2d6 - ".fa-grav"
    /// </summary>
    [Description(".fa-grav")]
    Grav = 0xf2d6,

    /// <summary>
    /// Gripfire - 0xf3ac - ".fa-gripfire"
    /// </summary>
    [Description(".fa-gripfire")]
    Gripfire = 0xf3ac,

    /// <summary>
    /// Grunt - 0xf3ad - ".fa-grunt"
    /// </summary>
    [Description(".fa-grunt")]
    Grunt = 0xf3ad,

    /// <summary>
    /// Guilded - 0xe07e - ".fa-guilded"
    /// </summary>
    [Description(".fa-guilded")]
    Guilded = 0xe07e,

    /// <summary>
    /// Gulp - 0xf3ae - ".fa-gulp"
    /// </summary>
    [Description(".fa-gulp")]
    Gulp = 0xf3ae,

    /// <summary>
    /// HackerNews - 0xf1d4 - ".fa-hacker-news"
    /// </summary>
    [Description(".fa-hacker-news")]
    HackerNews = 0xf1d4,

    /// <summary>
    /// HackerNewsSquare - 0xf3af - ".fa-hacker-news-square"
    /// </summary>
    [Description(".fa-hacker-news-square")]
    HackerNewsSquare = 0xf3af,

    /// <summary>
    /// Hackerrank - 0xf5f7 - ".fa-hackerrank"
    /// </summary>
    [Description(".fa-hackerrank")]
    Hackerrank = 0xf5f7,

    /// <summary>
    /// Hashnode - 0xe499 - ".fa-hashnode"
    /// </summary>
    [Description(".fa-hashnode")]
    Hashnode = 0xe499,

    /// <summary>
    /// Hips - 0xf452 - ".fa-hips"
    /// </summary>
    [Description(".fa-hips")]
    Hips = 0xf452,

    /// <summary>
    /// HireAHelper - 0xf3b0 - ".fa-hire-a-helper"
    /// </summary>
    [Description(".fa-hire-a-helper")]
    HireAHelper = 0xf3b0,

    /// <summary>
    /// Hive - 0xe07f - ".fa-hive"
    /// </summary>
    [Description(".fa-hive")]
    Hive = 0xe07f,

    /// <summary>
    /// Hooli - 0xf427 - ".fa-hooli"
    /// </summary>
    [Description(".fa-hooli")]
    Hooli = 0xf427,

    /// <summary>
    /// Hornbill - 0xf592 - ".fa-hornbill"
    /// </summary>
    [Description(".fa-hornbill")]
    Hornbill = 0xf592,

    /// <summary>
    /// Hotjar - 0xf3b1 - ".fa-hotjar"
    /// </summary>
    [Description(".fa-hotjar")]
    Hotjar = 0xf3b1,

    /// <summary>
    /// Houzz - 0xf27c - ".fa-houzz"
    /// </summary>
    [Description(".fa-houzz")]
    Houzz = 0xf27c,

    /// <summary>
    /// Html5 - 0xf13b - ".fa-html5"
    /// </summary>
    [Description(".fa-html5")]
    Html5 = 0xf13b,

    /// <summary>
    /// Hubspot - 0xf3b2 - ".fa-hubspot"
    /// </summary>
    [Description(".fa-hubspot")]
    Hubspot = 0xf3b2,

    /// <summary>
    /// Ideal - 0xe013 - ".fa-ideal"
    /// </summary>
    [Description(".fa-ideal")]
    Ideal = 0xe013,

    /// <summary>
    /// Imdb - 0xf2d8 - ".fa-imdb"
    /// </summary>
    [Description(".fa-imdb")]
    Imdb = 0xf2d8,

    /// <summary>
    /// Innosoft - 0xe080 - ".fa-innosoft"
    /// </summary>
    [Description(".fa-innosoft")]
    Innosoft = 0xe080,

    /// <summary>
    /// Instagram - 0xf16d - ".fa-instagram"
    /// </summary>
    [Description(".fa-instagram")]
    Instagram = 0xf16d,

    /// <summary>
    /// InstagramSquare - 0xe055 - ".fa-instagram-square"
    /// </summary>
    [Description(".fa-instagram-square")]
    InstagramSquare = 0xe055,

    /// <summary>
    /// Instalod - 0xe081 - ".fa-instalod"
    /// </summary>
    [Description(".fa-instalod")]
    Instalod = 0xe081,

    /// <summary>
    /// Intercom - 0xf7af - ".fa-intercom"
    /// </summary>
    [Description(".fa-intercom")]
    Intercom = 0xf7af,

    /// <summary>
    /// InternetExplorer - 0xf26b - ".fa-internet-explorer"
    /// </summary>
    [Description(".fa-internet-explorer")]
    InternetExplorer = 0xf26b,

    /// <summary>
    /// Invision - 0xf7b0 - ".fa-invision"
    /// </summary>
    [Description(".fa-invision")]
    Invision = 0xf7b0,

    /// <summary>
    /// Ioxhost - 0xf208 - ".fa-ioxhost"
    /// </summary>
    [Description(".fa-ioxhost")]
    Ioxhost = 0xf208,

    /// <summary>
    /// ItchIo - 0xf83a - ".fa-itch-io"
    /// </summary>
    [Description(".fa-itch-io")]
    ItchIo = 0xf83a,

    /// <summary>
    /// Itunes - 0xf3b4 - ".fa-itunes"
    /// </summary>
    [Description(".fa-itunes")]
    Itunes = 0xf3b4,

    /// <summary>
    /// ItunesNote - 0xf3b5 - ".fa-itunes-note"
    /// </summary>
    [Description(".fa-itunes-note")]
    ItunesNote = 0xf3b5,

    /// <summary>
    /// Java - 0xf4e4 - ".fa-java"
    /// </summary>
    [Description(".fa-java")]
    Java = 0xf4e4,

    /// <summary>
    /// JediOrder - 0xf50e - ".fa-jedi-order"
    /// </summary>
    [Description(".fa-jedi-order")]
    JediOrder = 0xf50e,

    /// <summary>
    /// Jenkins - 0xf3b6 - ".fa-jenkins"
    /// </summary>
    [Description(".fa-jenkins")]
    Jenkins = 0xf3b6,

    /// <summary>
    /// Jira - 0xf7b1 - ".fa-jira"
    /// </summary>
    [Description(".fa-jira")]
    Jira = 0xf7b1,

    /// <summary>
    /// Joget - 0xf3b7 - ".fa-joget"
    /// </summary>
    [Description(".fa-joget")]
    Joget = 0xf3b7,

    /// <summary>
    /// Joomla - 0xf1aa - ".fa-joomla"
    /// </summary>
    [Description(".fa-joomla")]
    Joomla = 0xf1aa,

    /// <summary>
    /// Js - 0xf3b8 - ".fa-js"
    /// </summary>
    [Description(".fa-js")]
    Js = 0xf3b8,

    /// <summary>
    /// JsSquare - 0xf3b9 - ".fa-js-square"
    /// </summary>
    [Description(".fa-js-square")]
    JsSquare = 0xf3b9,

    /// <summary>
    /// Jsfiddle - 0xf1cc - ".fa-jsfiddle"
    /// </summary>
    [Description(".fa-jsfiddle")]
    Jsfiddle = 0xf1cc,

    /// <summary>
    /// Jxl - 0xe67b - ".fa-jxl"
    /// </summary>
    [Description(".fa-jxl")]
    Jxl = 0xe67b,

    /// <summary>
    /// Kaggle - 0xf5fa - ".fa-kaggle"
    /// </summary>
    [Description(".fa-kaggle")]
    Kaggle = 0xf5fa,

    /// <summary>
    /// KakaoTalk - 0xe7d7 - ".fa-kakao-talk"
    /// </summary>
    [Description(".fa-kakao-talk")]
    KakaoTalk = 0xe7d7,

    /// <summary>
    /// Keybase - 0xf4f5 - ".fa-keybase"
    /// </summary>
    [Description(".fa-keybase")]
    Keybase = 0xf4f5,

    /// <summary>
    /// Keycdn - 0xf3ba - ".fa-keycdn"
    /// </summary>
    [Description(".fa-keycdn")]
    Keycdn = 0xf3ba,

    /// <summary>
    /// Kickstarter - 0xf3bb - ".fa-kickstarter"
    /// </summary>
    [Description(".fa-kickstarter")]
    Kickstarter = 0xf3bb,

    /// <summary>
    /// KickstarterK - 0xf3bc - ".fa-kickstarter-k"
    /// </summary>
    [Description(".fa-kickstarter-k")]
    KickstarterK = 0xf3bc,

    /// <summary>
    /// Korvue - 0xf42f - ".fa-korvue"
    /// </summary>
    [Description(".fa-korvue")]
    Korvue = 0xf42f,

    /// <summary>
    /// Laravel - 0xf3bd - ".fa-laravel"
    /// </summary>
    [Description(".fa-laravel")]
    Laravel = 0xf3bd,

    /// <summary>
    /// Lastfm - 0xf202 - ".fa-lastfm"
    /// </summary>
    [Description(".fa-lastfm")]
    Lastfm = 0xf202,

    /// <summary>
    /// LastfmSquare - 0xf203 - ".fa-lastfm-square"
    /// </summary>
    [Description(".fa-lastfm-square")]
    LastfmSquare = 0xf203,

    /// <summary>
    /// Leanpub - 0xf212 - ".fa-leanpub"
    /// </summary>
    [Description(".fa-leanpub")]
    Leanpub = 0xf212,

    /// <summary>
    /// Less - 0xf41d - ".fa-less"
    /// </summary>
    [Description(".fa-less")]
    Less = 0xf41d,

    /// <summary>
    /// Letterboxd - 0xe62d - ".fa-letterboxd"
    /// </summary>
    [Description(".fa-letterboxd")]
    Letterboxd = 0xe62d,

    /// <summary>
    /// Line - 0xf3c0 - ".fa-line"
    /// </summary>
    [Description(".fa-line")]
    Line = 0xf3c0,

    /// <summary>
    /// Linkedin - 0xf08c - ".fa-linkedin"
    /// </summary>
    [Description(".fa-linkedin")]
    Linkedin = 0xf08c,

    /// <summary>
    /// LinkedinIn - 0xf0e1 - ".fa-linkedin-in"
    /// </summary>
    [Description(".fa-linkedin-in")]
    LinkedinIn = 0xf0e1,

    /// <summary>
    /// Linktree - 0xe7d8 - ".fa-linktree"
    /// </summary>
    [Description(".fa-linktree")]
    Linktree = 0xe7d8,

    /// <summary>
    /// Linode - 0xf2b8 - ".fa-linode"
    /// </summary>
    [Description(".fa-linode")]
    Linode = 0xf2b8,

    /// <summary>
    /// Linux - 0xf17c - ".fa-linux"
    /// </summary>
    [Description(".fa-linux")]
    Linux = 0xf17c,

    /// <summary>
    /// Lumon - 0xe7e2 - ".fa-lumon"
    /// </summary>
    [Description(".fa-lumon")]
    Lumon = 0xe7e2,

    /// <summary>
    /// LumonDrop - 0xe7e3 - ".fa-lumon-drop"
    /// </summary>
    [Description(".fa-lumon-drop")]
    LumonDrop = 0xe7e3,

    /// <summary>
    /// Lyft - 0xf3c3 - ".fa-lyft"
    /// </summary>
    [Description(".fa-lyft")]
    Lyft = 0xf3c3,

    /// <summary>
    /// Magento - 0xf3c4 - ".fa-magento"
    /// </summary>
    [Description(".fa-magento")]
    Magento = 0xf3c4,

    /// <summary>
    /// Mailchimp - 0xf59e - ".fa-mailchimp"
    /// </summary>
    [Description(".fa-mailchimp")]
    Mailchimp = 0xf59e,

    /// <summary>
    /// Mandalorian - 0xf50f - ".fa-mandalorian"
    /// </summary>
    [Description(".fa-mandalorian")]
    Mandalorian = 0xf50f,

    /// <summary>
    /// Markdown - 0xf60f - ".fa-markdown"
    /// </summary>
    [Description(".fa-markdown")]
    Markdown = 0xf60f,

    /// <summary>
    /// Mastodon - 0xf4f6 - ".fa-mastodon"
    /// </summary>
    [Description(".fa-mastodon")]
    Mastodon = 0xf4f6,

    /// <summary>
    /// Maxcdn - 0xf136 - ".fa-maxcdn"
    /// </summary>
    [Description(".fa-maxcdn")]
    Maxcdn = 0xf136,

    /// <summary>
    /// Mdb - 0xf8ca - ".fa-mdb"
    /// </summary>
    [Description(".fa-mdb")]
    Mdb = 0xf8ca,

    /// <summary>
    /// Medapps - 0xf3c6 - ".fa-medapps"
    /// </summary>
    [Description(".fa-medapps")]
    Medapps = 0xf3c6,

    /// <summary>
    /// Medium - 0xf23a - ".fa-medium"
    /// </summary>
    [Description(".fa-medium")]
    Medium = 0xf23a,

    /// <summary>
    /// MediumM - 0xf23a - ".fa-medium-m"
    /// </summary>
    [Description(".fa-medium-m")]
    MediumM = 0xf23a,

    /// <summary>
    /// Medrt - 0xf3c8 - ".fa-medrt"
    /// </summary>
    [Description(".fa-medrt")]
    Medrt = 0xf3c8,

    /// <summary>
    /// Meetup - 0xf2e0 - ".fa-meetup"
    /// </summary>
    [Description(".fa-meetup")]
    Meetup = 0xf2e0,

    /// <summary>
    /// Megaport - 0xf5a3 - ".fa-megaport"
    /// </summary>
    [Description(".fa-megaport")]
    Megaport = 0xf5a3,

    /// <summary>
    /// Mendeley - 0xf7b3 - ".fa-mendeley"
    /// </summary>
    [Description(".fa-mendeley")]
    Mendeley = 0xf7b3,

    /// <summary>
    /// Meta - 0xe49b - ".fa-meta"
    /// </summary>
    [Description(".fa-meta")]
    Meta = 0xe49b,

    /// <summary>
    /// Microblog - 0xe01a - ".fa-microblog"
    /// </summary>
    [Description(".fa-microblog")]
    Microblog = 0xe01a,

    /// <summary>
    /// Microsoft - 0xf3ca - ".fa-microsoft"
    /// </summary>
    [Description(".fa-microsoft")]
    Microsoft = 0xf3ca,

    /// <summary>
    /// Mintbit - 0xe62f - ".fa-mintbit"
    /// </summary>
    [Description(".fa-mintbit")]
    Mintbit = 0xe62f,

    /// <summary>
    /// Mix - 0xf3cb - ".fa-mix"
    /// </summary>
    [Description(".fa-mix")]
    Mix = 0xf3cb,

    /// <summary>
    /// Mixcloud - 0xf289 - ".fa-mixcloud"
    /// </summary>
    [Description(".fa-mixcloud")]
    Mixcloud = 0xf289,

    /// <summary>
    /// Mixer - 0xe056 - ".fa-mixer"
    /// </summary>
    [Description(".fa-mixer")]
    Mixer = 0xe056,

    /// <summary>
    /// Mizuni - 0xf3cc - ".fa-mizuni"
    /// </summary>
    [Description(".fa-mizuni")]
    Mizuni = 0xf3cc,

    /// <summary>
    /// Modx - 0xf285 - ".fa-modx"
    /// </summary>
    [Description(".fa-modx")]
    Modx = 0xf285,

    /// <summary>
    /// Monero - 0xf3d0 - ".fa-monero"
    /// </summary>
    [Description(".fa-monero")]
    Monero = 0xf3d0,

    /// <summary>
    /// Napster - 0xf3d2 - ".fa-napster"
    /// </summary>
    [Description(".fa-napster")]
    Napster = 0xf3d2,

    /// <summary>
    /// Neos - 0xf612 - ".fa-neos"
    /// </summary>
    [Description(".fa-neos")]
    Neos = 0xf612,

    /// <summary>
    /// NfcDirectional - 0xe530 - ".fa-nfc-directional"
    /// </summary>
    [Description(".fa-nfc-directional")]
    NfcDirectional = 0xe530,

    /// <summary>
    /// NfcSymbol - 0xe531 - ".fa-nfc-symbol"
    /// </summary>
    [Description(".fa-nfc-symbol")]
    NfcSymbol = 0xe531,

    /// <summary>
    /// Nimblr - 0xf5a8 - ".fa-nimblr"
    /// </summary>
    [Description(".fa-nimblr")]
    Nimblr = 0xf5a8,

    /// <summary>
    /// Node - 0xf419 - ".fa-node"
    /// </summary>
    [Description(".fa-node")]
    Node = 0xf419,

    /// <summary>
    /// NodeJs - 0xf3d3 - ".fa-node-js"
    /// </summary>
    [Description(".fa-node-js")]
    NodeJs = 0xf3d3,

    /// <summary>
    /// Notion - 0xe7d9 - ".fa-notion"
    /// </summary>
    [Description(".fa-notion")]
    Notion = 0xe7d9,

    /// <summary>
    /// Npm - 0xf3d4 - ".fa-npm"
    /// </summary>
    [Description(".fa-npm")]
    Npm = 0xf3d4,

    /// <summary>
    /// Ns8 - 0xf3d5 - ".fa-ns8"
    /// </summary>
    [Description(".fa-ns8")]
    Ns8 = 0xf3d5,

    /// <summary>
    /// Nutritionix - 0xf3d6 - ".fa-nutritionix"
    /// </summary>
    [Description(".fa-nutritionix")]
    Nutritionix = 0xf3d6,

    /// <summary>
    /// OctopusDeploy - 0xe082 - ".fa-octopus-deploy"
    /// </summary>
    [Description(".fa-octopus-deploy")]
    OctopusDeploy = 0xe082,

    /// <summary>
    /// Odnoklassniki - 0xf263 - ".fa-odnoklassniki"
    /// </summary>
    [Description(".fa-odnoklassniki")]
    Odnoklassniki = 0xf263,

    /// <summary>
    /// OdnoklassnikiSquare - 0xf264 - ".fa-odnoklassniki-square"
    /// </summary>
    [Description(".fa-odnoklassniki-square")]
    OdnoklassnikiSquare = 0xf264,

    /// <summary>
    /// Odysee - 0xe5c6 - ".fa-odysee"
    /// </summary>
    [Description(".fa-odysee")]
    Odysee = 0xe5c6,

    /// <summary>
    /// OldRepublic - 0xf510 - ".fa-old-republic"
    /// </summary>
    [Description(".fa-old-republic")]
    OldRepublic = 0xf510,

    /// <summary>
    /// Openai - 0xe7cf - ".fa-openai"
    /// </summary>
    [Description(".fa-openai")]
    Openai = 0xe7cf,

    /// <summary>
    /// Opencart - 0xf23d - ".fa-opencart"
    /// </summary>
    [Description(".fa-opencart")]
    Opencart = 0xf23d,

    /// <summary>
    /// Openid - 0xf19b - ".fa-openid"
    /// </summary>
    [Description(".fa-openid")]
    Openid = 0xf19b,

    /// <summary>
    /// Opensuse - 0xe62b - ".fa-opensuse"
    /// </summary>
    [Description(".fa-opensuse")]
    Opensuse = 0xe62b,

    /// <summary>
    /// Opera - 0xf26a - ".fa-opera"
    /// </summary>
    [Description(".fa-opera")]
    Opera = 0xf26a,

    /// <summary>
    /// OptinMonster - 0xf23c - ".fa-optin-monster"
    /// </summary>
    [Description(".fa-optin-monster")]
    OptinMonster = 0xf23c,

    /// <summary>
    /// Orcid - 0xf8d2 - ".fa-orcid"
    /// </summary>
    [Description(".fa-orcid")]
    Orcid = 0xf8d2,

    /// <summary>
    /// Osi - 0xf41a - ".fa-osi"
    /// </summary>
    [Description(".fa-osi")]
    Osi = 0xf41a,

    /// <summary>
    /// Padlet - 0xe4a0 - ".fa-padlet"
    /// </summary>
    [Description(".fa-padlet")]
    Padlet = 0xe4a0,

    /// <summary>
    /// Page4 - 0xf3d7 - ".fa-page4"
    /// </summary>
    [Description(".fa-page4")]
    Page4 = 0xf3d7,

    /// <summary>
    /// Pagelines - 0xf18c - ".fa-pagelines"
    /// </summary>
    [Description(".fa-pagelines")]
    Pagelines = 0xf18c,

    /// <summary>
    /// Palfed - 0xf3d8 - ".fa-palfed"
    /// </summary>
    [Description(".fa-palfed")]
    Palfed = 0xf3d8,

    /// <summary>
    /// Pandora - 0xe7da - ".fa-pandora"
    /// </summary>
    [Description(".fa-pandora")]
    Pandora = 0xe7da,

    /// <summary>
    /// Patreon - 0xf3d9 - ".fa-patreon"
    /// </summary>
    [Description(".fa-patreon")]
    Patreon = 0xf3d9,

    /// <summary>
    /// Paypal - 0xf1ed - ".fa-paypal"
    /// </summary>
    [Description(".fa-paypal")]
    Paypal = 0xf1ed,

    /// <summary>
    /// Perbyte - 0xe083 - ".fa-perbyte"
    /// </summary>
    [Description(".fa-perbyte")]
    Perbyte = 0xe083,

    /// <summary>
    /// Periscope - 0xf3da - ".fa-periscope"
    /// </summary>
    [Description(".fa-periscope")]
    Periscope = 0xf3da,

    /// <summary>
    /// Phabricator - 0xf3db - ".fa-phabricator"
    /// </summary>
    [Description(".fa-phabricator")]
    Phabricator = 0xf3db,

    /// <summary>
    /// PhoenixFramework - 0xf3dc - ".fa-phoenix-framework"
    /// </summary>
    [Description(".fa-phoenix-framework")]
    PhoenixFramework = 0xf3dc,

    /// <summary>
    /// PhoenixSquadron - 0xf511 - ".fa-phoenix-squadron"
    /// </summary>
    [Description(".fa-phoenix-squadron")]
    PhoenixSquadron = 0xf511,

    /// <summary>
    /// Php - 0xf457 - ".fa-php"
    /// </summary>
    [Description(".fa-php")]
    Php = 0xf457,

    /// <summary>
    /// PiedPiper - 0xf2ae - ".fa-pied-piper"
    /// </summary>
    [Description(".fa-pied-piper")]
    PiedPiper = 0xf2ae,

    /// <summary>
    /// PiedPiperAlt - 0xf1a8 - ".fa-pied-piper-alt"
    /// </summary>
    [Description(".fa-pied-piper-alt")]
    PiedPiperAlt = 0xf1a8,

    /// <summary>
    /// PiedPiperHat - 0xf4e5 - ".fa-pied-piper-hat"
    /// </summary>
    [Description(".fa-pied-piper-hat")]
    PiedPiperHat = 0xf4e5,

    /// <summary>
    /// PiedPiperPp - 0xf1a7 - ".fa-pied-piper-pp"
    /// </summary>
    [Description(".fa-pied-piper-pp")]
    PiedPiperPp = 0xf1a7,

    /// <summary>
    /// PiedPiperSquare - 0xe01e - ".fa-pied-piper-square"
    /// </summary>
    [Description(".fa-pied-piper-square")]
    PiedPiperSquare = 0xe01e,

    /// <summary>
    /// Pinterest - 0xf0d2 - ".fa-pinterest"
    /// </summary>
    [Description(".fa-pinterest")]
    Pinterest = 0xf0d2,

    /// <summary>
    /// PinterestP - 0xf231 - ".fa-pinterest-p"
    /// </summary>
    [Description(".fa-pinterest-p")]
    PinterestP = 0xf231,

    /// <summary>
    /// PinterestSquare - 0xf0d3 - ".fa-pinterest-square"
    /// </summary>
    [Description(".fa-pinterest-square")]
    PinterestSquare = 0xf0d3,

    /// <summary>
    /// Pix - 0xe43a - ".fa-pix"
    /// </summary>
    [Description(".fa-pix")]
    Pix = 0xe43a,

    /// <summary>
    /// Pixelfed - 0xe7db - ".fa-pixelfed"
    /// </summary>
    [Description(".fa-pixelfed")]
    Pixelfed = 0xe7db,

    /// <summary>
    /// Pixiv - 0xe640 - ".fa-pixiv"
    /// </summary>
    [Description(".fa-pixiv")]
    Pixiv = 0xe640,

    /// <summary>
    /// Playstation - 0xf3df - ".fa-playstation"
    /// </summary>
    [Description(".fa-playstation")]
    Playstation = 0xf3df,

    /// <summary>
    /// ProductHunt - 0xf288 - ".fa-product-hunt"
    /// </summary>
    [Description(".fa-product-hunt")]
    ProductHunt = 0xf288,

    /// <summary>
    /// Pushed - 0xf3e1 - ".fa-pushed"
    /// </summary>
    [Description(".fa-pushed")]
    Pushed = 0xf3e1,

    /// <summary>
    /// Python - 0xf3e2 - ".fa-python"
    /// </summary>
    [Description(".fa-python")]
    Python = 0xf3e2,

    /// <summary>
    /// Qq - 0xf1d6 - ".fa-qq"
    /// </summary>
    [Description(".fa-qq")]
    Qq = 0xf1d6,

    /// <summary>
    /// Quinscape - 0xf459 - ".fa-quinscape"
    /// </summary>
    [Description(".fa-quinscape")]
    Quinscape = 0xf459,

    /// <summary>
    /// Quora - 0xf2c4 - ".fa-quora"
    /// </summary>
    [Description(".fa-quora")]
    Quora = 0xf2c4,

    /// <summary>
    /// RProject - 0xf4f7 - ".fa-r-project"
    /// </summary>
    [Description(".fa-r-project")]
    // ReSharper disable InconsistentNaming
    RProject = 0xf4f7,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// RaspberryPi - 0xf7bb - ".fa-raspberry-pi"
    /// </summary>
    [Description(".fa-raspberry-pi")]
    RaspberryPi = 0xf7bb,

    /// <summary>
    /// Ravelry - 0xf2d9 - ".fa-ravelry"
    /// </summary>
    [Description(".fa-ravelry")]
    Ravelry = 0xf2d9,

    /// <summary>
    /// React - 0xf41b - ".fa-react"
    /// </summary>
    [Description(".fa-react")]
    React = 0xf41b,

    /// <summary>
    /// Reacteurope - 0xf75d - ".fa-reacteurope"
    /// </summary>
    [Description(".fa-reacteurope")]
    Reacteurope = 0xf75d,

    /// <summary>
    /// Readme - 0xf4d5 - ".fa-readme"
    /// </summary>
    [Description(".fa-readme")]
    Readme = 0xf4d5,

    /// <summary>
    /// Rebel - 0xf1d0 - ".fa-rebel"
    /// </summary>
    [Description(".fa-rebel")]
    Rebel = 0xf1d0,

    /// <summary>
    /// RedRiver - 0xf3e3 - ".fa-red-river"
    /// </summary>
    [Description(".fa-red-river")]
    RedRiver = 0xf3e3,

    /// <summary>
    /// Reddit - 0xf1a1 - ".fa-reddit"
    /// </summary>
    [Description(".fa-reddit")]
    Reddit = 0xf1a1,

    /// <summary>
    /// RedditAlien - 0xf281 - ".fa-reddit-alien"
    /// </summary>
    [Description(".fa-reddit-alien")]
    RedditAlien = 0xf281,

    /// <summary>
    /// RedditSquare - 0xf1a2 - ".fa-reddit-square"
    /// </summary>
    [Description(".fa-reddit-square")]
    RedditSquare = 0xf1a2,

    /// <summary>
    /// Redhat - 0xf7bc - ".fa-redhat"
    /// </summary>
    [Description(".fa-redhat")]
    Redhat = 0xf7bc,

    /// <summary>
    /// Rendact - 0xf3e4 - ".fa-rendact"
    /// </summary>
    [Description(".fa-rendact")]
    Rendact = 0xf3e4,

    /// <summary>
    /// Renren - 0xf18b - ".fa-renren"
    /// </summary>
    [Description(".fa-renren")]
    Renren = 0xf18b,

    /// <summary>
    /// Replyd - 0xf3e6 - ".fa-replyd"
    /// </summary>
    [Description(".fa-replyd")]
    Replyd = 0xf3e6,

    /// <summary>
    /// Researchgate - 0xf4f8 - ".fa-researchgate"
    /// </summary>
    [Description(".fa-researchgate")]
    Researchgate = 0xf4f8,

    /// <summary>
    /// Resolving - 0xf3e7 - ".fa-resolving"
    /// </summary>
    [Description(".fa-resolving")]
    Resolving = 0xf3e7,

    /// <summary>
    /// Rev - 0xf5b2 - ".fa-rev"
    /// </summary>
    [Description(".fa-rev")]
    Rev = 0xf5b2,

    /// <summary>
    /// Rocketchat - 0xf3e8 - ".fa-rocketchat"
    /// </summary>
    [Description(".fa-rocketchat")]
    Rocketchat = 0xf3e8,

    /// <summary>
    /// Rockrms - 0xf3e9 - ".fa-rockrms"
    /// </summary>
    [Description(".fa-rockrms")]
    Rockrms = 0xf3e9,

    /// <summary>
    /// Rust - 0xe07a - ".fa-rust"
    /// </summary>
    [Description(".fa-rust")]
    Rust = 0xe07a,

    /// <summary>
    /// Safari - 0xf267 - ".fa-safari"
    /// </summary>
    [Description(".fa-safari")]
    Safari = 0xf267,

    /// <summary>
    /// Salesforce - 0xf83b - ".fa-salesforce"
    /// </summary>
    [Description(".fa-salesforce")]
    Salesforce = 0xf83b,

    /// <summary>
    /// Sass - 0xf41e - ".fa-sass"
    /// </summary>
    [Description(".fa-sass")]
    Sass = 0xf41e,

    /// <summary>
    /// Schlix - 0xf3ea - ".fa-schlix"
    /// </summary>
    [Description(".fa-schlix")]
    Schlix = 0xf3ea,

    /// <summary>
    /// Screenpal - 0xe570 - ".fa-screenpal"
    /// </summary>
    [Description(".fa-screenpal")]
    Screenpal = 0xe570,

    /// <summary>
    /// Scribd - 0xf28a - ".fa-scribd"
    /// </summary>
    [Description(".fa-scribd")]
    Scribd = 0xf28a,

    /// <summary>
    /// Searchengin - 0xf3eb - ".fa-searchengin"
    /// </summary>
    [Description(".fa-searchengin")]
    Searchengin = 0xf3eb,

    /// <summary>
    /// Sellcast - 0xf2da - ".fa-sellcast"
    /// </summary>
    [Description(".fa-sellcast")]
    Sellcast = 0xf2da,

    /// <summary>
    /// Sellsy - 0xf213 - ".fa-sellsy"
    /// </summary>
    [Description(".fa-sellsy")]
    Sellsy = 0xf213,

    /// <summary>
    /// Servicestack - 0xf3ec - ".fa-servicestack"
    /// </summary>
    [Description(".fa-servicestack")]
    Servicestack = 0xf3ec,

    /// <summary>
    /// Shirtsinbulk - 0xf214 - ".fa-shirtsinbulk"
    /// </summary>
    [Description(".fa-shirtsinbulk")]
    Shirtsinbulk = 0xf214,

    /// <summary>
    /// Shoelace - 0xe60c - ".fa-shoelace"
    /// </summary>
    [Description(".fa-shoelace")]
    Shoelace = 0xe60c,

    /// <summary>
    /// Shopify - 0xe057 - ".fa-shopify"
    /// </summary>
    [Description(".fa-shopify")]
    Shopify = 0xe057,

    /// <summary>
    /// Shopware - 0xf5b5 - ".fa-shopware"
    /// </summary>
    [Description(".fa-shopware")]
    Shopware = 0xf5b5,

    /// <summary>
    /// SignalMessenger - 0xe663 - ".fa-signal-messenger"
    /// </summary>
    [Description(".fa-signal-messenger")]
    SignalMessenger = 0xe663,

    /// <summary>
    /// Simplybuilt - 0xf215 - ".fa-simplybuilt"
    /// </summary>
    [Description(".fa-simplybuilt")]
    Simplybuilt = 0xf215,

    /// <summary>
    /// Sistrix - 0xf3ee - ".fa-sistrix"
    /// </summary>
    [Description(".fa-sistrix")]
    Sistrix = 0xf3ee,

    /// <summary>
    /// Sith - 0xf512 - ".fa-sith"
    /// </summary>
    [Description(".fa-sith")]
    Sith = 0xf512,

    /// <summary>
    /// Sitrox - 0xe44a - ".fa-sitrox"
    /// </summary>
    [Description(".fa-sitrox")]
    Sitrox = 0xe44a,

    /// <summary>
    /// Sketch - 0xf7c6 - ".fa-sketch"
    /// </summary>
    [Description(".fa-sketch")]
    Sketch = 0xf7c6,

    /// <summary>
    /// Skyatlas - 0xf216 - ".fa-skyatlas"
    /// </summary>
    [Description(".fa-skyatlas")]
    Skyatlas = 0xf216,

    /// <summary>
    /// Skype - 0xf17e - ".fa-skype"
    /// </summary>
    [Description(".fa-skype")]
    Skype = 0xf17e,

    /// <summary>
    /// Slack - 0xf198 - ".fa-slack"
    /// </summary>
    [Description(".fa-slack")]
    Slack = 0xf198,

    /// <summary>
    /// SlackHash - 0xf198 - ".fa-slack-hash"
    /// </summary>
    [Description(".fa-slack-hash")]
    SlackHash = 0xf198,

    /// <summary>
    /// Slideshare - 0xf1e7 - ".fa-slideshare"
    /// </summary>
    [Description(".fa-slideshare")]
    Slideshare = 0xf1e7,

    /// <summary>
    /// Snapchat - 0xf2ab - ".fa-snapchat"
    /// </summary>
    [Description(".fa-snapchat")]
    Snapchat = 0xf2ab,

    /// <summary>
    /// SnapchatGhost - 0xf2ab - ".fa-snapchat-ghost"
    /// </summary>
    [Description(".fa-snapchat-ghost")]
    SnapchatGhost = 0xf2ab,

    /// <summary>
    /// SnapchatSquare - 0xf2ad - ".fa-snapchat-square"
    /// </summary>
    [Description(".fa-snapchat-square")]
    SnapchatSquare = 0xf2ad,

    /// <summary>
    /// Soundcloud - 0xf1be - ".fa-soundcloud"
    /// </summary>
    [Description(".fa-soundcloud")]
    Soundcloud = 0xf1be,

    /// <summary>
    /// Sourcetree - 0xf7d3 - ".fa-sourcetree"
    /// </summary>
    [Description(".fa-sourcetree")]
    Sourcetree = 0xf7d3,

    /// <summary>
    /// SpaceAwesome - 0xe5ac - ".fa-space-awesome"
    /// </summary>
    [Description(".fa-space-awesome")]
    SpaceAwesome = 0xe5ac,

    /// <summary>
    /// Speakap - 0xf3f3 - ".fa-speakap"
    /// </summary>
    [Description(".fa-speakap")]
    Speakap = 0xf3f3,

    /// <summary>
    /// SpeakerDeck - 0xf83c - ".fa-speaker-deck"
    /// </summary>
    [Description(".fa-speaker-deck")]
    SpeakerDeck = 0xf83c,

    /// <summary>
    /// Spotify - 0xf1bc - ".fa-spotify"
    /// </summary>
    [Description(".fa-spotify")]
    Spotify = 0xf1bc,

    /// <summary>
    /// SquareBehance - 0xf1b5 - ".fa-square-behance"
    /// </summary>
    [Description(".fa-square-behance")]
    SquareBehance = 0xf1b5,

    /// <summary>
    /// SquareBluesky - 0xe6a3 - ".fa-square-bluesky"
    /// </summary>
    [Description(".fa-square-bluesky")]
    SquareBluesky = 0xe6a3,

    /// <summary>
    /// SquareDribbble - 0xf397 - ".fa-square-dribbble"
    /// </summary>
    [Description(".fa-square-dribbble")]
    SquareDribbble = 0xf397,

    /// <summary>
    /// SquareFacebook - 0xf082 - ".fa-square-facebook"
    /// </summary>
    [Description(".fa-square-facebook")]
    SquareFacebook = 0xf082,

    /// <summary>
    /// SquareFigma - 0xe7e4 - ".fa-square-figma"
    /// </summary>
    [Description(".fa-square-figma")]
    SquareFigma = 0xe7e4,

    /// <summary>
    /// SquareFontAwesome - 0xe5ad - ".fa-square-font-awesome"
    /// </summary>
    [Description(".fa-square-font-awesome")]
    SquareFontAwesome = 0xe5ad,

    /// <summary>
    /// SquareFontAwesomeStroke - 0xf35c - ".fa-square-font-awesome-stroke"
    /// </summary>
    [Description(".fa-square-font-awesome-stroke")]
    SquareFontAwesomeStroke = 0xf35c,

    /// <summary>
    /// SquareGit - 0xf1d2 - ".fa-square-git"
    /// </summary>
    [Description(".fa-square-git")]
    SquareGit = 0xf1d2,

    /// <summary>
    /// SquareGithub - 0xf092 - ".fa-square-github"
    /// </summary>
    [Description(".fa-square-github")]
    SquareGithub = 0xf092,

    /// <summary>
    /// SquareGitlab - 0xe5ae - ".fa-square-gitlab"
    /// </summary>
    [Description(".fa-square-gitlab")]
    SquareGitlab = 0xe5ae,

    /// <summary>
    /// SquareGooglePlus - 0xf0d4 - ".fa-square-google-plus"
    /// </summary>
    [Description(".fa-square-google-plus")]
    SquareGooglePlus = 0xf0d4,

    /// <summary>
    /// SquareHackerNews - 0xf3af - ".fa-square-hacker-news"
    /// </summary>
    [Description(".fa-square-hacker-news")]
    SquareHackerNews = 0xf3af,

    /// <summary>
    /// SquareInstagram - 0xe055 - ".fa-square-instagram"
    /// </summary>
    [Description(".fa-square-instagram")]
    SquareInstagram = 0xe055,

    /// <summary>
    /// SquareJs - 0xf3b9 - ".fa-square-js"
    /// </summary>
    [Description(".fa-square-js")]
    SquareJs = 0xf3b9,

    /// <summary>
    /// SquareKickstarter - 0xf3bb - ".fa-square-kickstarter"
    /// </summary>
    [Description(".fa-square-kickstarter")]
    SquareKickstarter = 0xf3bb,

    /// <summary>
    /// SquareLastfm - 0xf203 - ".fa-square-lastfm"
    /// </summary>
    [Description(".fa-square-lastfm")]
    SquareLastfm = 0xf203,

    /// <summary>
    /// SquareLetterboxd - 0xe62e - ".fa-square-letterboxd"
    /// </summary>
    [Description(".fa-square-letterboxd")]
    SquareLetterboxd = 0xe62e,

    /// <summary>
    /// SquareLinkedin - 0xe7d0 - ".fa-square-linkedin"
    /// </summary>
    [Description(".fa-square-linkedin")]
    SquareLinkedin = 0xe7d0,

    /// <summary>
    /// SquareOdnoklassniki - 0xf264 - ".fa-square-odnoklassniki"
    /// </summary>
    [Description(".fa-square-odnoklassniki")]
    SquareOdnoklassniki = 0xf264,

    /// <summary>
    /// SquarePiedPiper - 0xe01e - ".fa-square-pied-piper"
    /// </summary>
    [Description(".fa-square-pied-piper")]
    SquarePiedPiper = 0xe01e,

    /// <summary>
    /// SquarePinterest - 0xf0d3 - ".fa-square-pinterest"
    /// </summary>
    [Description(".fa-square-pinterest")]
    SquarePinterest = 0xf0d3,

    /// <summary>
    /// SquareReddit - 0xf1a2 - ".fa-square-reddit"
    /// </summary>
    [Description(".fa-square-reddit")]
    SquareReddit = 0xf1a2,

    /// <summary>
    /// SquareSnapchat - 0xf2ad - ".fa-square-snapchat"
    /// </summary>
    [Description(".fa-square-snapchat")]
    SquareSnapchat = 0xf2ad,

    /// <summary>
    /// SquareSteam - 0xf1b7 - ".fa-square-steam"
    /// </summary>
    [Description(".fa-square-steam")]
    SquareSteam = 0xf1b7,

    /// <summary>
    /// SquareThreads - 0xe619 - ".fa-square-threads"
    /// </summary>
    [Description(".fa-square-threads")]
    SquareThreads = 0xe619,

    /// <summary>
    /// SquareTumblr - 0xf174 - ".fa-square-tumblr"
    /// </summary>
    [Description(".fa-square-tumblr")]
    SquareTumblr = 0xf174,

    /// <summary>
    /// SquareTwitter - 0xf081 - ".fa-square-twitter"
    /// </summary>
    [Description(".fa-square-twitter")]
    SquareTwitter = 0xf081,

    /// <summary>
    /// SquareUpwork - 0xe67c - ".fa-square-upwork"
    /// </summary>
    [Description(".fa-square-upwork")]
    SquareUpwork = 0xe67c,

    /// <summary>
    /// SquareViadeo - 0xf2aa - ".fa-square-viadeo"
    /// </summary>
    [Description(".fa-square-viadeo")]
    SquareViadeo = 0xf2aa,

    /// <summary>
    /// SquareVimeo - 0xf194 - ".fa-square-vimeo"
    /// </summary>
    [Description(".fa-square-vimeo")]
    SquareVimeo = 0xf194,

    /// <summary>
    /// SquareWebAwesome - 0xe683 - ".fa-square-web-awesome"
    /// </summary>
    [Description(".fa-square-web-awesome")]
    SquareWebAwesome = 0xe683,

    /// <summary>
    /// SquareWebAwesomeStroke - 0xe684 - ".fa-square-web-awesome-stroke"
    /// </summary>
    [Description(".fa-square-web-awesome-stroke")]
    SquareWebAwesomeStroke = 0xe684,

    /// <summary>
    /// SquareWhatsapp - 0xf40c - ".fa-square-whatsapp"
    /// </summary>
    [Description(".fa-square-whatsapp")]
    SquareWhatsapp = 0xf40c,

    /// <summary>
    /// SquareXTwitter - 0xe61a - ".fa-square-x-twitter"
    /// </summary>
    [Description(".fa-square-x-twitter")]
    SquareXTwitter = 0xe61a,

    /// <summary>
    /// SquareXing - 0xf169 - ".fa-square-xing"
    /// </summary>
    [Description(".fa-square-xing")]
    SquareXing = 0xf169,

    /// <summary>
    /// SquareYoutube - 0xf431 - ".fa-square-youtube"
    /// </summary>
    [Description(".fa-square-youtube")]
    SquareYoutube = 0xf431,

    /// <summary>
    /// Squarespace - 0xf5be - ".fa-squarespace"
    /// </summary>
    [Description(".fa-squarespace")]
    Squarespace = 0xf5be,

    /// <summary>
    /// StackExchange - 0xf18d - ".fa-stack-exchange"
    /// </summary>
    [Description(".fa-stack-exchange")]
    StackExchange = 0xf18d,

    /// <summary>
    /// StackOverflow - 0xf16c - ".fa-stack-overflow"
    /// </summary>
    [Description(".fa-stack-overflow")]
    StackOverflow = 0xf16c,

    /// <summary>
    /// Stackpath - 0xf842 - ".fa-stackpath"
    /// </summary>
    [Description(".fa-stackpath")]
    Stackpath = 0xf842,

    /// <summary>
    /// Staylinked - 0xf3f5 - ".fa-staylinked"
    /// </summary>
    [Description(".fa-staylinked")]
    Staylinked = 0xf3f5,

    /// <summary>
    /// Steam - 0xf1b6 - ".fa-steam"
    /// </summary>
    [Description(".fa-steam")]
    Steam = 0xf1b6,

    /// <summary>
    /// SteamSquare - 0xf1b7 - ".fa-steam-square"
    /// </summary>
    [Description(".fa-steam-square")]
    SteamSquare = 0xf1b7,

    /// <summary>
    /// SteamSymbol - 0xf3f6 - ".fa-steam-symbol"
    /// </summary>
    [Description(".fa-steam-symbol")]
    SteamSymbol = 0xf3f6,

    /// <summary>
    /// StickerMule - 0xf3f7 - ".fa-sticker-mule"
    /// </summary>
    [Description(".fa-sticker-mule")]
    StickerMule = 0xf3f7,

    /// <summary>
    /// Strava - 0xf428 - ".fa-strava"
    /// </summary>
    [Description(".fa-strava")]
    Strava = 0xf428,

    /// <summary>
    /// Stripe - 0xf429 - ".fa-stripe"
    /// </summary>
    [Description(".fa-stripe")]
    Stripe = 0xf429,

    /// <summary>
    /// StripeS - 0xf42a - ".fa-stripe-s"
    /// </summary>
    [Description(".fa-stripe-s")]
    StripeS = 0xf42a,

    /// <summary>
    /// Stubber - 0xe5c7 - ".fa-stubber"
    /// </summary>
    [Description(".fa-stubber")]
    Stubber = 0xe5c7,

    /// <summary>
    /// Studiovinari - 0xf3f8 - ".fa-studiovinari"
    /// </summary>
    [Description(".fa-studiovinari")]
    Studiovinari = 0xf3f8,

    /// <summary>
    /// Stumbleupon - 0xf1a4 - ".fa-stumbleupon"
    /// </summary>
    [Description(".fa-stumbleupon")]
    Stumbleupon = 0xf1a4,

    /// <summary>
    /// StumbleuponCircle - 0xf1a3 - ".fa-stumbleupon-circle"
    /// </summary>
    [Description(".fa-stumbleupon-circle")]
    StumbleuponCircle = 0xf1a3,

    /// <summary>
    /// Superpowers - 0xf2dd - ".fa-superpowers"
    /// </summary>
    [Description(".fa-superpowers")]
    Superpowers = 0xf2dd,

    /// <summary>
    /// Supple - 0xf3f9 - ".fa-supple"
    /// </summary>
    [Description(".fa-supple")]
    Supple = 0xf3f9,

    /// <summary>
    /// Suse - 0xf7d6 - ".fa-suse"
    /// </summary>
    [Description(".fa-suse")]
    Suse = 0xf7d6,

    /// <summary>
    /// Swift - 0xf8e1 - ".fa-swift"
    /// </summary>
    [Description(".fa-swift")]
    Swift = 0xf8e1,

    /// <summary>
    /// Symfony - 0xf83d - ".fa-symfony"
    /// </summary>
    [Description(".fa-symfony")]
    Symfony = 0xf83d,

    /// <summary>
    /// Teamspeak - 0xf4f9 - ".fa-teamspeak"
    /// </summary>
    [Description(".fa-teamspeak")]
    Teamspeak = 0xf4f9,

    /// <summary>
    /// Telegram - 0xf2c6 - ".fa-telegram"
    /// </summary>
    [Description(".fa-telegram")]
    Telegram = 0xf2c6,

    /// <summary>
    /// TelegramPlane - 0xf2c6 - ".fa-telegram-plane"
    /// </summary>
    [Description(".fa-telegram-plane")]
    TelegramPlane = 0xf2c6,

    /// <summary>
    /// TencentWeibo - 0xf1d5 - ".fa-tencent-weibo"
    /// </summary>
    [Description(".fa-tencent-weibo")]
    TencentWeibo = 0xf1d5,

    /// <summary>
    /// Tex - 0xe7ff - ".fa-tex"
    /// </summary>
    [Description(".fa-tex")]
    Tex = 0xe7ff,

    /// <summary>
    /// TheRedYeti - 0xf69d - ".fa-the-red-yeti"
    /// </summary>
    [Description(".fa-the-red-yeti")]
    TheRedYeti = 0xf69d,

    /// <summary>
    /// Themeco - 0xf5c6 - ".fa-themeco"
    /// </summary>
    [Description(".fa-themeco")]
    Themeco = 0xf5c6,

    /// <summary>
    /// Themeisle - 0xf2b2 - ".fa-themeisle"
    /// </summary>
    [Description(".fa-themeisle")]
    Themeisle = 0xf2b2,

    /// <summary>
    /// ThinkPeaks - 0xf731 - ".fa-think-peaks"
    /// </summary>
    [Description(".fa-think-peaks")]
    ThinkPeaks = 0xf731,

    /// <summary>
    /// Threads - 0xe618 - ".fa-threads"
    /// </summary>
    [Description(".fa-threads")]
    Threads = 0xe618,

    /// <summary>
    /// Tidal - 0xe7dc - ".fa-tidal"
    /// </summary>
    [Description(".fa-tidal")]
    Tidal = 0xe7dc,

    /// <summary>
    /// Tiktok - 0xe07b - ".fa-tiktok"
    /// </summary>
    [Description(".fa-tiktok")]
    Tiktok = 0xe07b,

    /// <summary>
    /// TradeFederation - 0xf513 - ".fa-trade-federation"
    /// </summary>
    [Description(".fa-trade-federation")]
    TradeFederation = 0xf513,

    /// <summary>
    /// Trello - 0xf181 - ".fa-trello"
    /// </summary>
    [Description(".fa-trello")]
    Trello = 0xf181,

    /// <summary>
    /// Tumblr - 0xf173 - ".fa-tumblr"
    /// </summary>
    [Description(".fa-tumblr")]
    Tumblr = 0xf173,

    /// <summary>
    /// TumblrSquare - 0xf174 - ".fa-tumblr-square"
    /// </summary>
    [Description(".fa-tumblr-square")]
    TumblrSquare = 0xf174,

    /// <summary>
    /// Twitch - 0xf1e8 - ".fa-twitch"
    /// </summary>
    [Description(".fa-twitch")]
    Twitch = 0xf1e8,

    /// <summary>
    /// Twitter - 0xf099 - ".fa-twitter"
    /// </summary>
    [Description(".fa-twitter")]
    Twitter = 0xf099,

    /// <summary>
    /// TwitterSquare - 0xf081 - ".fa-twitter-square"
    /// </summary>
    [Description(".fa-twitter-square")]
    TwitterSquare = 0xf081,

    /// <summary>
    /// Typo3 - 0xf42b - ".fa-typo3"
    /// </summary>
    [Description(".fa-typo3")]
    Typo3 = 0xf42b,

    /// <summary>
    /// Uber - 0xf402 - ".fa-uber"
    /// </summary>
    [Description(".fa-uber")]
    Uber = 0xf402,

    /// <summary>
    /// Ubuntu - 0xf7df - ".fa-ubuntu"
    /// </summary>
    [Description(".fa-ubuntu")]
    Ubuntu = 0xf7df,

    /// <summary>
    /// Uikit - 0xf403 - ".fa-uikit"
    /// </summary>
    [Description(".fa-uikit")]
    Uikit = 0xf403,

    /// <summary>
    /// Umbraco - 0xf8e8 - ".fa-umbraco"
    /// </summary>
    [Description(".fa-umbraco")]
    Umbraco = 0xf8e8,

    /// <summary>
    /// Uncharted - 0xe084 - ".fa-uncharted"
    /// </summary>
    [Description(".fa-uncharted")]
    Uncharted = 0xe084,

    /// <summary>
    /// Uniregistry - 0xf404 - ".fa-uniregistry"
    /// </summary>
    [Description(".fa-uniregistry")]
    Uniregistry = 0xf404,

    /// <summary>
    /// Unity - 0xe049 - ".fa-unity"
    /// </summary>
    [Description(".fa-unity")]
    Unity = 0xe049,

    /// <summary>
    /// Unsplash - 0xe07c - ".fa-unsplash"
    /// </summary>
    [Description(".fa-unsplash")]
    Unsplash = 0xe07c,

    /// <summary>
    /// Untappd - 0xf405 - ".fa-untappd"
    /// </summary>
    [Description(".fa-untappd")]
    Untappd = 0xf405,

    /// <summary>
    /// Ups - 0xf7e0 - ".fa-ups"
    /// </summary>
    [Description(".fa-ups")]
    Ups = 0xf7e0,

    /// <summary>
    /// Upwork - 0xe641 - ".fa-upwork"
    /// </summary>
    [Description(".fa-upwork")]
    Upwork = 0xe641,

    /// <summary>
    /// Usb - 0xf287 - ".fa-usb"
    /// </summary>
    [Description(".fa-usb")]
    Usb = 0xf287,

    /// <summary>
    /// Usps - 0xf7e1 - ".fa-usps"
    /// </summary>
    [Description(".fa-usps")]
    Usps = 0xf7e1,

    /// <summary>
    /// Ussunnah - 0xf407 - ".fa-ussunnah"
    /// </summary>
    [Description(".fa-ussunnah")]
    Ussunnah = 0xf407,

    /// <summary>
    /// Vaadin - 0xf408 - ".fa-vaadin"
    /// </summary>
    [Description(".fa-vaadin")]
    Vaadin = 0xf408,

    /// <summary>
    /// Viacoin - 0xf237 - ".fa-viacoin"
    /// </summary>
    [Description(".fa-viacoin")]
    Viacoin = 0xf237,

    /// <summary>
    /// Viadeo - 0xf2a9 - ".fa-viadeo"
    /// </summary>
    [Description(".fa-viadeo")]
    Viadeo = 0xf2a9,

    /// <summary>
    /// ViadeoSquare - 0xf2aa - ".fa-viadeo-square"
    /// </summary>
    [Description(".fa-viadeo-square")]
    ViadeoSquare = 0xf2aa,

    /// <summary>
    /// Viber - 0xf409 - ".fa-viber"
    /// </summary>
    [Description(".fa-viber")]
    Viber = 0xf409,

    /// <summary>
    /// Vimeo - 0xf40a - ".fa-vimeo"
    /// </summary>
    [Description(".fa-vimeo")]
    Vimeo = 0xf40a,

    /// <summary>
    /// VimeoSquare - 0xf194 - ".fa-vimeo-square"
    /// </summary>
    [Description(".fa-vimeo-square")]
    VimeoSquare = 0xf194,

    /// <summary>
    /// VimeoV - 0xf27d - ".fa-vimeo-v"
    /// </summary>
    [Description(".fa-vimeo-v")]
    VimeoV = 0xf27d,

    /// <summary>
    /// Vine - 0xf1ca - ".fa-vine"
    /// </summary>
    [Description(".fa-vine")]
    Vine = 0xf1ca,

    /// <summary>
    /// Vk - 0xf189 - ".fa-vk"
    /// </summary>
    [Description(".fa-vk")]
    Vk = 0xf189,

    /// <summary>
    /// Vnv - 0xf40b - ".fa-vnv"
    /// </summary>
    [Description(".fa-vnv")]
    Vnv = 0xf40b,

    /// <summary>
    /// Vsco - 0xe7dd - ".fa-vsco"
    /// </summary>
    [Description(".fa-vsco")]
    Vsco = 0xe7dd,

    /// <summary>
    /// Vuejs - 0xf41f - ".fa-vuejs"
    /// </summary>
    [Description(".fa-vuejs")]
    Vuejs = 0xf41f,

    /// <summary>
    /// W3c - 0xe7de - ".fa-w3c"
    /// </summary>
    [Description(".fa-w3c")]
    W3c = 0xe7de,

    /// <summary>
    /// WatchmanMonitoring - 0xe087 - ".fa-watchman-monitoring"
    /// </summary>
    [Description(".fa-watchman-monitoring")]
    WatchmanMonitoring = 0xe087,

    /// <summary>
    /// Waze - 0xf83f - ".fa-waze"
    /// </summary>
    [Description(".fa-waze")]
    Waze = 0xf83f,

    /// <summary>
    /// WebAwesome - 0xe682 - ".fa-web-awesome"
    /// </summary>
    [Description(".fa-web-awesome")]
    WebAwesome = 0xe682,

    /// <summary>
    /// Webflow - 0xe65c - ".fa-webflow"
    /// </summary>
    [Description(".fa-webflow")]
    Webflow = 0xe65c,

    /// <summary>
    /// Weebly - 0xf5cc - ".fa-weebly"
    /// </summary>
    [Description(".fa-weebly")]
    Weebly = 0xf5cc,

    /// <summary>
    /// Weibo - 0xf18a - ".fa-weibo"
    /// </summary>
    [Description(".fa-weibo")]
    Weibo = 0xf18a,

    /// <summary>
    /// Weixin - 0xf1d7 - ".fa-weixin"
    /// </summary>
    [Description(".fa-weixin")]
    Weixin = 0xf1d7,

    /// <summary>
    /// Whatsapp - 0xf232 - ".fa-whatsapp"
    /// </summary>
    [Description(".fa-whatsapp")]
    Whatsapp = 0xf232,

    /// <summary>
    /// WhatsappSquare - 0xf40c - ".fa-whatsapp-square"
    /// </summary>
    [Description(".fa-whatsapp-square")]
    WhatsappSquare = 0xf40c,

    /// <summary>
    /// Whmcs - 0xf40d - ".fa-whmcs"
    /// </summary>
    [Description(".fa-whmcs")]
    Whmcs = 0xf40d,

    /// <summary>
    /// WikipediaW - 0xf266 - ".fa-wikipedia-w"
    /// </summary>
    [Description(".fa-wikipedia-w")]
    WikipediaW = 0xf266,

    /// <summary>
    /// Windows - 0xf17a - ".fa-windows"
    /// </summary>
    [Description(".fa-windows")]
    Windows = 0xf17a,

    /// <summary>
    /// Wirsindhandwerk - 0xe2d0 - ".fa-wirsindhandwerk"
    /// </summary>
    [Description(".fa-wirsindhandwerk")]
    Wirsindhandwerk = 0xe2d0,

    /// <summary>
    /// Wix - 0xf5cf - ".fa-wix"
    /// </summary>
    [Description(".fa-wix")]
    Wix = 0xf5cf,

    /// <summary>
    /// WizardsOfTheCoast - 0xf730 - ".fa-wizards-of-the-coast"
    /// </summary>
    [Description(".fa-wizards-of-the-coast")]
    WizardsOfTheCoast = 0xf730,

    /// <summary>
    /// Wodu - 0xe088 - ".fa-wodu"
    /// </summary>
    [Description(".fa-wodu")]
    Wodu = 0xe088,

    /// <summary>
    /// WolfPackBattalion - 0xf514 - ".fa-wolf-pack-battalion"
    /// </summary>
    [Description(".fa-wolf-pack-battalion")]
    WolfPackBattalion = 0xf514,

    /// <summary>
    /// Wordpress - 0xf19a - ".fa-wordpress"
    /// </summary>
    [Description(".fa-wordpress")]
    Wordpress = 0xf19a,

    /// <summary>
    /// WordpressSimple - 0xf411 - ".fa-wordpress-simple"
    /// </summary>
    [Description(".fa-wordpress-simple")]
    WordpressSimple = 0xf411,

    /// <summary>
    /// Wpbeginner - 0xf297 - ".fa-wpbeginner"
    /// </summary>
    [Description(".fa-wpbeginner")]
    Wpbeginner = 0xf297,

    /// <summary>
    /// Wpexplorer - 0xf2de - ".fa-wpexplorer"
    /// </summary>
    [Description(".fa-wpexplorer")]
    Wpexplorer = 0xf2de,

    /// <summary>
    /// Wpforms - 0xf298 - ".fa-wpforms"
    /// </summary>
    [Description(".fa-wpforms")]
    Wpforms = 0xf298,

    /// <summary>
    /// Wpressr - 0xf3e4 - ".fa-wpressr"
    /// </summary>
    [Description(".fa-wpressr")]
    Wpressr = 0xf3e4,

    /// <summary>
    /// Wsh - 0xe2d0 - ".fa-wsh"
    /// </summary>
    [Description(".fa-wsh")]
    Wsh = 0xe2d0,

    /// <summary>
    /// XTwitter - 0xe61b - ".fa-x-twitter"
    /// </summary>
    [Description(".fa-x-twitter")]
    // ReSharper disable InconsistentNaming
    XTwitter = 0xe61b,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// Xbox - 0xf412 - ".fa-xbox"
    /// </summary>
    [Description(".fa-xbox")]
    Xbox = 0xf412,

    /// <summary>
    /// Xing - 0xf168 - ".fa-xing"
    /// </summary>
    [Description(".fa-xing")]
    Xing = 0xf168,

    /// <summary>
    /// XingSquare - 0xf169 - ".fa-xing-square"
    /// </summary>
    [Description(".fa-xing-square")]
    XingSquare = 0xf169,

    /// <summary>
    /// YCombinator - 0xf23b - ".fa-y-combinator"
    /// </summary>
    [Description(".fa-y-combinator")]
    // ReSharper disable InconsistentNaming
    YCombinator = 0xf23b,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// Yahoo - 0xf19e - ".fa-yahoo"
    /// </summary>
    [Description(".fa-yahoo")]
    Yahoo = 0xf19e,

    /// <summary>
    /// Yammer - 0xf840 - ".fa-yammer"
    /// </summary>
    [Description(".fa-yammer")]
    Yammer = 0xf840,

    /// <summary>
    /// Yandex - 0xf413 - ".fa-yandex"
    /// </summary>
    [Description(".fa-yandex")]
    Yandex = 0xf413,

    /// <summary>
    /// YandexInternational - 0xf414 - ".fa-yandex-international"
    /// </summary>
    [Description(".fa-yandex-international")]
    YandexInternational = 0xf414,

    /// <summary>
    /// Yarn - 0xf7e3 - ".fa-yarn"
    /// </summary>
    [Description(".fa-yarn")]
    Yarn = 0xf7e3,

    /// <summary>
    /// Yelp - 0xf1e9 - ".fa-yelp"
    /// </summary>
    [Description(".fa-yelp")]
    Yelp = 0xf1e9,

    /// <summary>
    /// Yoast - 0xf2b1 - ".fa-yoast"
    /// </summary>
    [Description(".fa-yoast")]
    Yoast = 0xf2b1,

    /// <summary>
    /// Youtube - 0xf167 - ".fa-youtube"
    /// </summary>
    [Description(".fa-youtube")]
    Youtube = 0xf167,

    /// <summary>
    /// YoutubeSquare - 0xf431 - ".fa-youtube-square"
    /// </summary>
    [Description(".fa-youtube-square")]
    YoutubeSquare = 0xf431,

    /// <summary>
    /// Zhihu - 0xf63f - ".fa-zhihu"
    /// </summary>
    [Description(".fa-zhihu")]
    Zhihu = 0xf63f,

    /// <summary>
    /// _11ty - 0xe7d6 - ".fa-11ty"
    /// </summary>
    [Description(".fa-11ty")]
    // ReSharper disable InconsistentNaming
    _11ty = 0xe7d6,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _42Group - 0xe080 - ".fa-42-group"
    /// </summary>
    [Description(".fa-42-group")]
    // ReSharper disable InconsistentNaming
    _42Group = 0xe080,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _500px - 0xf26e - ".fa-500px"
    /// </summary>
    [Description(".fa-500px")]
    // ReSharper disable InconsistentNaming
    _500px = 0xf26e
    // ReSharper restore InconsistentNaming
}