//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool: Atc.Wpf.Generator.FontIconResources
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Atc.Wpf.FontIcons;

/// <summary>
/// Enumeration: FontAwesomeBrandType
/// </summary>
public enum FontAwesomeBrandType
{
    /// <summary>
    /// Default None
    /// </summary>
    None = 0x0,

    /// <summary>
    /// _500px - 0xf26e - ".fa-500px"
    /// </summary>
    [Description(".fa-500px")]
    // ReSharper disable InconsistentNaming
    _500px = 0xf26e,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// AccessibleIcon - 0xf368 - ".fa-accessible-icon"
    /// </summary>
    [Description(".fa-accessible-icon")]
    AccessibleIcon = 0xf368,

    /// <summary>
    /// Accusoft - 0xf369 - ".fa-accusoft"
    /// </summary>
    [Description(".fa-accusoft")]
    Accusoft = 0xf369,

    /// <summary>
    /// Adn - 0xf170 - ".fa-adn"
    /// </summary>
    [Description(".fa-adn")]
    Adn = 0xf170,

    /// <summary>
    /// Adversal - 0xf36a - ".fa-adversal"
    /// </summary>
    [Description(".fa-adversal")]
    Adversal = 0xf36a,

    /// <summary>
    /// Affiliatetheme - 0xf36b - ".fa-affiliatetheme"
    /// </summary>
    [Description(".fa-affiliatetheme")]
    Affiliatetheme = 0xf36b,

    /// <summary>
    /// Algolia - 0xf36c - ".fa-algolia"
    /// </summary>
    [Description(".fa-algolia")]
    Algolia = 0xf36c,

    /// <summary>
    /// Amazon - 0xf270 - ".fa-amazon"
    /// </summary>
    [Description(".fa-amazon")]
    Amazon = 0xf270,

    /// <summary>
    /// AmazonPay - 0xf42c - ".fa-amazon-pay"
    /// </summary>
    [Description(".fa-amazon-pay")]
    AmazonPay = 0xf42c,

    /// <summary>
    /// Amilia - 0xf36d - ".fa-amilia"
    /// </summary>
    [Description(".fa-amilia")]
    Amilia = 0xf36d,

    /// <summary>
    /// Android - 0xf17b - ".fa-android"
    /// </summary>
    [Description(".fa-android")]
    Android = 0xf17b,

    /// <summary>
    /// Angellist - 0xf209 - ".fa-angellist"
    /// </summary>
    [Description(".fa-angellist")]
    Angellist = 0xf209,

    /// <summary>
    /// Angrycreative - 0xf36e - ".fa-angrycreative"
    /// </summary>
    [Description(".fa-angrycreative")]
    Angrycreative = 0xf36e,

    /// <summary>
    /// Angular - 0xf420 - ".fa-angular"
    /// </summary>
    [Description(".fa-angular")]
    Angular = 0xf420,

    /// <summary>
    /// AppStore - 0xf36f - ".fa-app-store"
    /// </summary>
    [Description(".fa-app-store")]
    AppStore = 0xf36f,

    /// <summary>
    /// AppStoreIos - 0xf370 - ".fa-app-store-ios"
    /// </summary>
    [Description(".fa-app-store-ios")]
    AppStoreIos = 0xf370,

    /// <summary>
    /// Apper - 0xf371 - ".fa-apper"
    /// </summary>
    [Description(".fa-apper")]
    Apper = 0xf371,

    /// <summary>
    /// Apple - 0xf179 - ".fa-apple"
    /// </summary>
    [Description(".fa-apple")]
    Apple = 0xf179,

    /// <summary>
    /// ApplePay - 0xf415 - ".fa-apple-pay"
    /// </summary>
    [Description(".fa-apple-pay")]
    ApplePay = 0xf415,

    /// <summary>
    /// Asymmetrik - 0xf372 - ".fa-asymmetrik"
    /// </summary>
    [Description(".fa-asymmetrik")]
    Asymmetrik = 0xf372,

    /// <summary>
    /// Audible - 0xf373 - ".fa-audible"
    /// </summary>
    [Description(".fa-audible")]
    Audible = 0xf373,

    /// <summary>
    /// Autoprefixer - 0xf41c - ".fa-autoprefixer"
    /// </summary>
    [Description(".fa-autoprefixer")]
    Autoprefixer = 0xf41c,

    /// <summary>
    /// Avianex - 0xf374 - ".fa-avianex"
    /// </summary>
    [Description(".fa-avianex")]
    Avianex = 0xf374,

    /// <summary>
    /// Aviato - 0xf421 - ".fa-aviato"
    /// </summary>
    [Description(".fa-aviato")]
    Aviato = 0xf421,

    /// <summary>
    /// Aws - 0xf375 - ".fa-aws"
    /// </summary>
    [Description(".fa-aws")]
    Aws = 0xf375,

    /// <summary>
    /// Bandcamp - 0xf2d5 - ".fa-bandcamp"
    /// </summary>
    [Description(".fa-bandcamp")]
    Bandcamp = 0xf2d5,

    /// <summary>
    /// Behance - 0xf1b4 - ".fa-behance"
    /// </summary>
    [Description(".fa-behance")]
    Behance = 0xf1b4,

    /// <summary>
    /// BehanceSquare - 0xf1b5 - ".fa-behance-square"
    /// </summary>
    [Description(".fa-behance-square")]
    BehanceSquare = 0xf1b5,

    /// <summary>
    /// Bimobject - 0xf378 - ".fa-bimobject"
    /// </summary>
    [Description(".fa-bimobject")]
    Bimobject = 0xf378,

    /// <summary>
    /// Bitbucket - 0xf171 - ".fa-bitbucket"
    /// </summary>
    [Description(".fa-bitbucket")]
    Bitbucket = 0xf171,

    /// <summary>
    /// Bitcoin - 0xf379 - ".fa-bitcoin"
    /// </summary>
    [Description(".fa-bitcoin")]
    Bitcoin = 0xf379,

    /// <summary>
    /// Bity - 0xf37a - ".fa-bity"
    /// </summary>
    [Description(".fa-bity")]
    Bity = 0xf37a,

    /// <summary>
    /// BlackTie - 0xf27e - ".fa-black-tie"
    /// </summary>
    [Description(".fa-black-tie")]
    BlackTie = 0xf27e,

    /// <summary>
    /// Blackberry - 0xf37b - ".fa-blackberry"
    /// </summary>
    [Description(".fa-blackberry")]
    Blackberry = 0xf37b,

    /// <summary>
    /// Blogger - 0xf37c - ".fa-blogger"
    /// </summary>
    [Description(".fa-blogger")]
    Blogger = 0xf37c,

    /// <summary>
    /// Bloggerb - 0xf37d - ".fa-blogger-b"
    /// </summary>
    [Description(".fa-blogger-b")]
    Bloggerb = 0xf37d,

    /// <summary>
    /// Bluetooth - 0xf293 - ".fa-bluetooth"
    /// </summary>
    [Description(".fa-bluetooth")]
    Bluetooth = 0xf293,

    /// <summary>
    /// Bluetoothb - 0xf294 - ".fa-bluetooth-b"
    /// </summary>
    [Description(".fa-bluetooth-b")]
    Bluetoothb = 0xf294,

    /// <summary>
    /// Btc - 0xf15a - ".fa-btc"
    /// </summary>
    [Description(".fa-btc")]
    Btc = 0xf15a,

    /// <summary>
    /// Buromobelexperte - 0xf37f - ".fa-buromobelexperte"
    /// </summary>
    [Description(".fa-buromobelexperte")]
    Buromobelexperte = 0xf37f,

    /// <summary>
    /// Buysellads - 0xf20d - ".fa-buysellads"
    /// </summary>
    [Description(".fa-buysellads")]
    Buysellads = 0xf20d,

    /// <summary>
    /// CcAmazonPay - 0xf42d - ".fa-cc-amazon-pay"
    /// </summary>
    [Description(".fa-cc-amazon-pay")]
    CcAmazonPay = 0xf42d,

    /// <summary>
    /// CcAmex - 0xf1f3 - ".fa-cc-amex"
    /// </summary>
    [Description(".fa-cc-amex")]
    CcAmex = 0xf1f3,

    /// <summary>
    /// CcApplePay - 0xf416 - ".fa-cc-apple-pay"
    /// </summary>
    [Description(".fa-cc-apple-pay")]
    CcApplePay = 0xf416,

    /// <summary>
    /// CcDinersClub - 0xf24c - ".fa-cc-diners-club"
    /// </summary>
    [Description(".fa-cc-diners-club")]
    CcDinersClub = 0xf24c,

    /// <summary>
    /// CcDiscover - 0xf1f2 - ".fa-cc-discover"
    /// </summary>
    [Description(".fa-cc-discover")]
    CcDiscover = 0xf1f2,

    /// <summary>
    /// CcJcb - 0xf24b - ".fa-cc-jcb"
    /// </summary>
    [Description(".fa-cc-jcb")]
    CcJcb = 0xf24b,

    /// <summary>
    /// CcMastercard - 0xf1f1 - ".fa-cc-mastercard"
    /// </summary>
    [Description(".fa-cc-mastercard")]
    CcMastercard = 0xf1f1,

    /// <summary>
    /// CcPaypal - 0xf1f4 - ".fa-cc-paypal"
    /// </summary>
    [Description(".fa-cc-paypal")]
    CcPaypal = 0xf1f4,

    /// <summary>
    /// CcStripe - 0xf1f5 - ".fa-cc-stripe"
    /// </summary>
    [Description(".fa-cc-stripe")]
    CcStripe = 0xf1f5,

    /// <summary>
    /// CcVisa - 0xf1f0 - ".fa-cc-visa"
    /// </summary>
    [Description(".fa-cc-visa")]
    CcVisa = 0xf1f0,

    /// <summary>
    /// Centercode - 0xf380 - ".fa-centercode"
    /// </summary>
    [Description(".fa-centercode")]
    Centercode = 0xf380,

    /// <summary>
    /// Chrome - 0xf268 - ".fa-chrome"
    /// </summary>
    [Description(".fa-chrome")]
    Chrome = 0xf268,

    /// <summary>
    /// Cloudscale - 0xf383 - ".fa-cloudscale"
    /// </summary>
    [Description(".fa-cloudscale")]
    Cloudscale = 0xf383,

    /// <summary>
    /// Cloudsmith - 0xf384 - ".fa-cloudsmith"
    /// </summary>
    [Description(".fa-cloudsmith")]
    Cloudsmith = 0xf384,

    /// <summary>
    /// Cloudversify - 0xf385 - ".fa-cloudversify"
    /// </summary>
    [Description(".fa-cloudversify")]
    Cloudversify = 0xf385,

    /// <summary>
    /// Codepen - 0xf1cb - ".fa-codepen"
    /// </summary>
    [Description(".fa-codepen")]
    Codepen = 0xf1cb,

    /// <summary>
    /// Codiepie - 0xf284 - ".fa-codiepie"
    /// </summary>
    [Description(".fa-codiepie")]
    Codiepie = 0xf284,

    /// <summary>
    /// Connectdevelop - 0xf20e - ".fa-connectdevelop"
    /// </summary>
    [Description(".fa-connectdevelop")]
    Connectdevelop = 0xf20e,

    /// <summary>
    /// Contao - 0xf26d - ".fa-contao"
    /// </summary>
    [Description(".fa-contao")]
    Contao = 0xf26d,

    /// <summary>
    /// Cpanel - 0xf388 - ".fa-cpanel"
    /// </summary>
    [Description(".fa-cpanel")]
    Cpanel = 0xf388,

    /// <summary>
    /// CreativeCommons - 0xf25e - ".fa-creative-commons"
    /// </summary>
    [Description(".fa-creative-commons")]
    CreativeCommons = 0xf25e,

    /// <summary>
    /// CreativeCommonsBy - 0xf4e7 - ".fa-creative-commons-by"
    /// </summary>
    [Description(".fa-creative-commons-by")]
    CreativeCommonsBy = 0xf4e7,

    /// <summary>
    /// CreativeCommonsNc - 0xf4e8 - ".fa-creative-commons-nc"
    /// </summary>
    [Description(".fa-creative-commons-nc")]
    CreativeCommonsNc = 0xf4e8,

    /// <summary>
    /// CreativeCommonsNcEu - 0xf4e9 - ".fa-creative-commons-nc-eu"
    /// </summary>
    [Description(".fa-creative-commons-nc-eu")]
    CreativeCommonsNcEu = 0xf4e9,

    /// <summary>
    /// CreativeCommonsNcJp - 0xf4ea - ".fa-creative-commons-nc-jp"
    /// </summary>
    [Description(".fa-creative-commons-nc-jp")]
    CreativeCommonsNcJp = 0xf4ea,

    /// <summary>
    /// CreativeCommonsNd - 0xf4eb - ".fa-creative-commons-nd"
    /// </summary>
    [Description(".fa-creative-commons-nd")]
    CreativeCommonsNd = 0xf4eb,

    /// <summary>
    /// CreativeCommonsPd - 0xf4ec - ".fa-creative-commons-pd"
    /// </summary>
    [Description(".fa-creative-commons-pd")]
    CreativeCommonsPd = 0xf4ec,

    /// <summary>
    /// CreativeCommonsPdAlt - 0xf4ed - ".fa-creative-commons-pd-alt"
    /// </summary>
    [Description(".fa-creative-commons-pd-alt")]
    CreativeCommonsPdAlt = 0xf4ed,

    /// <summary>
    /// CreativeCommonsRemix - 0xf4ee - ".fa-creative-commons-remix"
    /// </summary>
    [Description(".fa-creative-commons-remix")]
    CreativeCommonsRemix = 0xf4ee,

    /// <summary>
    /// CreativeCommonsSa - 0xf4ef - ".fa-creative-commons-sa"
    /// </summary>
    [Description(".fa-creative-commons-sa")]
    CreativeCommonsSa = 0xf4ef,

    /// <summary>
    /// CreativeCommonsSampling - 0xf4f0 - ".fa-creative-commons-sampling"
    /// </summary>
    [Description(".fa-creative-commons-sampling")]
    CreativeCommonsSampling = 0xf4f0,

    /// <summary>
    /// CreativeCommonsSamplingPlus - 0xf4f1 - ".fa-creative-commons-sampling-plus"
    /// </summary>
    [Description(".fa-creative-commons-sampling-plus")]
    CreativeCommonsSamplingPlus = 0xf4f1,

    /// <summary>
    /// CreativeCommonsShare - 0xf4f2 - ".fa-creative-commons-share"
    /// </summary>
    [Description(".fa-creative-commons-share")]
    CreativeCommonsShare = 0xf4f2,

    /// <summary>
    /// Css3 - 0xf13c - ".fa-css3"
    /// </summary>
    [Description(".fa-css3")]
    Css3 = 0xf13c,

    /// <summary>
    /// Css3Alt - 0xf38b - ".fa-css3-alt"
    /// </summary>
    [Description(".fa-css3-alt")]
    Css3Alt = 0xf38b,

    /// <summary>
    /// Cuttlefish - 0xf38c - ".fa-cuttlefish"
    /// </summary>
    [Description(".fa-cuttlefish")]
    Cuttlefish = 0xf38c,

    /// <summary>
    /// DAndd - 0xf38d - ".fa-d-and-d"
    /// </summary>
    [Description(".fa-d-and-d")]
    // ReSharper disable InconsistentNaming
    DAndd = 0xf38d,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// Dashcube - 0xf210 - ".fa-dashcube"
    /// </summary>
    [Description(".fa-dashcube")]
    Dashcube = 0xf210,

    /// <summary>
    /// Delicious - 0xf1a5 - ".fa-delicious"
    /// </summary>
    [Description(".fa-delicious")]
    Delicious = 0xf1a5,

    /// <summary>
    /// Deploydog - 0xf38e - ".fa-deploydog"
    /// </summary>
    [Description(".fa-deploydog")]
    Deploydog = 0xf38e,

    /// <summary>
    /// Deskpro - 0xf38f - ".fa-deskpro"
    /// </summary>
    [Description(".fa-deskpro")]
    Deskpro = 0xf38f,

    /// <summary>
    /// Deviantart - 0xf1bd - ".fa-deviantart"
    /// </summary>
    [Description(".fa-deviantart")]
    Deviantart = 0xf1bd,

    /// <summary>
    /// Digg - 0xf1a6 - ".fa-digg"
    /// </summary>
    [Description(".fa-digg")]
    Digg = 0xf1a6,

    /// <summary>
    /// DigitalOcean - 0xf391 - ".fa-digital-ocean"
    /// </summary>
    [Description(".fa-digital-ocean")]
    DigitalOcean = 0xf391,

    /// <summary>
    /// Discord - 0xf392 - ".fa-discord"
    /// </summary>
    [Description(".fa-discord")]
    Discord = 0xf392,

    /// <summary>
    /// Discourse - 0xf393 - ".fa-discourse"
    /// </summary>
    [Description(".fa-discourse")]
    Discourse = 0xf393,

    /// <summary>
    /// Dochub - 0xf394 - ".fa-dochub"
    /// </summary>
    [Description(".fa-dochub")]
    Dochub = 0xf394,

    /// <summary>
    /// Docker - 0xf395 - ".fa-docker"
    /// </summary>
    [Description(".fa-docker")]
    Docker = 0xf395,

    /// <summary>
    /// Draft2digital - 0xf396 - ".fa-draft2digital"
    /// </summary>
    [Description(".fa-draft2digital")]
    Draft2digital = 0xf396,

    /// <summary>
    /// Dribbble - 0xf17d - ".fa-dribbble"
    /// </summary>
    [Description(".fa-dribbble")]
    Dribbble = 0xf17d,

    /// <summary>
    /// DribbbleSquare - 0xf397 - ".fa-dribbble-square"
    /// </summary>
    [Description(".fa-dribbble-square")]
    DribbbleSquare = 0xf397,

    /// <summary>
    /// Dropbox - 0xf16b - ".fa-dropbox"
    /// </summary>
    [Description(".fa-dropbox")]
    Dropbox = 0xf16b,

    /// <summary>
    /// Drupal - 0xf1a9 - ".fa-drupal"
    /// </summary>
    [Description(".fa-drupal")]
    Drupal = 0xf1a9,

    /// <summary>
    /// Dyalog - 0xf399 - ".fa-dyalog"
    /// </summary>
    [Description(".fa-dyalog")]
    Dyalog = 0xf399,

    /// <summary>
    /// Earlybirds - 0xf39a - ".fa-earlybirds"
    /// </summary>
    [Description(".fa-earlybirds")]
    Earlybirds = 0xf39a,

    /// <summary>
    /// Ebay - 0xf4f4 - ".fa-ebay"
    /// </summary>
    [Description(".fa-ebay")]
    Ebay = 0xf4f4,

    /// <summary>
    /// Edge - 0xf282 - ".fa-edge"
    /// </summary>
    [Description(".fa-edge")]
    Edge = 0xf282,

    /// <summary>
    /// Elementor - 0xf430 - ".fa-elementor"
    /// </summary>
    [Description(".fa-elementor")]
    Elementor = 0xf430,

    /// <summary>
    /// Ello - 0xf5f1 - ".fa-ello"
    /// </summary>
    [Description(".fa-ello")]
    Ello = 0xf5f1,

    /// <summary>
    /// Ember - 0xf423 - ".fa-ember"
    /// </summary>
    [Description(".fa-ember")]
    Ember = 0xf423,

    /// <summary>
    /// Empire - 0xf1d1 - ".fa-empire"
    /// </summary>
    [Description(".fa-empire")]
    Empire = 0xf1d1,

    /// <summary>
    /// Envira - 0xf299 - ".fa-envira"
    /// </summary>
    [Description(".fa-envira")]
    Envira = 0xf299,

    /// <summary>
    /// Erlang - 0xf39d - ".fa-erlang"
    /// </summary>
    [Description(".fa-erlang")]
    Erlang = 0xf39d,

    /// <summary>
    /// Ethereum - 0xf42e - ".fa-ethereum"
    /// </summary>
    [Description(".fa-ethereum")]
    Ethereum = 0xf42e,

    /// <summary>
    /// Etsy - 0xf2d7 - ".fa-etsy"
    /// </summary>
    [Description(".fa-etsy")]
    Etsy = 0xf2d7,

    /// <summary>
    /// Expeditedssl - 0xf23e - ".fa-expeditedssl"
    /// </summary>
    [Description(".fa-expeditedssl")]
    Expeditedssl = 0xf23e,

    /// <summary>
    /// Facebook - 0xf09a - ".fa-facebook"
    /// </summary>
    [Description(".fa-facebook")]
    Facebook = 0xf09a,

    /// <summary>
    /// Facebookf - 0xf39e - ".fa-facebook-f"
    /// </summary>
    [Description(".fa-facebook-f")]
    Facebookf = 0xf39e,

    /// <summary>
    /// FacebookMessenger - 0xf39f - ".fa-facebook-messenger"
    /// </summary>
    [Description(".fa-facebook-messenger")]
    FacebookMessenger = 0xf39f,

    /// <summary>
    /// FacebookSquare - 0xf082 - ".fa-facebook-square"
    /// </summary>
    [Description(".fa-facebook-square")]
    FacebookSquare = 0xf082,

    /// <summary>
    /// Firefox - 0xf269 - ".fa-firefox"
    /// </summary>
    [Description(".fa-firefox")]
    Firefox = 0xf269,

    /// <summary>
    /// FirstOrder - 0xf2b0 - ".fa-first-order"
    /// </summary>
    [Description(".fa-first-order")]
    FirstOrder = 0xf2b0,

    /// <summary>
    /// FirstOrderAlt - 0xf50a - ".fa-first-order-alt"
    /// </summary>
    [Description(".fa-first-order-alt")]
    FirstOrderAlt = 0xf50a,

    /// <summary>
    /// Firstdraft - 0xf3a1 - ".fa-firstdraft"
    /// </summary>
    [Description(".fa-firstdraft")]
    Firstdraft = 0xf3a1,

    /// <summary>
    /// Flickr - 0xf16e - ".fa-flickr"
    /// </summary>
    [Description(".fa-flickr")]
    Flickr = 0xf16e,

    /// <summary>
    /// Flipboard - 0xf44d - ".fa-flipboard"
    /// </summary>
    [Description(".fa-flipboard")]
    Flipboard = 0xf44d,

    /// <summary>
    /// Fly - 0xf417 - ".fa-fly"
    /// </summary>
    [Description(".fa-fly")]
    Fly = 0xf417,

    /// <summary>
    /// FontAwesome - 0xf2b4 - ".fa-font-awesome"
    /// </summary>
    [Description(".fa-font-awesome")]
    FontAwesome = 0xf2b4,

    /// <summary>
    /// FontAwesomeAlt - 0xf35c - ".fa-font-awesome-alt"
    /// </summary>
    [Description(".fa-font-awesome-alt")]
    FontAwesomeAlt = 0xf35c,

    /// <summary>
    /// FontAwesomeFlag - 0xf425 - ".fa-font-awesome-flag"
    /// </summary>
    [Description(".fa-font-awesome-flag")]
    FontAwesomeFlag = 0xf425,

    /// <summary>
    /// Fonticons - 0xf280 - ".fa-fonticons"
    /// </summary>
    [Description(".fa-fonticons")]
    Fonticons = 0xf280,

    /// <summary>
    /// FonticonsFi - 0xf3a2 - ".fa-fonticons-fi"
    /// </summary>
    [Description(".fa-fonticons-fi")]
    FonticonsFi = 0xf3a2,

    /// <summary>
    /// FortAwesome - 0xf286 - ".fa-fort-awesome"
    /// </summary>
    [Description(".fa-fort-awesome")]
    FortAwesome = 0xf286,

    /// <summary>
    /// FortAwesomeAlt - 0xf3a3 - ".fa-fort-awesome-alt"
    /// </summary>
    [Description(".fa-fort-awesome-alt")]
    FortAwesomeAlt = 0xf3a3,

    /// <summary>
    /// Forumbee - 0xf211 - ".fa-forumbee"
    /// </summary>
    [Description(".fa-forumbee")]
    Forumbee = 0xf211,

    /// <summary>
    /// Foursquare - 0xf180 - ".fa-foursquare"
    /// </summary>
    [Description(".fa-foursquare")]
    Foursquare = 0xf180,

    /// <summary>
    /// FreeCodeCamp - 0xf2c5 - ".fa-free-code-camp"
    /// </summary>
    [Description(".fa-free-code-camp")]
    FreeCodeCamp = 0xf2c5,

    /// <summary>
    /// Freebsd - 0xf3a4 - ".fa-freebsd"
    /// </summary>
    [Description(".fa-freebsd")]
    Freebsd = 0xf3a4,

    /// <summary>
    /// Fulcrum - 0xf50b - ".fa-fulcrum"
    /// </summary>
    [Description(".fa-fulcrum")]
    Fulcrum = 0xf50b,

    /// <summary>
    /// GalacticRepublic - 0xf50c - ".fa-galactic-republic"
    /// </summary>
    [Description(".fa-galactic-republic")]
    GalacticRepublic = 0xf50c,

    /// <summary>
    /// GalacticSenate - 0xf50d - ".fa-galactic-senate"
    /// </summary>
    [Description(".fa-galactic-senate")]
    GalacticSenate = 0xf50d,

    /// <summary>
    /// GetPocket - 0xf265 - ".fa-get-pocket"
    /// </summary>
    [Description(".fa-get-pocket")]
    GetPocket = 0xf265,

    /// <summary>
    /// Gg - 0xf260 - ".fa-gg"
    /// </summary>
    [Description(".fa-gg")]
    Gg = 0xf260,

    /// <summary>
    /// GgCircle - 0xf261 - ".fa-gg-circle"
    /// </summary>
    [Description(".fa-gg-circle")]
    GgCircle = 0xf261,

    /// <summary>
    /// Git - 0xf1d3 - ".fa-git"
    /// </summary>
    [Description(".fa-git")]
    Git = 0xf1d3,

    /// <summary>
    /// GitSquare - 0xf1d2 - ".fa-git-square"
    /// </summary>
    [Description(".fa-git-square")]
    GitSquare = 0xf1d2,

    /// <summary>
    /// Github - 0xf09b - ".fa-github"
    /// </summary>
    [Description(".fa-github")]
    Github = 0xf09b,

    /// <summary>
    /// GithubAlt - 0xf113 - ".fa-github-alt"
    /// </summary>
    [Description(".fa-github-alt")]
    GithubAlt = 0xf113,

    /// <summary>
    /// GithubSquare - 0xf092 - ".fa-github-square"
    /// </summary>
    [Description(".fa-github-square")]
    GithubSquare = 0xf092,

    /// <summary>
    /// Gitkraken - 0xf3a6 - ".fa-gitkraken"
    /// </summary>
    [Description(".fa-gitkraken")]
    Gitkraken = 0xf3a6,

    /// <summary>
    /// Gitlab - 0xf296 - ".fa-gitlab"
    /// </summary>
    [Description(".fa-gitlab")]
    Gitlab = 0xf296,

    /// <summary>
    /// Gitter - 0xf426 - ".fa-gitter"
    /// </summary>
    [Description(".fa-gitter")]
    Gitter = 0xf426,

    /// <summary>
    /// Glide - 0xf2a5 - ".fa-glide"
    /// </summary>
    [Description(".fa-glide")]
    Glide = 0xf2a5,

    /// <summary>
    /// Glideg - 0xf2a6 - ".fa-glide-g"
    /// </summary>
    [Description(".fa-glide-g")]
    Glideg = 0xf2a6,

    /// <summary>
    /// Gofore - 0xf3a7 - ".fa-gofore"
    /// </summary>
    [Description(".fa-gofore")]
    Gofore = 0xf3a7,

    /// <summary>
    /// Goodreads - 0xf3a8 - ".fa-goodreads"
    /// </summary>
    [Description(".fa-goodreads")]
    Goodreads = 0xf3a8,

    /// <summary>
    /// Goodreadsg - 0xf3a9 - ".fa-goodreads-g"
    /// </summary>
    [Description(".fa-goodreads-g")]
    Goodreadsg = 0xf3a9,

    /// <summary>
    /// Google - 0xf1a0 - ".fa-google"
    /// </summary>
    [Description(".fa-google")]
    Google = 0xf1a0,

    /// <summary>
    /// GoogleDrive - 0xf3aa - ".fa-google-drive"
    /// </summary>
    [Description(".fa-google-drive")]
    GoogleDrive = 0xf3aa,

    /// <summary>
    /// GooglePlay - 0xf3ab - ".fa-google-play"
    /// </summary>
    [Description(".fa-google-play")]
    GooglePlay = 0xf3ab,

    /// <summary>
    /// GooglePlus - 0xf2b3 - ".fa-google-plus"
    /// </summary>
    [Description(".fa-google-plus")]
    GooglePlus = 0xf2b3,

    /// <summary>
    /// GooglePlusg - 0xf0d5 - ".fa-google-plus-g"
    /// </summary>
    [Description(".fa-google-plus-g")]
    GooglePlusg = 0xf0d5,

    /// <summary>
    /// GooglePlusSquare - 0xf0d4 - ".fa-google-plus-square"
    /// </summary>
    [Description(".fa-google-plus-square")]
    GooglePlusSquare = 0xf0d4,

    /// <summary>
    /// GoogleWallet - 0xf1ee - ".fa-google-wallet"
    /// </summary>
    [Description(".fa-google-wallet")]
    GoogleWallet = 0xf1ee,

    /// <summary>
    /// Gratipay - 0xf184 - ".fa-gratipay"
    /// </summary>
    [Description(".fa-gratipay")]
    Gratipay = 0xf184,

    /// <summary>
    /// Grav - 0xf2d6 - ".fa-grav"
    /// </summary>
    [Description(".fa-grav")]
    Grav = 0xf2d6,

    /// <summary>
    /// Gripfire - 0xf3ac - ".fa-gripfire"
    /// </summary>
    [Description(".fa-gripfire")]
    Gripfire = 0xf3ac,

    /// <summary>
    /// Grunt - 0xf3ad - ".fa-grunt"
    /// </summary>
    [Description(".fa-grunt")]
    Grunt = 0xf3ad,

    /// <summary>
    /// Gulp - 0xf3ae - ".fa-gulp"
    /// </summary>
    [Description(".fa-gulp")]
    Gulp = 0xf3ae,

    /// <summary>
    /// HackerNews - 0xf1d4 - ".fa-hacker-news"
    /// </summary>
    [Description(".fa-hacker-news")]
    HackerNews = 0xf1d4,

    /// <summary>
    /// HackerNewsSquare - 0xf3af - ".fa-hacker-news-square"
    /// </summary>
    [Description(".fa-hacker-news-square")]
    HackerNewsSquare = 0xf3af,

    /// <summary>
    /// Hackerrank - 0xf5f7 - ".fa-hackerrank"
    /// </summary>
    [Description(".fa-hackerrank")]
    Hackerrank = 0xf5f7,

    /// <summary>
    /// Hips - 0xf452 - ".fa-hips"
    /// </summary>
    [Description(".fa-hips")]
    Hips = 0xf452,

    /// <summary>
    /// HireAHelper - 0xf3b0 - ".fa-hire-a-helper"
    /// </summary>
    [Description(".fa-hire-a-helper")]
    HireAHelper = 0xf3b0,

    /// <summary>
    /// Hooli - 0xf427 - ".fa-hooli"
    /// </summary>
    [Description(".fa-hooli")]
    Hooli = 0xf427,

    /// <summary>
    /// Hornbill - 0xf592 - ".fa-hornbill"
    /// </summary>
    [Description(".fa-hornbill")]
    Hornbill = 0xf592,

    /// <summary>
    /// Hotjar - 0xf3b1 - ".fa-hotjar"
    /// </summary>
    [Description(".fa-hotjar")]
    Hotjar = 0xf3b1,

    /// <summary>
    /// Houzz - 0xf27c - ".fa-houzz"
    /// </summary>
    [Description(".fa-houzz")]
    Houzz = 0xf27c,

    /// <summary>
    /// Html5 - 0xf13b - ".fa-html5"
    /// </summary>
    [Description(".fa-html5")]
    Html5 = 0xf13b,

    /// <summary>
    /// Hubspot - 0xf3b2 - ".fa-hubspot"
    /// </summary>
    [Description(".fa-hubspot")]
    Hubspot = 0xf3b2,

    /// <summary>
    /// Imdb - 0xf2d8 - ".fa-imdb"
    /// </summary>
    [Description(".fa-imdb")]
    Imdb = 0xf2d8,

    /// <summary>
    /// Instagram - 0xf16d - ".fa-instagram"
    /// </summary>
    [Description(".fa-instagram")]
    Instagram = 0xf16d,

    /// <summary>
    /// InternetExplorer - 0xf26b - ".fa-internet-explorer"
    /// </summary>
    [Description(".fa-internet-explorer")]
    InternetExplorer = 0xf26b,

    /// <summary>
    /// Ioxhost - 0xf208 - ".fa-ioxhost"
    /// </summary>
    [Description(".fa-ioxhost")]
    Ioxhost = 0xf208,

    /// <summary>
    /// Itunes - 0xf3b4 - ".fa-itunes"
    /// </summary>
    [Description(".fa-itunes")]
    Itunes = 0xf3b4,

    /// <summary>
    /// ItunesNote - 0xf3b5 - ".fa-itunes-note"
    /// </summary>
    [Description(".fa-itunes-note")]
    ItunesNote = 0xf3b5,

    /// <summary>
    /// Java - 0xf4e4 - ".fa-java"
    /// </summary>
    [Description(".fa-java")]
    Java = 0xf4e4,

    /// <summary>
    /// JediOrder - 0xf50e - ".fa-jedi-order"
    /// </summary>
    [Description(".fa-jedi-order")]
    JediOrder = 0xf50e,

    /// <summary>
    /// Jenkins - 0xf3b6 - ".fa-jenkins"
    /// </summary>
    [Description(".fa-jenkins")]
    Jenkins = 0xf3b6,

    /// <summary>
    /// Joget - 0xf3b7 - ".fa-joget"
    /// </summary>
    [Description(".fa-joget")]
    Joget = 0xf3b7,

    /// <summary>
    /// Joomla - 0xf1aa - ".fa-joomla"
    /// </summary>
    [Description(".fa-joomla")]
    Joomla = 0xf1aa,

    /// <summary>
    /// Js - 0xf3b8 - ".fa-js"
    /// </summary>
    [Description(".fa-js")]
    Js = 0xf3b8,

    /// <summary>
    /// JsSquare - 0xf3b9 - ".fa-js-square"
    /// </summary>
    [Description(".fa-js-square")]
    JsSquare = 0xf3b9,

    /// <summary>
    /// Jsfiddle - 0xf1cc - ".fa-jsfiddle"
    /// </summary>
    [Description(".fa-jsfiddle")]
    Jsfiddle = 0xf1cc,

    /// <summary>
    /// Kaggle - 0xf5fa - ".fa-kaggle"
    /// </summary>
    [Description(".fa-kaggle")]
    Kaggle = 0xf5fa,

    /// <summary>
    /// Keybase - 0xf4f5 - ".fa-keybase"
    /// </summary>
    [Description(".fa-keybase")]
    Keybase = 0xf4f5,

    /// <summary>
    /// Keycdn - 0xf3ba - ".fa-keycdn"
    /// </summary>
    [Description(".fa-keycdn")]
    Keycdn = 0xf3ba,

    /// <summary>
    /// Kickstarter - 0xf3bb - ".fa-kickstarter"
    /// </summary>
    [Description(".fa-kickstarter")]
    Kickstarter = 0xf3bb,

    /// <summary>
    /// Kickstarterk - 0xf3bc - ".fa-kickstarter-k"
    /// </summary>
    [Description(".fa-kickstarter-k")]
    Kickstarterk = 0xf3bc,

    /// <summary>
    /// Korvue - 0xf42f - ".fa-korvue"
    /// </summary>
    [Description(".fa-korvue")]
    Korvue = 0xf42f,

    /// <summary>
    /// Laravel - 0xf3bd - ".fa-laravel"
    /// </summary>
    [Description(".fa-laravel")]
    Laravel = 0xf3bd,

    /// <summary>
    /// Lastfm - 0xf202 - ".fa-lastfm"
    /// </summary>
    [Description(".fa-lastfm")]
    Lastfm = 0xf202,

    /// <summary>
    /// LastfmSquare - 0xf203 - ".fa-lastfm-square"
    /// </summary>
    [Description(".fa-lastfm-square")]
    LastfmSquare = 0xf203,

    /// <summary>
    /// Leanpub - 0xf212 - ".fa-leanpub"
    /// </summary>
    [Description(".fa-leanpub")]
    Leanpub = 0xf212,

    /// <summary>
    /// Less - 0xf41d - ".fa-less"
    /// </summary>
    [Description(".fa-less")]
    Less = 0xf41d,

    /// <summary>
    /// Line - 0xf3c0 - ".fa-line"
    /// </summary>
    [Description(".fa-line")]
    Line = 0xf3c0,

    /// <summary>
    /// Linkedin - 0xf08c - ".fa-linkedin"
    /// </summary>
    [Description(".fa-linkedin")]
    Linkedin = 0xf08c,

    /// <summary>
    /// LinkedinIn - 0xf0e1 - ".fa-linkedin-in"
    /// </summary>
    [Description(".fa-linkedin-in")]
    LinkedinIn = 0xf0e1,

    /// <summary>
    /// Linode - 0xf2b8 - ".fa-linode"
    /// </summary>
    [Description(".fa-linode")]
    Linode = 0xf2b8,

    /// <summary>
    /// Linux - 0xf17c - ".fa-linux"
    /// </summary>
    [Description(".fa-linux")]
    Linux = 0xf17c,

    /// <summary>
    /// Lyft - 0xf3c3 - ".fa-lyft"
    /// </summary>
    [Description(".fa-lyft")]
    Lyft = 0xf3c3,

    /// <summary>
    /// Magento - 0xf3c4 - ".fa-magento"
    /// </summary>
    [Description(".fa-magento")]
    Magento = 0xf3c4,

    /// <summary>
    /// Mailchimp - 0xf59e - ".fa-mailchimp"
    /// </summary>
    [Description(".fa-mailchimp")]
    Mailchimp = 0xf59e,

    /// <summary>
    /// Mandalorian - 0xf50f - ".fa-mandalorian"
    /// </summary>
    [Description(".fa-mandalorian")]
    Mandalorian = 0xf50f,

    /// <summary>
    /// Markdown - 0xf60f - ".fa-markdown"
    /// </summary>
    [Description(".fa-markdown")]
    Markdown = 0xf60f,

    /// <summary>
    /// Mastodon - 0xf4f6 - ".fa-mastodon"
    /// </summary>
    [Description(".fa-mastodon")]
    Mastodon = 0xf4f6,

    /// <summary>
    /// Maxcdn - 0xf136 - ".fa-maxcdn"
    /// </summary>
    [Description(".fa-maxcdn")]
    Maxcdn = 0xf136,

    /// <summary>
    /// Medapps - 0xf3c6 - ".fa-medapps"
    /// </summary>
    [Description(".fa-medapps")]
    Medapps = 0xf3c6,

    /// <summary>
    /// Medium - 0xf23a - ".fa-medium"
    /// </summary>
    [Description(".fa-medium")]
    Medium = 0xf23a,

    /// <summary>
    /// Mediumm - 0xf3c7 - ".fa-medium-m"
    /// </summary>
    [Description(".fa-medium-m")]
    Mediumm = 0xf3c7,

    /// <summary>
    /// Medrt - 0xf3c8 - ".fa-medrt"
    /// </summary>
    [Description(".fa-medrt")]
    Medrt = 0xf3c8,

    /// <summary>
    /// Meetup - 0xf2e0 - ".fa-meetup"
    /// </summary>
    [Description(".fa-meetup")]
    Meetup = 0xf2e0,

    /// <summary>
    /// Megaport - 0xf5a3 - ".fa-megaport"
    /// </summary>
    [Description(".fa-megaport")]
    Megaport = 0xf5a3,

    /// <summary>
    /// Microsoft - 0xf3ca - ".fa-microsoft"
    /// </summary>
    [Description(".fa-microsoft")]
    Microsoft = 0xf3ca,

    /// <summary>
    /// Mix - 0xf3cb - ".fa-mix"
    /// </summary>
    [Description(".fa-mix")]
    Mix = 0xf3cb,

    /// <summary>
    /// Mixcloud - 0xf289 - ".fa-mixcloud"
    /// </summary>
    [Description(".fa-mixcloud")]
    Mixcloud = 0xf289,

    /// <summary>
    /// Mizuni - 0xf3cc - ".fa-mizuni"
    /// </summary>
    [Description(".fa-mizuni")]
    Mizuni = 0xf3cc,

    /// <summary>
    /// Modx - 0xf285 - ".fa-modx"
    /// </summary>
    [Description(".fa-modx")]
    Modx = 0xf285,

    /// <summary>
    /// Monero - 0xf3d0 - ".fa-monero"
    /// </summary>
    [Description(".fa-monero")]
    Monero = 0xf3d0,

    /// <summary>
    /// Napster - 0xf3d2 - ".fa-napster"
    /// </summary>
    [Description(".fa-napster")]
    Napster = 0xf3d2,

    /// <summary>
    /// Neos - 0xf612 - ".fa-neos"
    /// </summary>
    [Description(".fa-neos")]
    Neos = 0xf612,

    /// <summary>
    /// Nimblr - 0xf5a8 - ".fa-nimblr"
    /// </summary>
    [Description(".fa-nimblr")]
    Nimblr = 0xf5a8,

    /// <summary>
    /// NintendoSwitch - 0xf418 - ".fa-nintendo-switch"
    /// </summary>
    [Description(".fa-nintendo-switch")]
    NintendoSwitch = 0xf418,

    /// <summary>
    /// Node - 0xf419 - ".fa-node"
    /// </summary>
    [Description(".fa-node")]
    Node = 0xf419,

    /// <summary>
    /// NodeJs - 0xf3d3 - ".fa-node-js"
    /// </summary>
    [Description(".fa-node-js")]
    NodeJs = 0xf3d3,

    /// <summary>
    /// Npm - 0xf3d4 - ".fa-npm"
    /// </summary>
    [Description(".fa-npm")]
    Npm = 0xf3d4,

    /// <summary>
    /// Ns8 - 0xf3d5 - ".fa-ns8"
    /// </summary>
    [Description(".fa-ns8")]
    Ns8 = 0xf3d5,

    /// <summary>
    /// Nutritionix - 0xf3d6 - ".fa-nutritionix"
    /// </summary>
    [Description(".fa-nutritionix")]
    Nutritionix = 0xf3d6,

    /// <summary>
    /// Odnoklassniki - 0xf263 - ".fa-odnoklassniki"
    /// </summary>
    [Description(".fa-odnoklassniki")]
    Odnoklassniki = 0xf263,

    /// <summary>
    /// OdnoklassnikiSquare - 0xf264 - ".fa-odnoklassniki-square"
    /// </summary>
    [Description(".fa-odnoklassniki-square")]
    OdnoklassnikiSquare = 0xf264,

    /// <summary>
    /// OldRepublic - 0xf510 - ".fa-old-republic"
    /// </summary>
    [Description(".fa-old-republic")]
    OldRepublic = 0xf510,

    /// <summary>
    /// Opencart - 0xf23d - ".fa-opencart"
    /// </summary>
    [Description(".fa-opencart")]
    Opencart = 0xf23d,

    /// <summary>
    /// Openid - 0xf19b - ".fa-openid"
    /// </summary>
    [Description(".fa-openid")]
    Openid = 0xf19b,

    /// <summary>
    /// Opera - 0xf26a - ".fa-opera"
    /// </summary>
    [Description(".fa-opera")]
    Opera = 0xf26a,

    /// <summary>
    /// OptinMonster - 0xf23c - ".fa-optin-monster"
    /// </summary>
    [Description(".fa-optin-monster")]
    OptinMonster = 0xf23c,

    /// <summary>
    /// Osi - 0xf41a - ".fa-osi"
    /// </summary>
    [Description(".fa-osi")]
    Osi = 0xf41a,

    /// <summary>
    /// Page4 - 0xf3d7 - ".fa-page4"
    /// </summary>
    [Description(".fa-page4")]
    Page4 = 0xf3d7,

    /// <summary>
    /// Pagelines - 0xf18c - ".fa-pagelines"
    /// </summary>
    [Description(".fa-pagelines")]
    Pagelines = 0xf18c,

    /// <summary>
    /// Palfed - 0xf3d8 - ".fa-palfed"
    /// </summary>
    [Description(".fa-palfed")]
    Palfed = 0xf3d8,

    /// <summary>
    /// Patreon - 0xf3d9 - ".fa-patreon"
    /// </summary>
    [Description(".fa-patreon")]
    Patreon = 0xf3d9,

    /// <summary>
    /// Paypal - 0xf1ed - ".fa-paypal"
    /// </summary>
    [Description(".fa-paypal")]
    Paypal = 0xf1ed,

    /// <summary>
    /// Periscope - 0xf3da - ".fa-periscope"
    /// </summary>
    [Description(".fa-periscope")]
    Periscope = 0xf3da,

    /// <summary>
    /// Phabricator - 0xf3db - ".fa-phabricator"
    /// </summary>
    [Description(".fa-phabricator")]
    Phabricator = 0xf3db,

    /// <summary>
    /// PhoenixFramework - 0xf3dc - ".fa-phoenix-framework"
    /// </summary>
    [Description(".fa-phoenix-framework")]
    PhoenixFramework = 0xf3dc,

    /// <summary>
    /// PhoenixSquadron - 0xf511 - ".fa-phoenix-squadron"
    /// </summary>
    [Description(".fa-phoenix-squadron")]
    PhoenixSquadron = 0xf511,

    /// <summary>
    /// Php - 0xf457 - ".fa-php"
    /// </summary>
    [Description(".fa-php")]
    Php = 0xf457,

    /// <summary>
    /// PiedPiper - 0xf2ae - ".fa-pied-piper"
    /// </summary>
    [Description(".fa-pied-piper")]
    PiedPiper = 0xf2ae,

    /// <summary>
    /// PiedPiperAlt - 0xf1a8 - ".fa-pied-piper-alt"
    /// </summary>
    [Description(".fa-pied-piper-alt")]
    PiedPiperAlt = 0xf1a8,

    /// <summary>
    /// PiedPiperHat - 0xf4e5 - ".fa-pied-piper-hat"
    /// </summary>
    [Description(".fa-pied-piper-hat")]
    PiedPiperHat = 0xf4e5,

    /// <summary>
    /// PiedPiperPp - 0xf1a7 - ".fa-pied-piper-pp"
    /// </summary>
    [Description(".fa-pied-piper-pp")]
    PiedPiperPp = 0xf1a7,

    /// <summary>
    /// Pinterest - 0xf0d2 - ".fa-pinterest"
    /// </summary>
    [Description(".fa-pinterest")]
    Pinterest = 0xf0d2,

    /// <summary>
    /// Pinterestp - 0xf231 - ".fa-pinterest-p"
    /// </summary>
    [Description(".fa-pinterest-p")]
    Pinterestp = 0xf231,

    /// <summary>
    /// PinterestSquare - 0xf0d3 - ".fa-pinterest-square"
    /// </summary>
    [Description(".fa-pinterest-square")]
    PinterestSquare = 0xf0d3,

    /// <summary>
    /// Playstation - 0xf3df - ".fa-playstation"
    /// </summary>
    [Description(".fa-playstation")]
    Playstation = 0xf3df,

    /// <summary>
    /// ProductHunt - 0xf288 - ".fa-product-hunt"
    /// </summary>
    [Description(".fa-product-hunt")]
    ProductHunt = 0xf288,

    /// <summary>
    /// Pushed - 0xf3e1 - ".fa-pushed"
    /// </summary>
    [Description(".fa-pushed")]
    Pushed = 0xf3e1,

    /// <summary>
    /// Python - 0xf3e2 - ".fa-python"
    /// </summary>
    [Description(".fa-python")]
    Python = 0xf3e2,

    /// <summary>
    /// Qq - 0xf1d6 - ".fa-qq"
    /// </summary>
    [Description(".fa-qq")]
    Qq = 0xf1d6,

    /// <summary>
    /// Quinscape - 0xf459 - ".fa-quinscape"
    /// </summary>
    [Description(".fa-quinscape")]
    Quinscape = 0xf459,

    /// <summary>
    /// Quora - 0xf2c4 - ".fa-quora"
    /// </summary>
    [Description(".fa-quora")]
    Quora = 0xf2c4,

    /// <summary>
    /// RProject - 0xf4f7 - ".fa-r-project"
    /// </summary>
    [Description(".fa-r-project")]
    // ReSharper disable InconsistentNaming
    RProject = 0xf4f7,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// Ravelry - 0xf2d9 - ".fa-ravelry"
    /// </summary>
    [Description(".fa-ravelry")]
    Ravelry = 0xf2d9,

    /// <summary>
    /// React - 0xf41b - ".fa-react"
    /// </summary>
    [Description(".fa-react")]
    React = 0xf41b,

    /// <summary>
    /// Readme - 0xf4d5 - ".fa-readme"
    /// </summary>
    [Description(".fa-readme")]
    Readme = 0xf4d5,

    /// <summary>
    /// Rebel - 0xf1d0 - ".fa-rebel"
    /// </summary>
    [Description(".fa-rebel")]
    Rebel = 0xf1d0,

    /// <summary>
    /// RedRiver - 0xf3e3 - ".fa-red-river"
    /// </summary>
    [Description(".fa-red-river")]
    RedRiver = 0xf3e3,

    /// <summary>
    /// Reddit - 0xf1a1 - ".fa-reddit"
    /// </summary>
    [Description(".fa-reddit")]
    Reddit = 0xf1a1,

    /// <summary>
    /// RedditAlien - 0xf281 - ".fa-reddit-alien"
    /// </summary>
    [Description(".fa-reddit-alien")]
    RedditAlien = 0xf281,

    /// <summary>
    /// RedditSquare - 0xf1a2 - ".fa-reddit-square"
    /// </summary>
    [Description(".fa-reddit-square")]
    RedditSquare = 0xf1a2,

    /// <summary>
    /// Rendact - 0xf3e4 - ".fa-rendact"
    /// </summary>
    [Description(".fa-rendact")]
    Rendact = 0xf3e4,

    /// <summary>
    /// Renren - 0xf18b - ".fa-renren"
    /// </summary>
    [Description(".fa-renren")]
    Renren = 0xf18b,

    /// <summary>
    /// Replyd - 0xf3e6 - ".fa-replyd"
    /// </summary>
    [Description(".fa-replyd")]
    Replyd = 0xf3e6,

    /// <summary>
    /// Researchgate - 0xf4f8 - ".fa-researchgate"
    /// </summary>
    [Description(".fa-researchgate")]
    Researchgate = 0xf4f8,

    /// <summary>
    /// Resolving - 0xf3e7 - ".fa-resolving"
    /// </summary>
    [Description(".fa-resolving")]
    Resolving = 0xf3e7,

    /// <summary>
    /// Rev - 0xf5b2 - ".fa-rev"
    /// </summary>
    [Description(".fa-rev")]
    Rev = 0xf5b2,

    /// <summary>
    /// Rocketchat - 0xf3e8 - ".fa-rocketchat"
    /// </summary>
    [Description(".fa-rocketchat")]
    Rocketchat = 0xf3e8,

    /// <summary>
    /// Rockrms - 0xf3e9 - ".fa-rockrms"
    /// </summary>
    [Description(".fa-rockrms")]
    Rockrms = 0xf3e9,

    /// <summary>
    /// Safari - 0xf267 - ".fa-safari"
    /// </summary>
    [Description(".fa-safari")]
    Safari = 0xf267,

    /// <summary>
    /// Sass - 0xf41e - ".fa-sass"
    /// </summary>
    [Description(".fa-sass")]
    Sass = 0xf41e,

    /// <summary>
    /// Schlix - 0xf3ea - ".fa-schlix"
    /// </summary>
    [Description(".fa-schlix")]
    Schlix = 0xf3ea,

    /// <summary>
    /// Scribd - 0xf28a - ".fa-scribd"
    /// </summary>
    [Description(".fa-scribd")]
    Scribd = 0xf28a,

    /// <summary>
    /// Searchengin - 0xf3eb - ".fa-searchengin"
    /// </summary>
    [Description(".fa-searchengin")]
    Searchengin = 0xf3eb,

    /// <summary>
    /// Sellcast - 0xf2da - ".fa-sellcast"
    /// </summary>
    [Description(".fa-sellcast")]
    Sellcast = 0xf2da,

    /// <summary>
    /// Sellsy - 0xf213 - ".fa-sellsy"
    /// </summary>
    [Description(".fa-sellsy")]
    Sellsy = 0xf213,

    /// <summary>
    /// Servicestack - 0xf3ec - ".fa-servicestack"
    /// </summary>
    [Description(".fa-servicestack")]
    Servicestack = 0xf3ec,

    /// <summary>
    /// Shirtsinbulk - 0xf214 - ".fa-shirtsinbulk"
    /// </summary>
    [Description(".fa-shirtsinbulk")]
    Shirtsinbulk = 0xf214,

    /// <summary>
    /// Shopware - 0xf5b5 - ".fa-shopware"
    /// </summary>
    [Description(".fa-shopware")]
    Shopware = 0xf5b5,

    /// <summary>
    /// Simplybuilt - 0xf215 - ".fa-simplybuilt"
    /// </summary>
    [Description(".fa-simplybuilt")]
    Simplybuilt = 0xf215,

    /// <summary>
    /// Sistrix - 0xf3ee - ".fa-sistrix"
    /// </summary>
    [Description(".fa-sistrix")]
    Sistrix = 0xf3ee,

    /// <summary>
    /// Sith - 0xf512 - ".fa-sith"
    /// </summary>
    [Description(".fa-sith")]
    Sith = 0xf512,

    /// <summary>
    /// Skyatlas - 0xf216 - ".fa-skyatlas"
    /// </summary>
    [Description(".fa-skyatlas")]
    Skyatlas = 0xf216,

    /// <summary>
    /// Skype - 0xf17e - ".fa-skype"
    /// </summary>
    [Description(".fa-skype")]
    Skype = 0xf17e,

    /// <summary>
    /// Slack - 0xf198 - ".fa-slack"
    /// </summary>
    [Description(".fa-slack")]
    Slack = 0xf198,

    /// <summary>
    /// SlackHash - 0xf3ef - ".fa-slack-hash"
    /// </summary>
    [Description(".fa-slack-hash")]
    SlackHash = 0xf3ef,

    /// <summary>
    /// Slideshare - 0xf1e7 - ".fa-slideshare"
    /// </summary>
    [Description(".fa-slideshare")]
    Slideshare = 0xf1e7,

    /// <summary>
    /// Snapchat - 0xf2ab - ".fa-snapchat"
    /// </summary>
    [Description(".fa-snapchat")]
    Snapchat = 0xf2ab,

    /// <summary>
    /// SnapchatGhost - 0xf2ac - ".fa-snapchat-ghost"
    /// </summary>
    [Description(".fa-snapchat-ghost")]
    SnapchatGhost = 0xf2ac,

    /// <summary>
    /// SnapchatSquare - 0xf2ad - ".fa-snapchat-square"
    /// </summary>
    [Description(".fa-snapchat-square")]
    SnapchatSquare = 0xf2ad,

    /// <summary>
    /// Soundcloud - 0xf1be - ".fa-soundcloud"
    /// </summary>
    [Description(".fa-soundcloud")]
    Soundcloud = 0xf1be,

    /// <summary>
    /// Speakap - 0xf3f3 - ".fa-speakap"
    /// </summary>
    [Description(".fa-speakap")]
    Speakap = 0xf3f3,

    /// <summary>
    /// Spotify - 0xf1bc - ".fa-spotify"
    /// </summary>
    [Description(".fa-spotify")]
    Spotify = 0xf1bc,

    /// <summary>
    /// Squarespace - 0xf5be - ".fa-squarespace"
    /// </summary>
    [Description(".fa-squarespace")]
    Squarespace = 0xf5be,

    /// <summary>
    /// StackExchange - 0xf18d - ".fa-stack-exchange"
    /// </summary>
    [Description(".fa-stack-exchange")]
    StackExchange = 0xf18d,

    /// <summary>
    /// StackOverflow - 0xf16c - ".fa-stack-overflow"
    /// </summary>
    [Description(".fa-stack-overflow")]
    StackOverflow = 0xf16c,

    /// <summary>
    /// Staylinked - 0xf3f5 - ".fa-staylinked"
    /// </summary>
    [Description(".fa-staylinked")]
    Staylinked = 0xf3f5,

    /// <summary>
    /// Steam - 0xf1b6 - ".fa-steam"
    /// </summary>
    [Description(".fa-steam")]
    Steam = 0xf1b6,

    /// <summary>
    /// SteamSquare - 0xf1b7 - ".fa-steam-square"
    /// </summary>
    [Description(".fa-steam-square")]
    SteamSquare = 0xf1b7,

    /// <summary>
    /// SteamSymbol - 0xf3f6 - ".fa-steam-symbol"
    /// </summary>
    [Description(".fa-steam-symbol")]
    SteamSymbol = 0xf3f6,

    /// <summary>
    /// StickerMule - 0xf3f7 - ".fa-sticker-mule"
    /// </summary>
    [Description(".fa-sticker-mule")]
    StickerMule = 0xf3f7,

    /// <summary>
    /// Strava - 0xf428 - ".fa-strava"
    /// </summary>
    [Description(".fa-strava")]
    Strava = 0xf428,

    /// <summary>
    /// Stripe - 0xf429 - ".fa-stripe"
    /// </summary>
    [Description(".fa-stripe")]
    Stripe = 0xf429,

    /// <summary>
    /// Stripes - 0xf42a - ".fa-stripe-s"
    /// </summary>
    [Description(".fa-stripe-s")]
    Stripes = 0xf42a,

    /// <summary>
    /// Studiovinari - 0xf3f8 - ".fa-studiovinari"
    /// </summary>
    [Description(".fa-studiovinari")]
    Studiovinari = 0xf3f8,

    /// <summary>
    /// Stumbleupon - 0xf1a4 - ".fa-stumbleupon"
    /// </summary>
    [Description(".fa-stumbleupon")]
    Stumbleupon = 0xf1a4,

    /// <summary>
    /// StumbleuponCircle - 0xf1a3 - ".fa-stumbleupon-circle"
    /// </summary>
    [Description(".fa-stumbleupon-circle")]
    StumbleuponCircle = 0xf1a3,

    /// <summary>
    /// Superpowers - 0xf2dd - ".fa-superpowers"
    /// </summary>
    [Description(".fa-superpowers")]
    Superpowers = 0xf2dd,

    /// <summary>
    /// Supple - 0xf3f9 - ".fa-supple"
    /// </summary>
    [Description(".fa-supple")]
    Supple = 0xf3f9,

    /// <summary>
    /// Teamspeak - 0xf4f9 - ".fa-teamspeak"
    /// </summary>
    [Description(".fa-teamspeak")]
    Teamspeak = 0xf4f9,

    /// <summary>
    /// Telegram - 0xf2c6 - ".fa-telegram"
    /// </summary>
    [Description(".fa-telegram")]
    Telegram = 0xf2c6,

    /// <summary>
    /// TelegramPlane - 0xf3fe - ".fa-telegram-plane"
    /// </summary>
    [Description(".fa-telegram-plane")]
    TelegramPlane = 0xf3fe,

    /// <summary>
    /// TencentWeibo - 0xf1d5 - ".fa-tencent-weibo"
    /// </summary>
    [Description(".fa-tencent-weibo")]
    TencentWeibo = 0xf1d5,

    /// <summary>
    /// Themeco - 0xf5c6 - ".fa-themeco"
    /// </summary>
    [Description(".fa-themeco")]
    Themeco = 0xf5c6,

    /// <summary>
    /// Themeisle - 0xf2b2 - ".fa-themeisle"
    /// </summary>
    [Description(".fa-themeisle")]
    Themeisle = 0xf2b2,

    /// <summary>
    /// TradeFederation - 0xf513 - ".fa-trade-federation"
    /// </summary>
    [Description(".fa-trade-federation")]
    TradeFederation = 0xf513,

    /// <summary>
    /// Trello - 0xf181 - ".fa-trello"
    /// </summary>
    [Description(".fa-trello")]
    Trello = 0xf181,

    /// <summary>
    /// Tripadvisor - 0xf262 - ".fa-tripadvisor"
    /// </summary>
    [Description(".fa-tripadvisor")]
    Tripadvisor = 0xf262,

    /// <summary>
    /// Tumblr - 0xf173 - ".fa-tumblr"
    /// </summary>
    [Description(".fa-tumblr")]
    Tumblr = 0xf173,

    /// <summary>
    /// TumblrSquare - 0xf174 - ".fa-tumblr-square"
    /// </summary>
    [Description(".fa-tumblr-square")]
    TumblrSquare = 0xf174,

    /// <summary>
    /// Twitch - 0xf1e8 - ".fa-twitch"
    /// </summary>
    [Description(".fa-twitch")]
    Twitch = 0xf1e8,

    /// <summary>
    /// Twitter - 0xf099 - ".fa-twitter"
    /// </summary>
    [Description(".fa-twitter")]
    Twitter = 0xf099,

    /// <summary>
    /// TwitterSquare - 0xf081 - ".fa-twitter-square"
    /// </summary>
    [Description(".fa-twitter-square")]
    TwitterSquare = 0xf081,

    /// <summary>
    /// Typo3 - 0xf42b - ".fa-typo3"
    /// </summary>
    [Description(".fa-typo3")]
    Typo3 = 0xf42b,

    /// <summary>
    /// Uber - 0xf402 - ".fa-uber"
    /// </summary>
    [Description(".fa-uber")]
    Uber = 0xf402,

    /// <summary>
    /// Uikit - 0xf403 - ".fa-uikit"
    /// </summary>
    [Description(".fa-uikit")]
    Uikit = 0xf403,

    /// <summary>
    /// Uniregistry - 0xf404 - ".fa-uniregistry"
    /// </summary>
    [Description(".fa-uniregistry")]
    Uniregistry = 0xf404,

    /// <summary>
    /// Untappd - 0xf405 - ".fa-untappd"
    /// </summary>
    [Description(".fa-untappd")]
    Untappd = 0xf405,

    /// <summary>
    /// Usb - 0xf287 - ".fa-usb"
    /// </summary>
    [Description(".fa-usb")]
    Usb = 0xf287,

    /// <summary>
    /// Ussunnah - 0xf407 - ".fa-ussunnah"
    /// </summary>
    [Description(".fa-ussunnah")]
    Ussunnah = 0xf407,

    /// <summary>
    /// Vaadin - 0xf408 - ".fa-vaadin"
    /// </summary>
    [Description(".fa-vaadin")]
    Vaadin = 0xf408,

    /// <summary>
    /// Viacoin - 0xf237 - ".fa-viacoin"
    /// </summary>
    [Description(".fa-viacoin")]
    Viacoin = 0xf237,

    /// <summary>
    /// Viadeo - 0xf2a9 - ".fa-viadeo"
    /// </summary>
    [Description(".fa-viadeo")]
    Viadeo = 0xf2a9,

    /// <summary>
    /// ViadeoSquare - 0xf2aa - ".fa-viadeo-square"
    /// </summary>
    [Description(".fa-viadeo-square")]
    ViadeoSquare = 0xf2aa,

    /// <summary>
    /// Viber - 0xf409 - ".fa-viber"
    /// </summary>
    [Description(".fa-viber")]
    Viber = 0xf409,

    /// <summary>
    /// Vimeo - 0xf40a - ".fa-vimeo"
    /// </summary>
    [Description(".fa-vimeo")]
    Vimeo = 0xf40a,

    /// <summary>
    /// VimeoSquare - 0xf194 - ".fa-vimeo-square"
    /// </summary>
    [Description(".fa-vimeo-square")]
    VimeoSquare = 0xf194,

    /// <summary>
    /// Vimeov - 0xf27d - ".fa-vimeo-v"
    /// </summary>
    [Description(".fa-vimeo-v")]
    Vimeov = 0xf27d,

    /// <summary>
    /// Vine - 0xf1ca - ".fa-vine"
    /// </summary>
    [Description(".fa-vine")]
    Vine = 0xf1ca,

    /// <summary>
    /// Vk - 0xf189 - ".fa-vk"
    /// </summary>
    [Description(".fa-vk")]
    Vk = 0xf189,

    /// <summary>
    /// Vnv - 0xf40b - ".fa-vnv"
    /// </summary>
    [Description(".fa-vnv")]
    Vnv = 0xf40b,

    /// <summary>
    /// Vuejs - 0xf41f - ".fa-vuejs"
    /// </summary>
    [Description(".fa-vuejs")]
    Vuejs = 0xf41f,

    /// <summary>
    /// Weebly - 0xf5cc - ".fa-weebly"
    /// </summary>
    [Description(".fa-weebly")]
    Weebly = 0xf5cc,

    /// <summary>
    /// Weibo - 0xf18a - ".fa-weibo"
    /// </summary>
    [Description(".fa-weibo")]
    Weibo = 0xf18a,

    /// <summary>
    /// Weixin - 0xf1d7 - ".fa-weixin"
    /// </summary>
    [Description(".fa-weixin")]
    Weixin = 0xf1d7,

    /// <summary>
    /// Whatsapp - 0xf232 - ".fa-whatsapp"
    /// </summary>
    [Description(".fa-whatsapp")]
    Whatsapp = 0xf232,

    /// <summary>
    /// WhatsappSquare - 0xf40c - ".fa-whatsapp-square"
    /// </summary>
    [Description(".fa-whatsapp-square")]
    WhatsappSquare = 0xf40c,

    /// <summary>
    /// Whmcs - 0xf40d - ".fa-whmcs"
    /// </summary>
    [Description(".fa-whmcs")]
    Whmcs = 0xf40d,

    /// <summary>
    /// Wikipediaw - 0xf266 - ".fa-wikipedia-w"
    /// </summary>
    [Description(".fa-wikipedia-w")]
    Wikipediaw = 0xf266,

    /// <summary>
    /// Windows - 0xf17a - ".fa-windows"
    /// </summary>
    [Description(".fa-windows")]
    Windows = 0xf17a,

    /// <summary>
    /// Wix - 0xf5cf - ".fa-wix"
    /// </summary>
    [Description(".fa-wix")]
    Wix = 0xf5cf,

    /// <summary>
    /// WolfPackBattalion - 0xf514 - ".fa-wolf-pack-battalion"
    /// </summary>
    [Description(".fa-wolf-pack-battalion")]
    WolfPackBattalion = 0xf514,

    /// <summary>
    /// Wordpress - 0xf19a - ".fa-wordpress"
    /// </summary>
    [Description(".fa-wordpress")]
    Wordpress = 0xf19a,

    /// <summary>
    /// WordpressSimple - 0xf411 - ".fa-wordpress-simple"
    /// </summary>
    [Description(".fa-wordpress-simple")]
    WordpressSimple = 0xf411,

    /// <summary>
    /// Wpbeginner - 0xf297 - ".fa-wpbeginner"
    /// </summary>
    [Description(".fa-wpbeginner")]
    Wpbeginner = 0xf297,

    /// <summary>
    /// Wpexplorer - 0xf2de - ".fa-wpexplorer"
    /// </summary>
    [Description(".fa-wpexplorer")]
    Wpexplorer = 0xf2de,

    /// <summary>
    /// Wpforms - 0xf298 - ".fa-wpforms"
    /// </summary>
    [Description(".fa-wpforms")]
    Wpforms = 0xf298,

    /// <summary>
    /// Xbox - 0xf412 - ".fa-xbox"
    /// </summary>
    [Description(".fa-xbox")]
    Xbox = 0xf412,

    /// <summary>
    /// Xing - 0xf168 - ".fa-xing"
    /// </summary>
    [Description(".fa-xing")]
    Xing = 0xf168,

    /// <summary>
    /// XingSquare - 0xf169 - ".fa-xing-square"
    /// </summary>
    [Description(".fa-xing-square")]
    XingSquare = 0xf169,

    /// <summary>
    /// YCombinator - 0xf23b - ".fa-y-combinator"
    /// </summary>
    [Description(".fa-y-combinator")]
    // ReSharper disable InconsistentNaming
    YCombinator = 0xf23b,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// Yahoo - 0xf19e - ".fa-yahoo"
    /// </summary>
    [Description(".fa-yahoo")]
    Yahoo = 0xf19e,

    /// <summary>
    /// Yandex - 0xf413 - ".fa-yandex"
    /// </summary>
    [Description(".fa-yandex")]
    Yandex = 0xf413,

    /// <summary>
    /// YandexInternational - 0xf414 - ".fa-yandex-international"
    /// </summary>
    [Description(".fa-yandex-international")]
    YandexInternational = 0xf414,

    /// <summary>
    /// Yelp - 0xf1e9 - ".fa-yelp"
    /// </summary>
    [Description(".fa-yelp")]
    Yelp = 0xf1e9,

    /// <summary>
    /// Yoast - 0xf2b1 - ".fa-yoast"
    /// </summary>
    [Description(".fa-yoast")]
    Yoast = 0xf2b1,

    /// <summary>
    /// Youtube - 0xf167 - ".fa-youtube"
    /// </summary>
    [Description(".fa-youtube")]
    Youtube = 0xf167,

    /// <summary>
    /// YoutubeSquare - 0xf431 - ".fa-youtube-square"
    /// </summary>
    [Description(".fa-youtube-square")]
    YoutubeSquare = 0xf431,

    /// <summary>
    /// Zhihu - 0xf63f - ".fa-zhihu"
    /// </summary>
    [Description(".fa-zhihu")]
    Zhihu = 0xf63f
}