//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool: Atc.Wpf.Generator.FontIconResources
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Atc.Wpf.FontIcons;

/// <summary>
/// Enumeration: FontAwesomeRegularType
/// </summary>
public enum FontAwesomeRegularType
{
    /// <summary>
    /// Default None
    /// </summary>
    None = 0x0,

    /// <summary>
    /// AddressBook - 0xf2b9 - ".fa-address-book"
    /// </summary>
    [Description(".fa-address-book")]
    AddressBook = 0xf2b9,

    /// <summary>
    /// AddressCard - 0xf2bb - ".fa-address-card"
    /// </summary>
    [Description(".fa-address-card")]
    AddressCard = 0xf2bb,

    /// <summary>
    /// Angry - 0xf556 - ".fa-angry"
    /// </summary>
    [Description(".fa-angry")]
    Angry = 0xf556,

    /// <summary>
    /// ArrowAltCircleDown - 0xf358 - ".fa-arrow-alt-circle-down"
    /// </summary>
    [Description(".fa-arrow-alt-circle-down")]
    ArrowAltCircleDown = 0xf358,

    /// <summary>
    /// ArrowAltCircleLeft - 0xf359 - ".fa-arrow-alt-circle-left"
    /// </summary>
    [Description(".fa-arrow-alt-circle-left")]
    ArrowAltCircleLeft = 0xf359,

    /// <summary>
    /// ArrowAltCircleRight - 0xf35a - ".fa-arrow-alt-circle-right"
    /// </summary>
    [Description(".fa-arrow-alt-circle-right")]
    ArrowAltCircleRight = 0xf35a,

    /// <summary>
    /// ArrowAltCircleUp - 0xf35b - ".fa-arrow-alt-circle-up"
    /// </summary>
    [Description(".fa-arrow-alt-circle-up")]
    ArrowAltCircleUp = 0xf35b,

    /// <summary>
    /// Bell - 0xf0f3 - ".fa-bell"
    /// </summary>
    [Description(".fa-bell")]
    Bell = 0xf0f3,

    /// <summary>
    /// BellSlash - 0xf1f6 - ".fa-bell-slash"
    /// </summary>
    [Description(".fa-bell-slash")]
    BellSlash = 0xf1f6,

    /// <summary>
    /// Bookmark - 0xf02e - ".fa-bookmark"
    /// </summary>
    [Description(".fa-bookmark")]
    Bookmark = 0xf02e,

    /// <summary>
    /// Building - 0xf1ad - ".fa-building"
    /// </summary>
    [Description(".fa-building")]
    Building = 0xf1ad,

    /// <summary>
    /// Calendar - 0xf133 - ".fa-calendar"
    /// </summary>
    [Description(".fa-calendar")]
    Calendar = 0xf133,

    /// <summary>
    /// CalendarAlt - 0xf073 - ".fa-calendar-alt"
    /// </summary>
    [Description(".fa-calendar-alt")]
    CalendarAlt = 0xf073,

    /// <summary>
    /// CalendarCheck - 0xf274 - ".fa-calendar-check"
    /// </summary>
    [Description(".fa-calendar-check")]
    CalendarCheck = 0xf274,

    /// <summary>
    /// CalendarMinus - 0xf272 - ".fa-calendar-minus"
    /// </summary>
    [Description(".fa-calendar-minus")]
    CalendarMinus = 0xf272,

    /// <summary>
    /// CalendarPlus - 0xf271 - ".fa-calendar-plus"
    /// </summary>
    [Description(".fa-calendar-plus")]
    CalendarPlus = 0xf271,

    /// <summary>
    /// CalendarTimes - 0xf273 - ".fa-calendar-times"
    /// </summary>
    [Description(".fa-calendar-times")]
    CalendarTimes = 0xf273,

    /// <summary>
    /// CaretSquareDown - 0xf150 - ".fa-caret-square-down"
    /// </summary>
    [Description(".fa-caret-square-down")]
    CaretSquareDown = 0xf150,

    /// <summary>
    /// CaretSquareLeft - 0xf191 - ".fa-caret-square-left"
    /// </summary>
    [Description(".fa-caret-square-left")]
    CaretSquareLeft = 0xf191,

    /// <summary>
    /// CaretSquareRight - 0xf152 - ".fa-caret-square-right"
    /// </summary>
    [Description(".fa-caret-square-right")]
    CaretSquareRight = 0xf152,

    /// <summary>
    /// CaretSquareUp - 0xf151 - ".fa-caret-square-up"
    /// </summary>
    [Description(".fa-caret-square-up")]
    CaretSquareUp = 0xf151,

    /// <summary>
    /// ChartBar - 0xf080 - ".fa-chart-bar"
    /// </summary>
    [Description(".fa-chart-bar")]
    ChartBar = 0xf080,

    /// <summary>
    /// CheckCircle - 0xf058 - ".fa-check-circle"
    /// </summary>
    [Description(".fa-check-circle")]
    CheckCircle = 0xf058,

    /// <summary>
    /// CheckSquare - 0xf14a - ".fa-check-square"
    /// </summary>
    [Description(".fa-check-square")]
    CheckSquare = 0xf14a,

    /// <summary>
    /// Circle - 0xf111 - ".fa-circle"
    /// </summary>
    [Description(".fa-circle")]
    Circle = 0xf111,

    /// <summary>
    /// Clipboard - 0xf328 - ".fa-clipboard"
    /// </summary>
    [Description(".fa-clipboard")]
    Clipboard = 0xf328,

    /// <summary>
    /// Clock - 0xf017 - ".fa-clock"
    /// </summary>
    [Description(".fa-clock")]
    Clock = 0xf017,

    /// <summary>
    /// Clone - 0xf24d - ".fa-clone"
    /// </summary>
    [Description(".fa-clone")]
    Clone = 0xf24d,

    /// <summary>
    /// ClosedCaptioning - 0xf20a - ".fa-closed-captioning"
    /// </summary>
    [Description(".fa-closed-captioning")]
    ClosedCaptioning = 0xf20a,

    /// <summary>
    /// Comment - 0xf075 - ".fa-comment"
    /// </summary>
    [Description(".fa-comment")]
    Comment = 0xf075,

    /// <summary>
    /// CommentAlt - 0xf27a - ".fa-comment-alt"
    /// </summary>
    [Description(".fa-comment-alt")]
    CommentAlt = 0xf27a,

    /// <summary>
    /// CommentDots - 0xf4ad - ".fa-comment-dots"
    /// </summary>
    [Description(".fa-comment-dots")]
    CommentDots = 0xf4ad,

    /// <summary>
    /// Comments - 0xf086 - ".fa-comments"
    /// </summary>
    [Description(".fa-comments")]
    Comments = 0xf086,

    /// <summary>
    /// Compass - 0xf14e - ".fa-compass"
    /// </summary>
    [Description(".fa-compass")]
    Compass = 0xf14e,

    /// <summary>
    /// Copy - 0xf0c5 - ".fa-copy"
    /// </summary>
    [Description(".fa-copy")]
    Copy = 0xf0c5,

    /// <summary>
    /// Copyright - 0xf1f9 - ".fa-copyright"
    /// </summary>
    [Description(".fa-copyright")]
    Copyright = 0xf1f9,

    /// <summary>
    /// CreditCard - 0xf09d - ".fa-credit-card"
    /// </summary>
    [Description(".fa-credit-card")]
    CreditCard = 0xf09d,

    /// <summary>
    /// Dizzy - 0xf567 - ".fa-dizzy"
    /// </summary>
    [Description(".fa-dizzy")]
    Dizzy = 0xf567,

    /// <summary>
    /// DotCircle - 0xf192 - ".fa-dot-circle"
    /// </summary>
    [Description(".fa-dot-circle")]
    DotCircle = 0xf192,

    /// <summary>
    /// Edit - 0xf044 - ".fa-edit"
    /// </summary>
    [Description(".fa-edit")]
    Edit = 0xf044,

    /// <summary>
    /// Envelope - 0xf0e0 - ".fa-envelope"
    /// </summary>
    [Description(".fa-envelope")]
    Envelope = 0xf0e0,

    /// <summary>
    /// EnvelopeOpen - 0xf2b6 - ".fa-envelope-open"
    /// </summary>
    [Description(".fa-envelope-open")]
    EnvelopeOpen = 0xf2b6,

    /// <summary>
    /// Eye - 0xf06e - ".fa-eye"
    /// </summary>
    [Description(".fa-eye")]
    Eye = 0xf06e,

    /// <summary>
    /// EyeSlash - 0xf070 - ".fa-eye-slash"
    /// </summary>
    [Description(".fa-eye-slash")]
    EyeSlash = 0xf070,

    /// <summary>
    /// File - 0xf15b - ".fa-file"
    /// </summary>
    [Description(".fa-file")]
    File = 0xf15b,

    /// <summary>
    /// FileAlt - 0xf15c - ".fa-file-alt"
    /// </summary>
    [Description(".fa-file-alt")]
    FileAlt = 0xf15c,

    /// <summary>
    /// FileArchive - 0xf1c6 - ".fa-file-archive"
    /// </summary>
    [Description(".fa-file-archive")]
    FileArchive = 0xf1c6,

    /// <summary>
    /// FileAudio - 0xf1c7 - ".fa-file-audio"
    /// </summary>
    [Description(".fa-file-audio")]
    FileAudio = 0xf1c7,

    /// <summary>
    /// FileCode - 0xf1c9 - ".fa-file-code"
    /// </summary>
    [Description(".fa-file-code")]
    FileCode = 0xf1c9,

    /// <summary>
    /// FileExcel - 0xf1c3 - ".fa-file-excel"
    /// </summary>
    [Description(".fa-file-excel")]
    FileExcel = 0xf1c3,

    /// <summary>
    /// FileImage - 0xf1c5 - ".fa-file-image"
    /// </summary>
    [Description(".fa-file-image")]
    FileImage = 0xf1c5,

    /// <summary>
    /// FilePdf - 0xf1c1 - ".fa-file-pdf"
    /// </summary>
    [Description(".fa-file-pdf")]
    FilePdf = 0xf1c1,

    /// <summary>
    /// FilePowerpoint - 0xf1c4 - ".fa-file-powerpoint"
    /// </summary>
    [Description(".fa-file-powerpoint")]
    FilePowerpoint = 0xf1c4,

    /// <summary>
    /// FileVideo - 0xf1c8 - ".fa-file-video"
    /// </summary>
    [Description(".fa-file-video")]
    FileVideo = 0xf1c8,

    /// <summary>
    /// FileWord - 0xf1c2 - ".fa-file-word"
    /// </summary>
    [Description(".fa-file-word")]
    FileWord = 0xf1c2,

    /// <summary>
    /// Flag - 0xf024 - ".fa-flag"
    /// </summary>
    [Description(".fa-flag")]
    Flag = 0xf024,

    /// <summary>
    /// Flushed - 0xf579 - ".fa-flushed"
    /// </summary>
    [Description(".fa-flushed")]
    Flushed = 0xf579,

    /// <summary>
    /// Folder - 0xf07b - ".fa-folder"
    /// </summary>
    [Description(".fa-folder")]
    Folder = 0xf07b,

    /// <summary>
    /// FolderOpen - 0xf07c - ".fa-folder-open"
    /// </summary>
    [Description(".fa-folder-open")]
    FolderOpen = 0xf07c,

    /// <summary>
    /// Frown - 0xf119 - ".fa-frown"
    /// </summary>
    [Description(".fa-frown")]
    Frown = 0xf119,

    /// <summary>
    /// FrownOpen - 0xf57a - ".fa-frown-open"
    /// </summary>
    [Description(".fa-frown-open")]
    FrownOpen = 0xf57a,

    /// <summary>
    /// Futbol - 0xf1e3 - ".fa-futbol"
    /// </summary>
    [Description(".fa-futbol")]
    Futbol = 0xf1e3,

    /// <summary>
    /// Gem - 0xf3a5 - ".fa-gem"
    /// </summary>
    [Description(".fa-gem")]
    Gem = 0xf3a5,

    /// <summary>
    /// Grimace - 0xf57f - ".fa-grimace"
    /// </summary>
    [Description(".fa-grimace")]
    Grimace = 0xf57f,

    /// <summary>
    /// Grin - 0xf580 - ".fa-grin"
    /// </summary>
    [Description(".fa-grin")]
    Grin = 0xf580,

    /// <summary>
    /// GrinAlt - 0xf581 - ".fa-grin-alt"
    /// </summary>
    [Description(".fa-grin-alt")]
    GrinAlt = 0xf581,

    /// <summary>
    /// GrinBeam - 0xf582 - ".fa-grin-beam"
    /// </summary>
    [Description(".fa-grin-beam")]
    GrinBeam = 0xf582,

    /// <summary>
    /// GrinBeamSweat - 0xf583 - ".fa-grin-beam-sweat"
    /// </summary>
    [Description(".fa-grin-beam-sweat")]
    GrinBeamSweat = 0xf583,

    /// <summary>
    /// GrinHearts - 0xf584 - ".fa-grin-hearts"
    /// </summary>
    [Description(".fa-grin-hearts")]
    GrinHearts = 0xf584,

    /// <summary>
    /// GrinSquint - 0xf585 - ".fa-grin-squint"
    /// </summary>
    [Description(".fa-grin-squint")]
    GrinSquint = 0xf585,

    /// <summary>
    /// GrinSquintTears - 0xf586 - ".fa-grin-squint-tears"
    /// </summary>
    [Description(".fa-grin-squint-tears")]
    GrinSquintTears = 0xf586,

    /// <summary>
    /// GrinStars - 0xf587 - ".fa-grin-stars"
    /// </summary>
    [Description(".fa-grin-stars")]
    GrinStars = 0xf587,

    /// <summary>
    /// GrinTears - 0xf588 - ".fa-grin-tears"
    /// </summary>
    [Description(".fa-grin-tears")]
    GrinTears = 0xf588,

    /// <summary>
    /// GrinTongue - 0xf589 - ".fa-grin-tongue"
    /// </summary>
    [Description(".fa-grin-tongue")]
    GrinTongue = 0xf589,

    /// <summary>
    /// GrinTongueSquint - 0xf58a - ".fa-grin-tongue-squint"
    /// </summary>
    [Description(".fa-grin-tongue-squint")]
    GrinTongueSquint = 0xf58a,

    /// <summary>
    /// GrinTongueWink - 0xf58b - ".fa-grin-tongue-wink"
    /// </summary>
    [Description(".fa-grin-tongue-wink")]
    GrinTongueWink = 0xf58b,

    /// <summary>
    /// GrinWink - 0xf58c - ".fa-grin-wink"
    /// </summary>
    [Description(".fa-grin-wink")]
    GrinWink = 0xf58c,

    /// <summary>
    /// HandLizard - 0xf258 - ".fa-hand-lizard"
    /// </summary>
    [Description(".fa-hand-lizard")]
    HandLizard = 0xf258,

    /// <summary>
    /// HandPaper - 0xf256 - ".fa-hand-paper"
    /// </summary>
    [Description(".fa-hand-paper")]
    HandPaper = 0xf256,

    /// <summary>
    /// HandPeace - 0xf25b - ".fa-hand-peace"
    /// </summary>
    [Description(".fa-hand-peace")]
    HandPeace = 0xf25b,

    /// <summary>
    /// HandPointDown - 0xf0a7 - ".fa-hand-point-down"
    /// </summary>
    [Description(".fa-hand-point-down")]
    HandPointDown = 0xf0a7,

    /// <summary>
    /// HandPointLeft - 0xf0a5 - ".fa-hand-point-left"
    /// </summary>
    [Description(".fa-hand-point-left")]
    HandPointLeft = 0xf0a5,

    /// <summary>
    /// HandPointRight - 0xf0a4 - ".fa-hand-point-right"
    /// </summary>
    [Description(".fa-hand-point-right")]
    HandPointRight = 0xf0a4,

    /// <summary>
    /// HandPointUp - 0xf0a6 - ".fa-hand-point-up"
    /// </summary>
    [Description(".fa-hand-point-up")]
    HandPointUp = 0xf0a6,

    /// <summary>
    /// HandPointer - 0xf25a - ".fa-hand-pointer"
    /// </summary>
    [Description(".fa-hand-pointer")]
    HandPointer = 0xf25a,

    /// <summary>
    /// HandRock - 0xf255 - ".fa-hand-rock"
    /// </summary>
    [Description(".fa-hand-rock")]
    HandRock = 0xf255,

    /// <summary>
    /// HandScissors - 0xf257 - ".fa-hand-scissors"
    /// </summary>
    [Description(".fa-hand-scissors")]
    HandScissors = 0xf257,

    /// <summary>
    /// HandSpock - 0xf259 - ".fa-hand-spock"
    /// </summary>
    [Description(".fa-hand-spock")]
    HandSpock = 0xf259,

    /// <summary>
    /// Handshake - 0xf2b5 - ".fa-handshake"
    /// </summary>
    [Description(".fa-handshake")]
    Handshake = 0xf2b5,

    /// <summary>
    /// Hdd - 0xf0a0 - ".fa-hdd"
    /// </summary>
    [Description(".fa-hdd")]
    Hdd = 0xf0a0,

    /// <summary>
    /// Heart - 0xf004 - ".fa-heart"
    /// </summary>
    [Description(".fa-heart")]
    Heart = 0xf004,

    /// <summary>
    /// Hospital - 0xf0f8 - ".fa-hospital"
    /// </summary>
    [Description(".fa-hospital")]
    Hospital = 0xf0f8,

    /// <summary>
    /// Hourglass - 0xf254 - ".fa-hourglass"
    /// </summary>
    [Description(".fa-hourglass")]
    Hourglass = 0xf254,

    /// <summary>
    /// IdBadge - 0xf2c1 - ".fa-id-badge"
    /// </summary>
    [Description(".fa-id-badge")]
    IdBadge = 0xf2c1,

    /// <summary>
    /// IdCard - 0xf2c2 - ".fa-id-card"
    /// </summary>
    [Description(".fa-id-card")]
    IdCard = 0xf2c2,

    /// <summary>
    /// Image - 0xf03e - ".fa-image"
    /// </summary>
    [Description(".fa-image")]
    Image = 0xf03e,

    /// <summary>
    /// Images - 0xf302 - ".fa-images"
    /// </summary>
    [Description(".fa-images")]
    Images = 0xf302,

    /// <summary>
    /// Keyboard - 0xf11c - ".fa-keyboard"
    /// </summary>
    [Description(".fa-keyboard")]
    Keyboard = 0xf11c,

    /// <summary>
    /// Kiss - 0xf596 - ".fa-kiss"
    /// </summary>
    [Description(".fa-kiss")]
    Kiss = 0xf596,

    /// <summary>
    /// KissBeam - 0xf597 - ".fa-kiss-beam"
    /// </summary>
    [Description(".fa-kiss-beam")]
    KissBeam = 0xf597,

    /// <summary>
    /// KissWinkHeart - 0xf598 - ".fa-kiss-wink-heart"
    /// </summary>
    [Description(".fa-kiss-wink-heart")]
    KissWinkHeart = 0xf598,

    /// <summary>
    /// Laugh - 0xf599 - ".fa-laugh"
    /// </summary>
    [Description(".fa-laugh")]
    Laugh = 0xf599,

    /// <summary>
    /// LaughBeam - 0xf59a - ".fa-laugh-beam"
    /// </summary>
    [Description(".fa-laugh-beam")]
    LaughBeam = 0xf59a,

    /// <summary>
    /// LaughSquint - 0xf59b - ".fa-laugh-squint"
    /// </summary>
    [Description(".fa-laugh-squint")]
    LaughSquint = 0xf59b,

    /// <summary>
    /// LaughWink - 0xf59c - ".fa-laugh-wink"
    /// </summary>
    [Description(".fa-laugh-wink")]
    LaughWink = 0xf59c,

    /// <summary>
    /// Lemon - 0xf094 - ".fa-lemon"
    /// </summary>
    [Description(".fa-lemon")]
    Lemon = 0xf094,

    /// <summary>
    /// LifeRing - 0xf1cd - ".fa-life-ring"
    /// </summary>
    [Description(".fa-life-ring")]
    LifeRing = 0xf1cd,

    /// <summary>
    /// Lightbulb - 0xf0eb - ".fa-lightbulb"
    /// </summary>
    [Description(".fa-lightbulb")]
    Lightbulb = 0xf0eb,

    /// <summary>
    /// ListAlt - 0xf022 - ".fa-list-alt"
    /// </summary>
    [Description(".fa-list-alt")]
    ListAlt = 0xf022,

    /// <summary>
    /// Map - 0xf279 - ".fa-map"
    /// </summary>
    [Description(".fa-map")]
    Map = 0xf279,

    /// <summary>
    /// Meh - 0xf11a - ".fa-meh"
    /// </summary>
    [Description(".fa-meh")]
    Meh = 0xf11a,

    /// <summary>
    /// MehBlank - 0xf5a4 - ".fa-meh-blank"
    /// </summary>
    [Description(".fa-meh-blank")]
    MehBlank = 0xf5a4,

    /// <summary>
    /// MehRollingEyes - 0xf5a5 - ".fa-meh-rolling-eyes"
    /// </summary>
    [Description(".fa-meh-rolling-eyes")]
    MehRollingEyes = 0xf5a5,

    /// <summary>
    /// MinusSquare - 0xf146 - ".fa-minus-square"
    /// </summary>
    [Description(".fa-minus-square")]
    MinusSquare = 0xf146,

    /// <summary>
    /// MoneyBillAlt - 0xf3d1 - ".fa-money-bill-alt"
    /// </summary>
    [Description(".fa-money-bill-alt")]
    MoneyBillAlt = 0xf3d1,

    /// <summary>
    /// Moon - 0xf186 - ".fa-moon"
    /// </summary>
    [Description(".fa-moon")]
    Moon = 0xf186,

    /// <summary>
    /// Newspaper - 0xf1ea - ".fa-newspaper"
    /// </summary>
    [Description(".fa-newspaper")]
    Newspaper = 0xf1ea,

    /// <summary>
    /// ObjectGroup - 0xf247 - ".fa-object-group"
    /// </summary>
    [Description(".fa-object-group")]
    ObjectGroup = 0xf247,

    /// <summary>
    /// ObjectUngroup - 0xf248 - ".fa-object-ungroup"
    /// </summary>
    [Description(".fa-object-ungroup")]
    ObjectUngroup = 0xf248,

    /// <summary>
    /// PaperPlane - 0xf1d8 - ".fa-paper-plane"
    /// </summary>
    [Description(".fa-paper-plane")]
    PaperPlane = 0xf1d8,

    /// <summary>
    /// PauseCircle - 0xf28b - ".fa-pause-circle"
    /// </summary>
    [Description(".fa-pause-circle")]
    PauseCircle = 0xf28b,

    /// <summary>
    /// PlayCircle - 0xf144 - ".fa-play-circle"
    /// </summary>
    [Description(".fa-play-circle")]
    PlayCircle = 0xf144,

    /// <summary>
    /// PlusSquare - 0xf0fe - ".fa-plus-square"
    /// </summary>
    [Description(".fa-plus-square")]
    PlusSquare = 0xf0fe,

    /// <summary>
    /// QuestionCircle - 0xf059 - ".fa-question-circle"
    /// </summary>
    [Description(".fa-question-circle")]
    QuestionCircle = 0xf059,

    /// <summary>
    /// Registered - 0xf25d - ".fa-registered"
    /// </summary>
    [Description(".fa-registered")]
    Registered = 0xf25d,

    /// <summary>
    /// SadCry - 0xf5b3 - ".fa-sad-cry"
    /// </summary>
    [Description(".fa-sad-cry")]
    SadCry = 0xf5b3,

    /// <summary>
    /// SadTear - 0xf5b4 - ".fa-sad-tear"
    /// </summary>
    [Description(".fa-sad-tear")]
    SadTear = 0xf5b4,

    /// <summary>
    /// Save - 0xf0c7 - ".fa-save"
    /// </summary>
    [Description(".fa-save")]
    Save = 0xf0c7,

    /// <summary>
    /// ShareSquare - 0xf14d - ".fa-share-square"
    /// </summary>
    [Description(".fa-share-square")]
    ShareSquare = 0xf14d,

    /// <summary>
    /// Smile - 0xf118 - ".fa-smile"
    /// </summary>
    [Description(".fa-smile")]
    Smile = 0xf118,

    /// <summary>
    /// SmileBeam - 0xf5b8 - ".fa-smile-beam"
    /// </summary>
    [Description(".fa-smile-beam")]
    SmileBeam = 0xf5b8,

    /// <summary>
    /// SmileWink - 0xf4da - ".fa-smile-wink"
    /// </summary>
    [Description(".fa-smile-wink")]
    SmileWink = 0xf4da,

    /// <summary>
    /// Snowflake - 0xf2dc - ".fa-snowflake"
    /// </summary>
    [Description(".fa-snowflake")]
    Snowflake = 0xf2dc,

    /// <summary>
    /// Square - 0xf0c8 - ".fa-square"
    /// </summary>
    [Description(".fa-square")]
    Square = 0xf0c8,

    /// <summary>
    /// Star - 0xf005 - ".fa-star"
    /// </summary>
    [Description(".fa-star")]
    Star = 0xf005,

    /// <summary>
    /// StarHalf - 0xf089 - ".fa-star-half"
    /// </summary>
    [Description(".fa-star-half")]
    StarHalf = 0xf089,

    /// <summary>
    /// StickyNote - 0xf249 - ".fa-sticky-note"
    /// </summary>
    [Description(".fa-sticky-note")]
    StickyNote = 0xf249,

    /// <summary>
    /// StopCircle - 0xf28d - ".fa-stop-circle"
    /// </summary>
    [Description(".fa-stop-circle")]
    StopCircle = 0xf28d,

    /// <summary>
    /// Sun - 0xf185 - ".fa-sun"
    /// </summary>
    [Description(".fa-sun")]
    Sun = 0xf185,

    /// <summary>
    /// Surprise - 0xf5c2 - ".fa-surprise"
    /// </summary>
    [Description(".fa-surprise")]
    Surprise = 0xf5c2,

    /// <summary>
    /// ThumbsDown - 0xf165 - ".fa-thumbs-down"
    /// </summary>
    [Description(".fa-thumbs-down")]
    ThumbsDown = 0xf165,

    /// <summary>
    /// ThumbsUp - 0xf164 - ".fa-thumbs-up"
    /// </summary>
    [Description(".fa-thumbs-up")]
    ThumbsUp = 0xf164,

    /// <summary>
    /// TimesCircle - 0xf057 - ".fa-times-circle"
    /// </summary>
    [Description(".fa-times-circle")]
    TimesCircle = 0xf057,

    /// <summary>
    /// Tired - 0xf5c8 - ".fa-tired"
    /// </summary>
    [Description(".fa-tired")]
    Tired = 0xf5c8,

    /// <summary>
    /// TrashAlt - 0xf2ed - ".fa-trash-alt"
    /// </summary>
    [Description(".fa-trash-alt")]
    TrashAlt = 0xf2ed,

    /// <summary>
    /// User - 0xf007 - ".fa-user"
    /// </summary>
    [Description(".fa-user")]
    User = 0xf007,

    /// <summary>
    /// UserCircle - 0xf2bd - ".fa-user-circle"
    /// </summary>
    [Description(".fa-user-circle")]
    UserCircle = 0xf2bd,

    /// <summary>
    /// WindowClose - 0xf410 - ".fa-window-close"
    /// </summary>
    [Description(".fa-window-close")]
    WindowClose = 0xf410,

    /// <summary>
    /// WindowMaximize - 0xf2d0 - ".fa-window-maximize"
    /// </summary>
    [Description(".fa-window-maximize")]
    WindowMaximize = 0xf2d0,

    /// <summary>
    /// WindowMinimize - 0xf2d1 - ".fa-window-minimize"
    /// </summary>
    [Description(".fa-window-minimize")]
    WindowMinimize = 0xf2d1,

    /// <summary>
    /// WindowRestore - 0xf2d2 - ".fa-window-restore"
    /// </summary>
    [Description(".fa-window-restore")]
    WindowRestore = 0xf2d2
}