//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool: Atc.Wpf.Generator.FontIconResources
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Atc.Wpf.FontIcons;

/// <summary>
/// Enumeration: FontAwesomeRegular7Type
/// </summary>
public enum FontAwesomeRegular7Type
{
    /// <summary>
    /// Default None
    /// </summary>
    None = 0x0,

    /// <summary>
    /// AddressBook - 0xf2b9 - ".fa-address-book"
    /// </summary>
    [Description(".fa-address-book")]
    AddressBook = 0xf2b9,

    /// <summary>
    /// AddressCard - 0xf2bb - ".fa-address-card"
    /// </summary>
    [Description(".fa-address-card")]
    AddressCard = 0xf2bb,

    /// <summary>
    /// AlarmClock - 0xf34e - ".fa-alarm-clock"
    /// </summary>
    [Description(".fa-alarm-clock")]
    AlarmClock = 0xf34e,

    /// <summary>
    /// Angry - 0xf556 - ".fa-angry"
    /// </summary>
    [Description(".fa-angry")]
    Angry = 0xf556,

    /// <summary>
    /// ArrowAltCircleDown - 0xf358 - ".fa-arrow-alt-circle-down"
    /// </summary>
    [Description(".fa-arrow-alt-circle-down")]
    ArrowAltCircleDown = 0xf358,

    /// <summary>
    /// ArrowAltCircleLeft - 0xf359 - ".fa-arrow-alt-circle-left"
    /// </summary>
    [Description(".fa-arrow-alt-circle-left")]
    ArrowAltCircleLeft = 0xf359,

    /// <summary>
    /// ArrowAltCircleRight - 0xf35a - ".fa-arrow-alt-circle-right"
    /// </summary>
    [Description(".fa-arrow-alt-circle-right")]
    ArrowAltCircleRight = 0xf35a,

    /// <summary>
    /// ArrowAltCircleUp - 0xf35b - ".fa-arrow-alt-circle-up"
    /// </summary>
    [Description(".fa-arrow-alt-circle-up")]
    ArrowAltCircleUp = 0xf35b,

    /// <summary>
    /// BarChart - 0xf080 - ".fa-bar-chart"
    /// </summary>
    [Description(".fa-bar-chart")]
    BarChart = 0xf080,

    /// <summary>
    /// Bell - 0xf0f3 - ".fa-bell"
    /// </summary>
    [Description(".fa-bell")]
    Bell = 0xf0f3,

    /// <summary>
    /// BellSlash - 0xf1f6 - ".fa-bell-slash"
    /// </summary>
    [Description(".fa-bell-slash")]
    BellSlash = 0xf1f6,

    /// <summary>
    /// Bookmark - 0xf02e - ".fa-bookmark"
    /// </summary>
    [Description(".fa-bookmark")]
    Bookmark = 0xf02e,

    /// <summary>
    /// Building - 0xf1ad - ".fa-building"
    /// </summary>
    [Description(".fa-building")]
    Building = 0xf1ad,

    /// <summary>
    /// Calendar - 0xf133 - ".fa-calendar"
    /// </summary>
    [Description(".fa-calendar")]
    Calendar = 0xf133,

    /// <summary>
    /// CalendarAlt - 0xf073 - ".fa-calendar-alt"
    /// </summary>
    [Description(".fa-calendar-alt")]
    CalendarAlt = 0xf073,

    /// <summary>
    /// CalendarCheck - 0xf274 - ".fa-calendar-check"
    /// </summary>
    [Description(".fa-calendar-check")]
    CalendarCheck = 0xf274,

    /// <summary>
    /// CalendarDays - 0xf073 - ".fa-calendar-days"
    /// </summary>
    [Description(".fa-calendar-days")]
    CalendarDays = 0xf073,

    /// <summary>
    /// CalendarMinus - 0xf272 - ".fa-calendar-minus"
    /// </summary>
    [Description(".fa-calendar-minus")]
    CalendarMinus = 0xf272,

    /// <summary>
    /// CalendarPlus - 0xf271 - ".fa-calendar-plus"
    /// </summary>
    [Description(".fa-calendar-plus")]
    CalendarPlus = 0xf271,

    /// <summary>
    /// CalendarTimes - 0xf273 - ".fa-calendar-times"
    /// </summary>
    [Description(".fa-calendar-times")]
    CalendarTimes = 0xf273,

    /// <summary>
    /// CalendarXmark - 0xf273 - ".fa-calendar-xmark"
    /// </summary>
    [Description(".fa-calendar-xmark")]
    CalendarXmark = 0xf273,

    /// <summary>
    /// Camera - 0xf030 - ".fa-camera"
    /// </summary>
    [Description(".fa-camera")]
    Camera = 0xf030,

    /// <summary>
    /// CameraAlt - 0xf030 - ".fa-camera-alt"
    /// </summary>
    [Description(".fa-camera-alt")]
    CameraAlt = 0xf030,

    /// <summary>
    /// CaretSquareDown - 0xf150 - ".fa-caret-square-down"
    /// </summary>
    [Description(".fa-caret-square-down")]
    CaretSquareDown = 0xf150,

    /// <summary>
    /// CaretSquareLeft - 0xf191 - ".fa-caret-square-left"
    /// </summary>
    [Description(".fa-caret-square-left")]
    CaretSquareLeft = 0xf191,

    /// <summary>
    /// CaretSquareRight - 0xf152 - ".fa-caret-square-right"
    /// </summary>
    [Description(".fa-caret-square-right")]
    CaretSquareRight = 0xf152,

    /// <summary>
    /// CaretSquareUp - 0xf151 - ".fa-caret-square-up"
    /// </summary>
    [Description(".fa-caret-square-up")]
    CaretSquareUp = 0xf151,

    /// <summary>
    /// ChartBar - 0xf080 - ".fa-chart-bar"
    /// </summary>
    [Description(".fa-chart-bar")]
    ChartBar = 0xf080,

    /// <summary>
    /// CheckCircle - 0xf058 - ".fa-check-circle"
    /// </summary>
    [Description(".fa-check-circle")]
    CheckCircle = 0xf058,

    /// <summary>
    /// CheckSquare - 0xf14a - ".fa-check-square"
    /// </summary>
    [Description(".fa-check-square")]
    CheckSquare = 0xf14a,

    /// <summary>
    /// ChessBishop - 0xf43a - ".fa-chess-bishop"
    /// </summary>
    [Description(".fa-chess-bishop")]
    ChessBishop = 0xf43a,

    /// <summary>
    /// ChessKing - 0xf43f - ".fa-chess-king"
    /// </summary>
    [Description(".fa-chess-king")]
    ChessKing = 0xf43f,

    /// <summary>
    /// ChessKnight - 0xf441 - ".fa-chess-knight"
    /// </summary>
    [Description(".fa-chess-knight")]
    ChessKnight = 0xf441,

    /// <summary>
    /// ChessPawn - 0xf443 - ".fa-chess-pawn"
    /// </summary>
    [Description(".fa-chess-pawn")]
    ChessPawn = 0xf443,

    /// <summary>
    /// ChessQueen - 0xf445 - ".fa-chess-queen"
    /// </summary>
    [Description(".fa-chess-queen")]
    ChessQueen = 0xf445,

    /// <summary>
    /// ChessRook - 0xf447 - ".fa-chess-rook"
    /// </summary>
    [Description(".fa-chess-rook")]
    ChessRook = 0xf447,

    /// <summary>
    /// Circle - 0xf111 - ".fa-circle"
    /// </summary>
    [Description(".fa-circle")]
    Circle = 0xf111,

    /// <summary>
    /// CircleCheck - 0xf058 - ".fa-circle-check"
    /// </summary>
    [Description(".fa-circle-check")]
    CircleCheck = 0xf058,

    /// <summary>
    /// CircleDot - 0xf192 - ".fa-circle-dot"
    /// </summary>
    [Description(".fa-circle-dot")]
    CircleDot = 0xf192,

    /// <summary>
    /// CircleDown - 0xf358 - ".fa-circle-down"
    /// </summary>
    [Description(".fa-circle-down")]
    CircleDown = 0xf358,

    /// <summary>
    /// CircleLeft - 0xf359 - ".fa-circle-left"
    /// </summary>
    [Description(".fa-circle-left")]
    CircleLeft = 0xf359,

    /// <summary>
    /// CirclePause - 0xf28b - ".fa-circle-pause"
    /// </summary>
    [Description(".fa-circle-pause")]
    CirclePause = 0xf28b,

    /// <summary>
    /// CirclePlay - 0xf144 - ".fa-circle-play"
    /// </summary>
    [Description(".fa-circle-play")]
    CirclePlay = 0xf144,

    /// <summary>
    /// CircleQuestion - 0xf059 - ".fa-circle-question"
    /// </summary>
    [Description(".fa-circle-question")]
    CircleQuestion = 0xf059,

    /// <summary>
    /// CircleRight - 0xf35a - ".fa-circle-right"
    /// </summary>
    [Description(".fa-circle-right")]
    CircleRight = 0xf35a,

    /// <summary>
    /// CircleStop - 0xf28d - ".fa-circle-stop"
    /// </summary>
    [Description(".fa-circle-stop")]
    CircleStop = 0xf28d,

    /// <summary>
    /// CircleUp - 0xf35b - ".fa-circle-up"
    /// </summary>
    [Description(".fa-circle-up")]
    CircleUp = 0xf35b,

    /// <summary>
    /// CircleUser - 0xf2bd - ".fa-circle-user"
    /// </summary>
    [Description(".fa-circle-user")]
    CircleUser = 0xf2bd,

    /// <summary>
    /// CircleXmark - 0xf057 - ".fa-circle-xmark"
    /// </summary>
    [Description(".fa-circle-xmark")]
    CircleXmark = 0xf057,

    /// <summary>
    /// Clipboard - 0xf328 - ".fa-clipboard"
    /// </summary>
    [Description(".fa-clipboard")]
    Clipboard = 0xf328,

    /// <summary>
    /// Clock - 0xf017 - ".fa-clock"
    /// </summary>
    [Description(".fa-clock")]
    Clock = 0xf017,

    /// <summary>
    /// ClockFour - 0xf017 - ".fa-clock-four"
    /// </summary>
    [Description(".fa-clock-four")]
    ClockFour = 0xf017,

    /// <summary>
    /// Clone - 0xf24d - ".fa-clone"
    /// </summary>
    [Description(".fa-clone")]
    Clone = 0xf24d,

    /// <summary>
    /// ClosedCaptioning - 0xf20a - ".fa-closed-captioning"
    /// </summary>
    [Description(".fa-closed-captioning")]
    ClosedCaptioning = 0xf20a,

    /// <summary>
    /// Cloud - 0xf0c2 - ".fa-cloud"
    /// </summary>
    [Description(".fa-cloud")]
    Cloud = 0xf0c2,

    /// <summary>
    /// Comment - 0xf075 - ".fa-comment"
    /// </summary>
    [Description(".fa-comment")]
    Comment = 0xf075,

    /// <summary>
    /// CommentAlt - 0xf27a - ".fa-comment-alt"
    /// </summary>
    [Description(".fa-comment-alt")]
    CommentAlt = 0xf27a,

    /// <summary>
    /// CommentDots - 0xf4ad - ".fa-comment-dots"
    /// </summary>
    [Description(".fa-comment-dots")]
    CommentDots = 0xf4ad,

    /// <summary>
    /// Commenting - 0xf4ad - ".fa-commenting"
    /// </summary>
    [Description(".fa-commenting")]
    Commenting = 0xf4ad,

    /// <summary>
    /// Comments - 0xf086 - ".fa-comments"
    /// </summary>
    [Description(".fa-comments")]
    Comments = 0xf086,

    /// <summary>
    /// Compass - 0xf14e - ".fa-compass"
    /// </summary>
    [Description(".fa-compass")]
    Compass = 0xf14e,

    /// <summary>
    /// ContactBook - 0xf2b9 - ".fa-contact-book"
    /// </summary>
    [Description(".fa-contact-book")]
    ContactBook = 0xf2b9,

    /// <summary>
    /// ContactCard - 0xf2bb - ".fa-contact-card"
    /// </summary>
    [Description(".fa-contact-card")]
    ContactCard = 0xf2bb,

    /// <summary>
    /// Copy - 0xf0c5 - ".fa-copy"
    /// </summary>
    [Description(".fa-copy")]
    Copy = 0xf0c5,

    /// <summary>
    /// Copyright - 0xf1f9 - ".fa-copyright"
    /// </summary>
    [Description(".fa-copyright")]
    Copyright = 0xf1f9,

    /// <summary>
    /// CreditCard - 0xf09d - ".fa-credit-card"
    /// </summary>
    [Description(".fa-credit-card")]
    CreditCard = 0xf09d,

    /// <summary>
    /// CreditCardAlt - 0xf09d - ".fa-credit-card-alt"
    /// </summary>
    [Description(".fa-credit-card-alt")]
    CreditCardAlt = 0xf09d,

    /// <summary>
    /// Dizzy - 0xf567 - ".fa-dizzy"
    /// </summary>
    [Description(".fa-dizzy")]
    Dizzy = 0xf567,

    /// <summary>
    /// DotCircle - 0xf192 - ".fa-dot-circle"
    /// </summary>
    [Description(".fa-dot-circle")]
    DotCircle = 0xf192,

    /// <summary>
    /// DriversLicense - 0xf2c2 - ".fa-drivers-license"
    /// </summary>
    [Description(".fa-drivers-license")]
    DriversLicense = 0xf2c2,

    /// <summary>
    /// Edit - 0xf044 - ".fa-edit"
    /// </summary>
    [Description(".fa-edit")]
    Edit = 0xf044,

    /// <summary>
    /// Envelope - 0xf0e0 - ".fa-envelope"
    /// </summary>
    [Description(".fa-envelope")]
    Envelope = 0xf0e0,

    /// <summary>
    /// EnvelopeOpen - 0xf2b6 - ".fa-envelope-open"
    /// </summary>
    [Description(".fa-envelope-open")]
    EnvelopeOpen = 0xf2b6,

    /// <summary>
    /// Eye - 0xf06e - ".fa-eye"
    /// </summary>
    [Description(".fa-eye")]
    Eye = 0xf06e,

    /// <summary>
    /// EyeSlash - 0xf070 - ".fa-eye-slash"
    /// </summary>
    [Description(".fa-eye-slash")]
    EyeSlash = 0xf070,

    /// <summary>
    /// FaceAngry - 0xf556 - ".fa-face-angry"
    /// </summary>
    [Description(".fa-face-angry")]
    FaceAngry = 0xf556,

    /// <summary>
    /// FaceDizzy - 0xf567 - ".fa-face-dizzy"
    /// </summary>
    [Description(".fa-face-dizzy")]
    FaceDizzy = 0xf567,

    /// <summary>
    /// FaceFlushed - 0xf579 - ".fa-face-flushed"
    /// </summary>
    [Description(".fa-face-flushed")]
    FaceFlushed = 0xf579,

    /// <summary>
    /// FaceFrown - 0xf119 - ".fa-face-frown"
    /// </summary>
    [Description(".fa-face-frown")]
    FaceFrown = 0xf119,

    /// <summary>
    /// FaceFrownOpen - 0xf57a - ".fa-face-frown-open"
    /// </summary>
    [Description(".fa-face-frown-open")]
    FaceFrownOpen = 0xf57a,

    /// <summary>
    /// FaceGrimace - 0xf57f - ".fa-face-grimace"
    /// </summary>
    [Description(".fa-face-grimace")]
    FaceGrimace = 0xf57f,

    /// <summary>
    /// FaceGrin - 0xf580 - ".fa-face-grin"
    /// </summary>
    [Description(".fa-face-grin")]
    FaceGrin = 0xf580,

    /// <summary>
    /// FaceGrinBeam - 0xf582 - ".fa-face-grin-beam"
    /// </summary>
    [Description(".fa-face-grin-beam")]
    FaceGrinBeam = 0xf582,

    /// <summary>
    /// FaceGrinBeamSweat - 0xf583 - ".fa-face-grin-beam-sweat"
    /// </summary>
    [Description(".fa-face-grin-beam-sweat")]
    FaceGrinBeamSweat = 0xf583,

    /// <summary>
    /// FaceGrinHearts - 0xf584 - ".fa-face-grin-hearts"
    /// </summary>
    [Description(".fa-face-grin-hearts")]
    FaceGrinHearts = 0xf584,

    /// <summary>
    /// FaceGrinSquint - 0xf585 - ".fa-face-grin-squint"
    /// </summary>
    [Description(".fa-face-grin-squint")]
    FaceGrinSquint = 0xf585,

    /// <summary>
    /// FaceGrinSquintTears - 0xf586 - ".fa-face-grin-squint-tears"
    /// </summary>
    [Description(".fa-face-grin-squint-tears")]
    FaceGrinSquintTears = 0xf586,

    /// <summary>
    /// FaceGrinStars - 0xf587 - ".fa-face-grin-stars"
    /// </summary>
    [Description(".fa-face-grin-stars")]
    FaceGrinStars = 0xf587,

    /// <summary>
    /// FaceGrinTears - 0xf588 - ".fa-face-grin-tears"
    /// </summary>
    [Description(".fa-face-grin-tears")]
    FaceGrinTears = 0xf588,

    /// <summary>
    /// FaceGrinTongue - 0xf589 - ".fa-face-grin-tongue"
    /// </summary>
    [Description(".fa-face-grin-tongue")]
    FaceGrinTongue = 0xf589,

    /// <summary>
    /// FaceGrinTongueSquint - 0xf58a - ".fa-face-grin-tongue-squint"
    /// </summary>
    [Description(".fa-face-grin-tongue-squint")]
    FaceGrinTongueSquint = 0xf58a,

    /// <summary>
    /// FaceGrinTongueWink - 0xf58b - ".fa-face-grin-tongue-wink"
    /// </summary>
    [Description(".fa-face-grin-tongue-wink")]
    FaceGrinTongueWink = 0xf58b,

    /// <summary>
    /// FaceGrinWide - 0xf581 - ".fa-face-grin-wide"
    /// </summary>
    [Description(".fa-face-grin-wide")]
    FaceGrinWide = 0xf581,

    /// <summary>
    /// FaceGrinWink - 0xf58c - ".fa-face-grin-wink"
    /// </summary>
    [Description(".fa-face-grin-wink")]
    FaceGrinWink = 0xf58c,

    /// <summary>
    /// FaceKiss - 0xf596 - ".fa-face-kiss"
    /// </summary>
    [Description(".fa-face-kiss")]
    FaceKiss = 0xf596,

    /// <summary>
    /// FaceKissBeam - 0xf597 - ".fa-face-kiss-beam"
    /// </summary>
    [Description(".fa-face-kiss-beam")]
    FaceKissBeam = 0xf597,

    /// <summary>
    /// FaceKissWinkHeart - 0xf598 - ".fa-face-kiss-wink-heart"
    /// </summary>
    [Description(".fa-face-kiss-wink-heart")]
    FaceKissWinkHeart = 0xf598,

    /// <summary>
    /// FaceLaugh - 0xf599 - ".fa-face-laugh"
    /// </summary>
    [Description(".fa-face-laugh")]
    FaceLaugh = 0xf599,

    /// <summary>
    /// FaceLaughBeam - 0xf59a - ".fa-face-laugh-beam"
    /// </summary>
    [Description(".fa-face-laugh-beam")]
    FaceLaughBeam = 0xf59a,

    /// <summary>
    /// FaceLaughSquint - 0xf59b - ".fa-face-laugh-squint"
    /// </summary>
    [Description(".fa-face-laugh-squint")]
    FaceLaughSquint = 0xf59b,

    /// <summary>
    /// FaceLaughWink - 0xf59c - ".fa-face-laugh-wink"
    /// </summary>
    [Description(".fa-face-laugh-wink")]
    FaceLaughWink = 0xf59c,

    /// <summary>
    /// FaceMeh - 0xf11a - ".fa-face-meh"
    /// </summary>
    [Description(".fa-face-meh")]
    FaceMeh = 0xf11a,

    /// <summary>
    /// FaceMehBlank - 0xf5a4 - ".fa-face-meh-blank"
    /// </summary>
    [Description(".fa-face-meh-blank")]
    FaceMehBlank = 0xf5a4,

    /// <summary>
    /// FaceRollingEyes - 0xf5a5 - ".fa-face-rolling-eyes"
    /// </summary>
    [Description(".fa-face-rolling-eyes")]
    FaceRollingEyes = 0xf5a5,

    /// <summary>
    /// FaceSadCry - 0xf5b3 - ".fa-face-sad-cry"
    /// </summary>
    [Description(".fa-face-sad-cry")]
    FaceSadCry = 0xf5b3,

    /// <summary>
    /// FaceSadTear - 0xf5b4 - ".fa-face-sad-tear"
    /// </summary>
    [Description(".fa-face-sad-tear")]
    FaceSadTear = 0xf5b4,

    /// <summary>
    /// FaceSmile - 0xf118 - ".fa-face-smile"
    /// </summary>
    [Description(".fa-face-smile")]
    FaceSmile = 0xf118,

    /// <summary>
    /// FaceSmileBeam - 0xf5b8 - ".fa-face-smile-beam"
    /// </summary>
    [Description(".fa-face-smile-beam")]
    FaceSmileBeam = 0xf5b8,

    /// <summary>
    /// FaceSmileWink - 0xf4da - ".fa-face-smile-wink"
    /// </summary>
    [Description(".fa-face-smile-wink")]
    FaceSmileWink = 0xf4da,

    /// <summary>
    /// FaceSurprise - 0xf5c2 - ".fa-face-surprise"
    /// </summary>
    [Description(".fa-face-surprise")]
    FaceSurprise = 0xf5c2,

    /// <summary>
    /// FaceTired - 0xf5c8 - ".fa-face-tired"
    /// </summary>
    [Description(".fa-face-tired")]
    FaceTired = 0xf5c8,

    /// <summary>
    /// File - 0xf15b - ".fa-file"
    /// </summary>
    [Description(".fa-file")]
    File = 0xf15b,

    /// <summary>
    /// FileAlt - 0xf15c - ".fa-file-alt"
    /// </summary>
    [Description(".fa-file-alt")]
    FileAlt = 0xf15c,

    /// <summary>
    /// FileArchive - 0xf1c6 - ".fa-file-archive"
    /// </summary>
    [Description(".fa-file-archive")]
    FileArchive = 0xf1c6,

    /// <summary>
    /// FileAudio - 0xf1c7 - ".fa-file-audio"
    /// </summary>
    [Description(".fa-file-audio")]
    FileAudio = 0xf1c7,

    /// <summary>
    /// FileClipboard - 0xf0ea - ".fa-file-clipboard"
    /// </summary>
    [Description(".fa-file-clipboard")]
    FileClipboard = 0xf0ea,

    /// <summary>
    /// FileCode - 0xf1c9 - ".fa-file-code"
    /// </summary>
    [Description(".fa-file-code")]
    FileCode = 0xf1c9,

    /// <summary>
    /// FileExcel - 0xf1c3 - ".fa-file-excel"
    /// </summary>
    [Description(".fa-file-excel")]
    FileExcel = 0xf1c3,

    /// <summary>
    /// FileImage - 0xf1c5 - ".fa-file-image"
    /// </summary>
    [Description(".fa-file-image")]
    FileImage = 0xf1c5,

    /// <summary>
    /// FileLines - 0xf15c - ".fa-file-lines"
    /// </summary>
    [Description(".fa-file-lines")]
    FileLines = 0xf15c,

    /// <summary>
    /// FilePdf - 0xf1c1 - ".fa-file-pdf"
    /// </summary>
    [Description(".fa-file-pdf")]
    FilePdf = 0xf1c1,

    /// <summary>
    /// FilePowerpoint - 0xf1c4 - ".fa-file-powerpoint"
    /// </summary>
    [Description(".fa-file-powerpoint")]
    FilePowerpoint = 0xf1c4,

    /// <summary>
    /// FileText - 0xf15c - ".fa-file-text"
    /// </summary>
    [Description(".fa-file-text")]
    FileText = 0xf15c,

    /// <summary>
    /// FileVideo - 0xf1c8 - ".fa-file-video"
    /// </summary>
    [Description(".fa-file-video")]
    FileVideo = 0xf1c8,

    /// <summary>
    /// FileWord - 0xf1c2 - ".fa-file-word"
    /// </summary>
    [Description(".fa-file-word")]
    FileWord = 0xf1c2,

    /// <summary>
    /// FileZipper - 0xf1c6 - ".fa-file-zipper"
    /// </summary>
    [Description(".fa-file-zipper")]
    FileZipper = 0xf1c6,

    /// <summary>
    /// Flag - 0xf024 - ".fa-flag"
    /// </summary>
    [Description(".fa-flag")]
    Flag = 0xf024,

    /// <summary>
    /// FloppyDisk - 0xf0c7 - ".fa-floppy-disk"
    /// </summary>
    [Description(".fa-floppy-disk")]
    FloppyDisk = 0xf0c7,

    /// <summary>
    /// Flushed - 0xf579 - ".fa-flushed"
    /// </summary>
    [Description(".fa-flushed")]
    Flushed = 0xf579,

    /// <summary>
    /// Folder - 0xf07b - ".fa-folder"
    /// </summary>
    [Description(".fa-folder")]
    Folder = 0xf07b,

    /// <summary>
    /// FolderBlank - 0xf07b - ".fa-folder-blank"
    /// </summary>
    [Description(".fa-folder-blank")]
    FolderBlank = 0xf07b,

    /// <summary>
    /// FolderClosed - 0xe185 - ".fa-folder-closed"
    /// </summary>
    [Description(".fa-folder-closed")]
    FolderClosed = 0xe185,

    /// <summary>
    /// FolderOpen - 0xf07c - ".fa-folder-open"
    /// </summary>
    [Description(".fa-folder-open")]
    FolderOpen = 0xf07c,

    /// <summary>
    /// FontAwesome - 0xf2b4 - ".fa-font-awesome"
    /// </summary>
    [Description(".fa-font-awesome")]
    FontAwesome = 0xf2b4,

    /// <summary>
    /// FontAwesomeFlag - 0xf2b4 - ".fa-font-awesome-flag"
    /// </summary>
    [Description(".fa-font-awesome-flag")]
    FontAwesomeFlag = 0xf2b4,

    /// <summary>
    /// FontAwesomeLogoFull - 0xf2b4 - ".fa-font-awesome-logo-full"
    /// </summary>
    [Description(".fa-font-awesome-logo-full")]
    FontAwesomeLogoFull = 0xf2b4,

    /// <summary>
    /// Frown - 0xf119 - ".fa-frown"
    /// </summary>
    [Description(".fa-frown")]
    Frown = 0xf119,

    /// <summary>
    /// FrownOpen - 0xf57a - ".fa-frown-open"
    /// </summary>
    [Description(".fa-frown-open")]
    FrownOpen = 0xf57a,

    /// <summary>
    /// Futbol - 0xf1e3 - ".fa-futbol"
    /// </summary>
    [Description(".fa-futbol")]
    Futbol = 0xf1e3,

    /// <summary>
    /// FutbolBall - 0xf1e3 - ".fa-futbol-ball"
    /// </summary>
    [Description(".fa-futbol-ball")]
    FutbolBall = 0xf1e3,

    /// <summary>
    /// Gem - 0xf3a5 - ".fa-gem"
    /// </summary>
    [Description(".fa-gem")]
    Gem = 0xf3a5,

    /// <summary>
    /// Grimace - 0xf57f - ".fa-grimace"
    /// </summary>
    [Description(".fa-grimace")]
    Grimace = 0xf57f,

    /// <summary>
    /// Grin - 0xf580 - ".fa-grin"
    /// </summary>
    [Description(".fa-grin")]
    Grin = 0xf580,

    /// <summary>
    /// GrinAlt - 0xf581 - ".fa-grin-alt"
    /// </summary>
    [Description(".fa-grin-alt")]
    GrinAlt = 0xf581,

    /// <summary>
    /// GrinBeam - 0xf582 - ".fa-grin-beam"
    /// </summary>
    [Description(".fa-grin-beam")]
    GrinBeam = 0xf582,

    /// <summary>
    /// GrinBeamSweat - 0xf583 - ".fa-grin-beam-sweat"
    /// </summary>
    [Description(".fa-grin-beam-sweat")]
    GrinBeamSweat = 0xf583,

    /// <summary>
    /// GrinHearts - 0xf584 - ".fa-grin-hearts"
    /// </summary>
    [Description(".fa-grin-hearts")]
    GrinHearts = 0xf584,

    /// <summary>
    /// GrinSquint - 0xf585 - ".fa-grin-squint"
    /// </summary>
    [Description(".fa-grin-squint")]
    GrinSquint = 0xf585,

    /// <summary>
    /// GrinSquintTears - 0xf586 - ".fa-grin-squint-tears"
    /// </summary>
    [Description(".fa-grin-squint-tears")]
    GrinSquintTears = 0xf586,

    /// <summary>
    /// GrinStars - 0xf587 - ".fa-grin-stars"
    /// </summary>
    [Description(".fa-grin-stars")]
    GrinStars = 0xf587,

    /// <summary>
    /// GrinTears - 0xf588 - ".fa-grin-tears"
    /// </summary>
    [Description(".fa-grin-tears")]
    GrinTears = 0xf588,

    /// <summary>
    /// GrinTongue - 0xf589 - ".fa-grin-tongue"
    /// </summary>
    [Description(".fa-grin-tongue")]
    GrinTongue = 0xf589,

    /// <summary>
    /// GrinTongueSquint - 0xf58a - ".fa-grin-tongue-squint"
    /// </summary>
    [Description(".fa-grin-tongue-squint")]
    GrinTongueSquint = 0xf58a,

    /// <summary>
    /// GrinTongueWink - 0xf58b - ".fa-grin-tongue-wink"
    /// </summary>
    [Description(".fa-grin-tongue-wink")]
    GrinTongueWink = 0xf58b,

    /// <summary>
    /// GrinWink - 0xf58c - ".fa-grin-wink"
    /// </summary>
    [Description(".fa-grin-wink")]
    GrinWink = 0xf58c,

    /// <summary>
    /// Hand - 0xf256 - ".fa-hand"
    /// </summary>
    [Description(".fa-hand")]
    Hand = 0xf256,

    /// <summary>
    /// HandBackFist - 0xf255 - ".fa-hand-back-fist"
    /// </summary>
    [Description(".fa-hand-back-fist")]
    HandBackFist = 0xf255,

    /// <summary>
    /// HandLizard - 0xf258 - ".fa-hand-lizard"
    /// </summary>
    [Description(".fa-hand-lizard")]
    HandLizard = 0xf258,

    /// <summary>
    /// HandPaper - 0xf256 - ".fa-hand-paper"
    /// </summary>
    [Description(".fa-hand-paper")]
    HandPaper = 0xf256,

    /// <summary>
    /// HandPeace - 0xf25b - ".fa-hand-peace"
    /// </summary>
    [Description(".fa-hand-peace")]
    HandPeace = 0xf25b,

    /// <summary>
    /// HandPointDown - 0xf0a7 - ".fa-hand-point-down"
    /// </summary>
    [Description(".fa-hand-point-down")]
    HandPointDown = 0xf0a7,

    /// <summary>
    /// HandPointLeft - 0xf0a5 - ".fa-hand-point-left"
    /// </summary>
    [Description(".fa-hand-point-left")]
    HandPointLeft = 0xf0a5,

    /// <summary>
    /// HandPointRight - 0xf0a4 - ".fa-hand-point-right"
    /// </summary>
    [Description(".fa-hand-point-right")]
    HandPointRight = 0xf0a4,

    /// <summary>
    /// HandPointUp - 0xf0a6 - ".fa-hand-point-up"
    /// </summary>
    [Description(".fa-hand-point-up")]
    HandPointUp = 0xf0a6,

    /// <summary>
    /// HandPointer - 0xf25a - ".fa-hand-pointer"
    /// </summary>
    [Description(".fa-hand-pointer")]
    HandPointer = 0xf25a,

    /// <summary>
    /// HandRock - 0xf255 - ".fa-hand-rock"
    /// </summary>
    [Description(".fa-hand-rock")]
    HandRock = 0xf255,

    /// <summary>
    /// HandScissors - 0xf257 - ".fa-hand-scissors"
    /// </summary>
    [Description(".fa-hand-scissors")]
    HandScissors = 0xf257,

    /// <summary>
    /// HandSpock - 0xf259 - ".fa-hand-spock"
    /// </summary>
    [Description(".fa-hand-spock")]
    HandSpock = 0xf259,

    /// <summary>
    /// Handshake - 0xf2b5 - ".fa-handshake"
    /// </summary>
    [Description(".fa-handshake")]
    Handshake = 0xf2b5,

    /// <summary>
    /// HandshakeAlt - 0xf2b5 - ".fa-handshake-alt"
    /// </summary>
    [Description(".fa-handshake-alt")]
    HandshakeAlt = 0xf2b5,

    /// <summary>
    /// HandshakeSimple - 0xf2b5 - ".fa-handshake-simple"
    /// </summary>
    [Description(".fa-handshake-simple")]
    HandshakeSimple = 0xf2b5,

    /// <summary>
    /// HardDrive - 0xf0a0 - ".fa-hard-drive"
    /// </summary>
    [Description(".fa-hard-drive")]
    HardDrive = 0xf0a0,

    /// <summary>
    /// Hdd - 0xf0a0 - ".fa-hdd"
    /// </summary>
    [Description(".fa-hdd")]
    Hdd = 0xf0a0,

    /// <summary>
    /// Headphones - 0xf025 - ".fa-headphones"
    /// </summary>
    [Description(".fa-headphones")]
    Headphones = 0xf025,

    /// <summary>
    /// HeadphonesAlt - 0xf025 - ".fa-headphones-alt"
    /// </summary>
    [Description(".fa-headphones-alt")]
    HeadphonesAlt = 0xf025,

    /// <summary>
    /// HeadphonesSimple - 0xf025 - ".fa-headphones-simple"
    /// </summary>
    [Description(".fa-headphones-simple")]
    HeadphonesSimple = 0xf025,

    /// <summary>
    /// Heart - 0xf004 - ".fa-heart"
    /// </summary>
    [Description(".fa-heart")]
    Heart = 0xf004,

    /// <summary>
    /// Home - 0xf015 - ".fa-home"
    /// </summary>
    [Description(".fa-home")]
    Home = 0xf015,

    /// <summary>
    /// HomeAlt - 0xf015 - ".fa-home-alt"
    /// </summary>
    [Description(".fa-home-alt")]
    HomeAlt = 0xf015,

    /// <summary>
    /// HomeLgAlt - 0xf015 - ".fa-home-lg-alt"
    /// </summary>
    [Description(".fa-home-lg-alt")]
    HomeLgAlt = 0xf015,

    /// <summary>
    /// Hospital - 0xf0f8 - ".fa-hospital"
    /// </summary>
    [Description(".fa-hospital")]
    Hospital = 0xf0f8,

    /// <summary>
    /// HospitalAlt - 0xf0f8 - ".fa-hospital-alt"
    /// </summary>
    [Description(".fa-hospital-alt")]
    HospitalAlt = 0xf0f8,

    /// <summary>
    /// HospitalWide - 0xf0f8 - ".fa-hospital-wide"
    /// </summary>
    [Description(".fa-hospital-wide")]
    HospitalWide = 0xf0f8,

    /// <summary>
    /// Hourglass - 0xf254 - ".fa-hourglass"
    /// </summary>
    [Description(".fa-hourglass")]
    Hourglass = 0xf254,

    /// <summary>
    /// Hourglass2 - 0xf252 - ".fa-hourglass-2"
    /// </summary>
    [Description(".fa-hourglass-2")]
    Hourglass2 = 0xf252,

    /// <summary>
    /// HourglassEmpty - 0xf254 - ".fa-hourglass-empty"
    /// </summary>
    [Description(".fa-hourglass-empty")]
    HourglassEmpty = 0xf254,

    /// <summary>
    /// HourglassHalf - 0xf252 - ".fa-hourglass-half"
    /// </summary>
    [Description(".fa-hourglass-half")]
    HourglassHalf = 0xf252,

    /// <summary>
    /// House - 0xf015 - ".fa-house"
    /// </summary>
    [Description(".fa-house")]
    House = 0xf015,

    /// <summary>
    /// IdBadge - 0xf2c1 - ".fa-id-badge"
    /// </summary>
    [Description(".fa-id-badge")]
    IdBadge = 0xf2c1,

    /// <summary>
    /// IdCard - 0xf2c2 - ".fa-id-card"
    /// </summary>
    [Description(".fa-id-card")]
    IdCard = 0xf2c2,

    /// <summary>
    /// Image - 0xf03e - ".fa-image"
    /// </summary>
    [Description(".fa-image")]
    Image = 0xf03e,

    /// <summary>
    /// Images - 0xf302 - ".fa-images"
    /// </summary>
    [Description(".fa-images")]
    Images = 0xf302,

    /// <summary>
    /// Keyboard - 0xf11c - ".fa-keyboard"
    /// </summary>
    [Description(".fa-keyboard")]
    Keyboard = 0xf11c,

    /// <summary>
    /// Kiss - 0xf596 - ".fa-kiss"
    /// </summary>
    [Description(".fa-kiss")]
    Kiss = 0xf596,

    /// <summary>
    /// KissBeam - 0xf597 - ".fa-kiss-beam"
    /// </summary>
    [Description(".fa-kiss-beam")]
    KissBeam = 0xf597,

    /// <summary>
    /// KissWinkHeart - 0xf598 - ".fa-kiss-wink-heart"
    /// </summary>
    [Description(".fa-kiss-wink-heart")]
    KissWinkHeart = 0xf598,

    /// <summary>
    /// Laugh - 0xf599 - ".fa-laugh"
    /// </summary>
    [Description(".fa-laugh")]
    Laugh = 0xf599,

    /// <summary>
    /// LaughBeam - 0xf59a - ".fa-laugh-beam"
    /// </summary>
    [Description(".fa-laugh-beam")]
    LaughBeam = 0xf59a,

    /// <summary>
    /// LaughSquint - 0xf59b - ".fa-laugh-squint"
    /// </summary>
    [Description(".fa-laugh-squint")]
    LaughSquint = 0xf59b,

    /// <summary>
    /// LaughWink - 0xf59c - ".fa-laugh-wink"
    /// </summary>
    [Description(".fa-laugh-wink")]
    LaughWink = 0xf59c,

    /// <summary>
    /// Lemon - 0xf094 - ".fa-lemon"
    /// </summary>
    [Description(".fa-lemon")]
    Lemon = 0xf094,

    /// <summary>
    /// LifeRing - 0xf1cd - ".fa-life-ring"
    /// </summary>
    [Description(".fa-life-ring")]
    LifeRing = 0xf1cd,

    /// <summary>
    /// Lightbulb - 0xf0eb - ".fa-lightbulb"
    /// </summary>
    [Description(".fa-lightbulb")]
    Lightbulb = 0xf0eb,

    /// <summary>
    /// ListAlt - 0xf022 - ".fa-list-alt"
    /// </summary>
    [Description(".fa-list-alt")]
    ListAlt = 0xf022,

    /// <summary>
    /// Map - 0xf279 - ".fa-map"
    /// </summary>
    [Description(".fa-map")]
    Map = 0xf279,

    /// <summary>
    /// Meh - 0xf11a - ".fa-meh"
    /// </summary>
    [Description(".fa-meh")]
    Meh = 0xf11a,

    /// <summary>
    /// MehBlank - 0xf5a4 - ".fa-meh-blank"
    /// </summary>
    [Description(".fa-meh-blank")]
    MehBlank = 0xf5a4,

    /// <summary>
    /// MehRollingEyes - 0xf5a5 - ".fa-meh-rolling-eyes"
    /// </summary>
    [Description(".fa-meh-rolling-eyes")]
    MehRollingEyes = 0xf5a5,

    /// <summary>
    /// Message - 0xf27a - ".fa-message"
    /// </summary>
    [Description(".fa-message")]
    Message = 0xf27a,

    /// <summary>
    /// MinusSquare - 0xf146 - ".fa-minus-square"
    /// </summary>
    [Description(".fa-minus-square")]
    MinusSquare = 0xf146,

    /// <summary>
    /// MoneyBill1 - 0xf3d1 - ".fa-money-bill-1"
    /// </summary>
    [Description(".fa-money-bill-1")]
    MoneyBill1 = 0xf3d1,

    /// <summary>
    /// MoneyBillAlt - 0xf3d1 - ".fa-money-bill-alt"
    /// </summary>
    [Description(".fa-money-bill-alt")]
    MoneyBillAlt = 0xf3d1,

    /// <summary>
    /// Moon - 0xf186 - ".fa-moon"
    /// </summary>
    [Description(".fa-moon")]
    Moon = 0xf186,

    /// <summary>
    /// Newspaper - 0xf1ea - ".fa-newspaper"
    /// </summary>
    [Description(".fa-newspaper")]
    Newspaper = 0xf1ea,

    /// <summary>
    /// NoteSticky - 0xf249 - ".fa-note-sticky"
    /// </summary>
    [Description(".fa-note-sticky")]
    NoteSticky = 0xf249,

    /// <summary>
    /// ObjectGroup - 0xf247 - ".fa-object-group"
    /// </summary>
    [Description(".fa-object-group")]
    ObjectGroup = 0xf247,

    /// <summary>
    /// ObjectUngroup - 0xf248 - ".fa-object-ungroup"
    /// </summary>
    [Description(".fa-object-ungroup")]
    ObjectUngroup = 0xf248,

    /// <summary>
    /// PaperPlane - 0xf1d8 - ".fa-paper-plane"
    /// </summary>
    [Description(".fa-paper-plane")]
    PaperPlane = 0xf1d8,

    /// <summary>
    /// Paste - 0xf0ea - ".fa-paste"
    /// </summary>
    [Description(".fa-paste")]
    Paste = 0xf0ea,

    /// <summary>
    /// PauseCircle - 0xf28b - ".fa-pause-circle"
    /// </summary>
    [Description(".fa-pause-circle")]
    PauseCircle = 0xf28b,

    /// <summary>
    /// PenToSquare - 0xf044 - ".fa-pen-to-square"
    /// </summary>
    [Description(".fa-pen-to-square")]
    PenToSquare = 0xf044,

    /// <summary>
    /// PlayCircle - 0xf144 - ".fa-play-circle"
    /// </summary>
    [Description(".fa-play-circle")]
    PlayCircle = 0xf144,

    /// <summary>
    /// PlusSquare - 0xf0fe - ".fa-plus-square"
    /// </summary>
    [Description(".fa-plus-square")]
    PlusSquare = 0xf0fe,

    /// <summary>
    /// QuestionCircle - 0xf059 - ".fa-question-circle"
    /// </summary>
    [Description(".fa-question-circle")]
    QuestionCircle = 0xf059,

    /// <summary>
    /// RectangleList - 0xf022 - ".fa-rectangle-list"
    /// </summary>
    [Description(".fa-rectangle-list")]
    RectangleList = 0xf022,

    /// <summary>
    /// RectangleTimes - 0xf410 - ".fa-rectangle-times"
    /// </summary>
    [Description(".fa-rectangle-times")]
    RectangleTimes = 0xf410,

    /// <summary>
    /// RectangleXmark - 0xf410 - ".fa-rectangle-xmark"
    /// </summary>
    [Description(".fa-rectangle-xmark")]
    RectangleXmark = 0xf410,

    /// <summary>
    /// Registered - 0xf25d - ".fa-registered"
    /// </summary>
    [Description(".fa-registered")]
    Registered = 0xf25d,

    /// <summary>
    /// SadCry - 0xf5b3 - ".fa-sad-cry"
    /// </summary>
    [Description(".fa-sad-cry")]
    SadCry = 0xf5b3,

    /// <summary>
    /// SadTear - 0xf5b4 - ".fa-sad-tear"
    /// </summary>
    [Description(".fa-sad-tear")]
    SadTear = 0xf5b4,

    /// <summary>
    /// Save - 0xf0c7 - ".fa-save"
    /// </summary>
    [Description(".fa-save")]
    Save = 0xf0c7,

    /// <summary>
    /// ShareFromSquare - 0xf14d - ".fa-share-from-square"
    /// </summary>
    [Description(".fa-share-from-square")]
    ShareFromSquare = 0xf14d,

    /// <summary>
    /// ShareSquare - 0xf14d - ".fa-share-square"
    /// </summary>
    [Description(".fa-share-square")]
    ShareSquare = 0xf14d,

    /// <summary>
    /// Smile - 0xf118 - ".fa-smile"
    /// </summary>
    [Description(".fa-smile")]
    Smile = 0xf118,

    /// <summary>
    /// SmileBeam - 0xf5b8 - ".fa-smile-beam"
    /// </summary>
    [Description(".fa-smile-beam")]
    SmileBeam = 0xf5b8,

    /// <summary>
    /// SmileWink - 0xf4da - ".fa-smile-wink"
    /// </summary>
    [Description(".fa-smile-wink")]
    SmileWink = 0xf4da,

    /// <summary>
    /// Snowflake - 0xf2dc - ".fa-snowflake"
    /// </summary>
    [Description(".fa-snowflake")]
    Snowflake = 0xf2dc,

    /// <summary>
    /// SoccerBall - 0xf1e3 - ".fa-soccer-ball"
    /// </summary>
    [Description(".fa-soccer-ball")]
    SoccerBall = 0xf1e3,

    /// <summary>
    /// Square - 0xf0c8 - ".fa-square"
    /// </summary>
    [Description(".fa-square")]
    Square = 0xf0c8,

    /// <summary>
    /// SquareCaretDown - 0xf150 - ".fa-square-caret-down"
    /// </summary>
    [Description(".fa-square-caret-down")]
    SquareCaretDown = 0xf150,

    /// <summary>
    /// SquareCaretLeft - 0xf191 - ".fa-square-caret-left"
    /// </summary>
    [Description(".fa-square-caret-left")]
    SquareCaretLeft = 0xf191,

    /// <summary>
    /// SquareCaretRight - 0xf152 - ".fa-square-caret-right"
    /// </summary>
    [Description(".fa-square-caret-right")]
    SquareCaretRight = 0xf152,

    /// <summary>
    /// SquareCaretUp - 0xf151 - ".fa-square-caret-up"
    /// </summary>
    [Description(".fa-square-caret-up")]
    SquareCaretUp = 0xf151,

    /// <summary>
    /// SquareCheck - 0xf14a - ".fa-square-check"
    /// </summary>
    [Description(".fa-square-check")]
    SquareCheck = 0xf14a,

    /// <summary>
    /// SquareFull - 0xf45c - ".fa-square-full"
    /// </summary>
    [Description(".fa-square-full")]
    SquareFull = 0xf45c,

    /// <summary>
    /// SquareMinus - 0xf146 - ".fa-square-minus"
    /// </summary>
    [Description(".fa-square-minus")]
    SquareMinus = 0xf146,

    /// <summary>
    /// SquarePlus - 0xf0fe - ".fa-square-plus"
    /// </summary>
    [Description(".fa-square-plus")]
    SquarePlus = 0xf0fe,

    /// <summary>
    /// Star - 0xf005 - ".fa-star"
    /// </summary>
    [Description(".fa-star")]
    Star = 0xf005,

    /// <summary>
    /// StarHalf - 0xf089 - ".fa-star-half"
    /// </summary>
    [Description(".fa-star-half")]
    StarHalf = 0xf089,

    /// <summary>
    /// StarHalfAlt - 0xf5c0 - ".fa-star-half-alt"
    /// </summary>
    [Description(".fa-star-half-alt")]
    StarHalfAlt = 0xf5c0,

    /// <summary>
    /// StarHalfStroke - 0xf5c0 - ".fa-star-half-stroke"
    /// </summary>
    [Description(".fa-star-half-stroke")]
    StarHalfStroke = 0xf5c0,

    /// <summary>
    /// StickyNote - 0xf249 - ".fa-sticky-note"
    /// </summary>
    [Description(".fa-sticky-note")]
    StickyNote = 0xf249,

    /// <summary>
    /// StopCircle - 0xf28d - ".fa-stop-circle"
    /// </summary>
    [Description(".fa-stop-circle")]
    StopCircle = 0xf28d,

    /// <summary>
    /// Sun - 0xf185 - ".fa-sun"
    /// </summary>
    [Description(".fa-sun")]
    Sun = 0xf185,

    /// <summary>
    /// Surprise - 0xf5c2 - ".fa-surprise"
    /// </summary>
    [Description(".fa-surprise")]
    Surprise = 0xf5c2,

    /// <summary>
    /// ThumbsDown - 0xf165 - ".fa-thumbs-down"
    /// </summary>
    [Description(".fa-thumbs-down")]
    ThumbsDown = 0xf165,

    /// <summary>
    /// ThumbsUp - 0xf164 - ".fa-thumbs-up"
    /// </summary>
    [Description(".fa-thumbs-up")]
    ThumbsUp = 0xf164,

    /// <summary>
    /// TimesCircle - 0xf057 - ".fa-times-circle"
    /// </summary>
    [Description(".fa-times-circle")]
    TimesCircle = 0xf057,

    /// <summary>
    /// TimesRectangle - 0xf410 - ".fa-times-rectangle"
    /// </summary>
    [Description(".fa-times-rectangle")]
    TimesRectangle = 0xf410,

    /// <summary>
    /// Tired - 0xf5c8 - ".fa-tired"
    /// </summary>
    [Description(".fa-tired")]
    Tired = 0xf5c8,

    /// <summary>
    /// TrashAlt - 0xf2ed - ".fa-trash-alt"
    /// </summary>
    [Description(".fa-trash-alt")]
    TrashAlt = 0xf2ed,

    /// <summary>
    /// TrashCan - 0xf2ed - ".fa-trash-can"
    /// </summary>
    [Description(".fa-trash-can")]
    TrashCan = 0xf2ed,

    /// <summary>
    /// Truck - 0xf0d1 - ".fa-truck"
    /// </summary>
    [Description(".fa-truck")]
    Truck = 0xf0d1,

    /// <summary>
    /// User - 0xf007 - ".fa-user"
    /// </summary>
    [Description(".fa-user")]
    User = 0xf007,

    /// <summary>
    /// UserAlt - 0xf007 - ".fa-user-alt"
    /// </summary>
    [Description(".fa-user-alt")]
    UserAlt = 0xf007,

    /// <summary>
    /// UserCircle - 0xf2bd - ".fa-user-circle"
    /// </summary>
    [Description(".fa-user-circle")]
    UserCircle = 0xf2bd,

    /// <summary>
    /// UserLarge - 0xf007 - ".fa-user-large"
    /// </summary>
    [Description(".fa-user-large")]
    UserLarge = 0xf007,

    /// <summary>
    /// Vcard - 0xf2bb - ".fa-vcard"
    /// </summary>
    [Description(".fa-vcard")]
    Vcard = 0xf2bb,

    /// <summary>
    /// WindowClose - 0xf410 - ".fa-window-close"
    /// </summary>
    [Description(".fa-window-close")]
    WindowClose = 0xf410,

    /// <summary>
    /// WindowMaximize - 0xf2d0 - ".fa-window-maximize"
    /// </summary>
    [Description(".fa-window-maximize")]
    WindowMaximize = 0xf2d0,

    /// <summary>
    /// WindowMinimize - 0xf2d1 - ".fa-window-minimize"
    /// </summary>
    [Description(".fa-window-minimize")]
    WindowMinimize = 0xf2d1,

    /// <summary>
    /// WindowRestore - 0xf2d2 - ".fa-window-restore"
    /// </summary>
    [Description(".fa-window-restore")]
    WindowRestore = 0xf2d2,

    /// <summary>
    /// XmarkCircle - 0xf057 - ".fa-xmark-circle"
    /// </summary>
    [Description(".fa-xmark-circle")]
    XmarkCircle = 0xf057,

    /// <summary>
    /// _0 - 0x30 - ".fa-0"
    /// </summary>
    [Description(".fa-0")]
    // ReSharper disable InconsistentNaming
    _0 = 0x30,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _1 - 0x31 - ".fa-1"
    /// </summary>
    [Description(".fa-1")]
    // ReSharper disable InconsistentNaming
    _1 = 0x31,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _2 - 0x32 - ".fa-2"
    /// </summary>
    [Description(".fa-2")]
    // ReSharper disable InconsistentNaming
    _2 = 0x32,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _3 - 0x33 - ".fa-3"
    /// </summary>
    [Description(".fa-3")]
    // ReSharper disable InconsistentNaming
    _3 = 0x33,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _4 - 0x34 - ".fa-4"
    /// </summary>
    [Description(".fa-4")]
    // ReSharper disable InconsistentNaming
    _4 = 0x34,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _5 - 0x35 - ".fa-5"
    /// </summary>
    [Description(".fa-5")]
    // ReSharper disable InconsistentNaming
    _5 = 0x35,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _6 - 0x36 - ".fa-6"
    /// </summary>
    [Description(".fa-6")]
    // ReSharper disable InconsistentNaming
    _6 = 0x36,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _7 - 0x37 - ".fa-7"
    /// </summary>
    [Description(".fa-7")]
    // ReSharper disable InconsistentNaming
    _7 = 0x37,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _8 - 0x38 - ".fa-8"
    /// </summary>
    [Description(".fa-8")]
    // ReSharper disable InconsistentNaming
    _8 = 0x38,
    // ReSharper restore InconsistentNaming

    /// <summary>
    /// _9 - 0x39 - ".fa-9"
    /// </summary>
    [Description(".fa-9")]
    // ReSharper disable InconsistentNaming
    _9 = 0x39
    // ReSharper restore InconsistentNaming
}