//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atc.Wpf.Components.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JsonViewer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JsonViewer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atc.Wpf.Components.Resources.JsonViewer", typeof(JsonViewer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not open the JSON string:
        ///{0}.
        /// </summary>
        public static string CouldNotOpenJsonStringFormat1 {
            get {
                return ResourceManager.GetString("CouldNotOpenJsonStringFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON format..
        /// </summary>
        public static string InvalidJsonFormat {
            get {
                return ResourceManager.GetString("InvalidJsonFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to array.
        /// </summary>
        public static string JsonTypeArray {
            get {
                return ResourceManager.GetString("JsonTypeArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        public static string JsonTypeBoolean {
            get {
                return ResourceManager.GetString("JsonTypeBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string JsonTypeDate {
            get {
                return ResourceManager.GetString("JsonTypeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guid.
        /// </summary>
        public static string JsonTypeGuid {
            get {
                return ResourceManager.GetString("JsonTypeGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        public static string JsonTypeNull {
            get {
                return ResourceManager.GetString("JsonTypeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string JsonTypeNumber {
            get {
                return ResourceManager.GetString("JsonTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string JsonTypeString {
            get {
                return ResourceManager.GetString("JsonTypeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri.
        /// </summary>
        public static string JsonTypeUri {
            get {
                return ResourceManager.GetString("JsonTypeUri", resourceCulture);
            }
        }
    }
}
