//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atc.Wpf.Hardware.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Miscellaneous {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Miscellaneous() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atc.Wpf.Hardware.Resources.Miscellaneous", typeof(Miscellaneous).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Input.
        /// </summary>
        public static string AudioInput {
            get {
                return ResourceManager.GetString("AudioInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio Output.
        /// </summary>
        public static string AudioOutput {
            get {
                return ResourceManager.GetString("AudioOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth Device.
        /// </summary>
        public static string BluetoothDevice {
            get {
                return ResourceManager.GetString("BluetoothDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device disconnected.
        /// </summary>
        public static string DeviceDisconnected {
            get {
                return ResourceManager.GetString("DeviceDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use by another application.
        /// </summary>
        public static string DeviceInUse {
            get {
                return ResourceManager.GetString("DeviceInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use by {0}.
        /// </summary>
        public static string DeviceInUseByFormat1 {
            get {
                return ResourceManager.GetString("DeviceInUseByFormat1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drive.
        /// </summary>
        public static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In use.
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Adapter.
        /// </summary>
        public static string NetworkAdapter {
            get {
                return ResourceManager.GetString("NetworkAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No devices found.
        /// </summary>
        public static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string Printer {
            get {
                return ResourceManager.GetString("Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        public static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select audio input….
        /// </summary>
        public static string SelectAudioInput {
            get {
                return ResourceManager.GetString("SelectAudioInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select audio output….
        /// </summary>
        public static string SelectAudioOutput {
            get {
                return ResourceManager.GetString("SelectAudioOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bluetooth device….
        /// </summary>
        public static string SelectBluetoothDevice {
            get {
                return ResourceManager.GetString("SelectBluetoothDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select camera….
        /// </summary>
        public static string SelectCamera {
            get {
                return ResourceManager.GetString("SelectCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select drive….
        /// </summary>
        public static string SelectDrive {
            get {
                return ResourceManager.GetString("SelectDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select network adapter….
        /// </summary>
        public static string SelectNetworkAdapter {
            get {
                return ResourceManager.GetString("SelectNetworkAdapter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select printer….
        /// </summary>
        public static string SelectPrinter {
            get {
                return ResourceManager.GetString("SelectPrinter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select process….
        /// </summary>
        public static string SelectProcess {
            get {
                return ResourceManager.GetString("SelectProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select serial port….
        /// </summary>
        public static string SelectSerialPort {
            get {
                return ResourceManager.GetString("SelectSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select time zone….
        /// </summary>
        public static string SelectTimeZone {
            get {
                return ResourceManager.GetString("SelectTimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select USB device….
        /// </summary>
        public static string SelectUsbDevice {
            get {
                return ResourceManager.GetString("SelectUsbDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select window….
        /// </summary>
        public static string SelectWindow {
            get {
                return ResourceManager.GetString("SelectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Port.
        /// </summary>
        public static string SerialPort {
            get {
                return ResourceManager.GetString("SerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test camera.
        /// </summary>
        public static string TestCamera {
            get {
                return ResourceManager.GetString("TestCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Zone.
        /// </summary>
        public static string TimeZone {
            get {
                return ResourceManager.GetString("TimeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Camera.
        /// </summary>
        public static string UsbCamera {
            get {
                return ResourceManager.GetString("UsbCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB Device.
        /// </summary>
        public static string UsbDevice {
            get {
                return ResourceManager.GetString("UsbDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
    }
}
