//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atc.Wpf.Hardware.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Miscellaneous {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Miscellaneous() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atc.Wpf.Hardware.Resources.Miscellaneous", typeof(Miscellaneous).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string SerialPort {
            get {
                return ResourceManager.GetString("SerialPort", resourceCulture);
            }
        }

        public static string UsbDevice {
            get {
                return ResourceManager.GetString("UsbDevice", resourceCulture);
            }
        }

        public static string UsbCamera {
            get {
                return ResourceManager.GetString("UsbCamera", resourceCulture);
            }
        }

        public static string SelectSerialPort {
            get {
                return ResourceManager.GetString("SelectSerialPort", resourceCulture);
            }
        }

        public static string SelectUsbDevice {
            get {
                return ResourceManager.GetString("SelectUsbDevice", resourceCulture);
            }
        }

        public static string SelectCamera {
            get {
                return ResourceManager.GetString("SelectCamera", resourceCulture);
            }
        }

        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }

        public static string NoDevicesFound {
            get {
                return ResourceManager.GetString("NoDevicesFound", resourceCulture);
            }
        }

        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }

        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }

        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }

        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }

        public static string DeviceDisconnected {
            get {
                return ResourceManager.GetString("DeviceDisconnected", resourceCulture);
            }
        }

        public static string DeviceInUse {
            get {
                return ResourceManager.GetString("DeviceInUse", resourceCulture);
            }
        }

        public static string DeviceInUseByFormat1 {
            get {
                return ResourceManager.GetString("DeviceInUseByFormat1", resourceCulture);
            }
        }

        public static string TestCamera {
            get {
                return ResourceManager.GetString("TestCamera", resourceCulture);
            }
        }
    }
}