[assembly: InternalsVisibleTo("Atc.Wpf.Controls.Tests")]
[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]

[assembly: XmlnsPrefix("https://github.com/atc-net/atc-wpf/tree/main/schemas", "atc")]
[assembly: XmlnsDefinition(@"https://github.com/atc-net/atc-wpf/tree/main/schemas", "Atc.Wpf.Controls")]
[assembly: XmlnsDefinition(@"https://github.com/atc-net/atc-wpf/tree/main/schemas", "Atc.Wpf.Controls.BaseControls")]
[assembly: XmlnsDefinition(@"https://github.com/atc-net/atc-wpf/tree/main/schemas", "Atc.Wpf.Controls.LabelControls")]
[assembly: XmlnsDefinition(@"https://github.com/atc-net/atc-wpf/tree/main/schemas", "Atc.Wpf.Controls.Layouts")]
[assembly: XmlnsDefinition(@"https://github.com/atc-net/atc-wpf/tree/main/schemas", "Atc.Wpf.Controls.Progressing")]
[assembly: XmlnsDefinition(@"https://github.com/atc-net/atc-wpf/tree/main/schemas", "Atc.Wpf.Controls.Viewers")]