// ReSharper disable CheckNamespace
namespace Atc.Wpf.Theming;

public enum AtcAppsBrushKeyType
{
    Highlight,
    AccentBase,
    Accent,
    Accent2,
    Accent3,
    Accent4,
    ThemeBackground,
    ThemeBackground1,
    ThemeBackground2,
    ThemeBackground3,
    ThemeBackground4,
    ThemeBackground5,
    ThemeBackground6,
    ThemeBackground7,
    ThemeForeground7,
    ThemeForeground6,
    ThemeForeground5,
    ThemeForeground4,
    ThemeForeground3,
    ThemeForeground2,
    ThemeForeground1,
    ThemeForeground,
    IdealForeground,
    Gray1,
    Gray2,
    Gray3,
    Gray4,
    Gray5,
    Gray6,
    Gray7,
    Gray8,
    Gray9,
    Gray10,
}