name: "Pre-Integration"

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  dotnet-build:
    runs-on: windows-latest
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⚙️ Setup dotnet 10.0.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: 📐 Ensure nuget.org added as package source on Windows
        run: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org --configfile $env:APPDATA\NuGet\NuGet.Config
        continue-on-error: true

      - name: 🔁 Restore packages
        run: dotnet restore

      - name: 🛠️ Building library in release mode
        run: dotnet build -c Release --no-restore

  dotnet-test:
    runs-on: windows-latest
    needs:
      - dotnet-build
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: ⚙️ Setup dotnet 10.0.x
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.0.x"

      - name: 📐 Ensure nuget.org added as package source on Windows
        run: dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org --configfile $env:APPDATA\NuGet\NuGet.Config
        continue-on-error: true

      - name: 🔁 Restore packages
        run: dotnet restore

      - name: 🛠️ Build
        run: dotnet build -c Release --no-restore /p:UseSourceLink=true

      - name: 🧪 Run unit tests with code coverage
        run: dotnet test -c Release --no-build -- --coverage --coverage-output-format cobertura

      - name: 📤 Upload coverage reports as workflow artifacts
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-cobertura
          path: '**/TestResults/**/*.cobertura.xml'
          if-no-files-found: warn
          retention-days: 14
